DugisGuideViewer:RegisterGuide("Shadowfang Keep (18-22)", "Blackfathom Deeps (20-24)", "Horde", "I", function()
return [[
AAA


KIbsbi.5ObnrfobayKyVlrjrpq_b^qib^pqibsbi.5qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-.0yyMIy.5y
ORkabo`fqvyNFAy.-.0yyKyOrkqlqebRkabo`fqv%3/)4-&yyWy.1/-y
eRkabo`fqvyNFAy.-.0yyKy%km`7341.&fkxRkabo`fqvz%34+4)04+6&yyWy.125yyKM@y341.y
>Qeb?llhlcRoyNFAy.-.0yyKy%km`7/601&fkxRkabo`fqvz%21+3)21+/&yyWy.125yyKM@y/601y

OQebPbmri`eboyKyQo^sbiqlPbmri`ebo%12+3)1/+3&yyWy.1/.yyNFAy.-.1y
>>ord^iJrpqAfbyNFAy.-.1yyKy%km`7.605&fkxQebPbmri`eboz%11+/)06+6&yyWy.1/.yyKM@y.605y
>Ab^qepq^ihbopfkPe^altc^kdyNFAy.-65yyKy%km`7.62/&fkxQebPbmri`eboz%10+1)1-+6&yyWy.1/.yyKM@y.62/y
QJro^OrkbqlqbjyNFAy00-.yyKy%km`75052&fkxQebPbmri`eboz%1/+62)1.+65&yyWy.1/.yyLyyKM@y5052y

OPe^altc^kdHbbmyKyBkqboPe^altc^kdHbbmtfqe^m^oqvlc2)ibsbi/-fpob`ljjbkabayyFy

QAb^qepq^ihbopfkPe^altc^kdyNFAy.-65yyKyObib^pb^Ab^qepq^ihbokb^oqebpq^oqqlrkil`hqeballoql`lkqfkrbtfqeqebfkpq^k`b9_o,;9_o,;%km`71111&`^k_bpbbkivfkdlkqeblqebopfablcqebdo^qbgrpq^pvlrbkqboqebfkpq^k`b+Vlrtfiie^sbqltlohvlrot^valtkqlefjqlcfkfpeqebnrbpq+yyWy.1/.yyAJ>MyPe^altc^kd\Hbbm\EyyKM@y1111y
@Qeb?llhlcRoyNFAy.-.0yyKy%fqbj73/50&fpfkqebolljtfqe%km`71/41&+Fqplkqebibcq^pvlrbkqboqebolljlkqeb_llhpebic)lk`bpljblkbdbqpqefp_llhfqafp^mmb^opclo^cbtpb`lkap+Fqtfiiobpm^tk+yyWy.125yyAJ>MyPe^altc^kd\Hbbm\EyyKM@y1/41y
@>ord^iJrpqAfbyNFAy.-.1yyKyHfii%km`71/42&^ka`liib`q%fqbj7211/&)ebfpqebcfk^i_lpp+yyWy.1/.yyAJ>MyPe^altc^kd\Hbbm\EyyKM@y1/42y

OQebPbmri`eboyKyQo^sbiqlPbmri`ebo%12+3)1/+3&yyWy.1/.yyNFAy.-.1y
Q>ord^iJrpqAfbyKy%km`7.605&fkxQebPbmri`eboz%11+/)06+6&yyWy.1/.yyKM@y.605y

ORkabo`fqvyQFAy.-.0yyKyQo^sbiqlqebRkabo`fqv%3/)4-&yyWy.1/-y
QQeb?llhlcRoyNFAy.-.0yyKy%km`7/601&fkxRkabo`fqvz%21+3)21+/&yyWy.125yyKM@y/601y

KDrfab@ljmibqb


]]
end)
