DugisGuideViewer:RegisterGuide("Eversong Woods (1-13 Blood Elf)", "Ghostlands (13-20)", "Horde", "L", function()
return [[
AAA

>Ob`i^fjfkdPrkpqofaboFpibyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy50/2y
@Ob`i^fjfkdPrkpqofaboFpibyKyHfii5J^k^Tvojp%02).6&yyNFAy50/2y
QOb`i^fjfkdPrkpqofaboFpibyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy50/2y
>Rkcloqrk^qbJb^probpyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy50/3y

>ErkqboQo^fkfkdy@yErkqboyyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy6060y
>T^oil`hQo^fkfkdy@yT^oil`hyyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy5230y
>OldrbQo^fkfkdy@yOldrbyyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy606/y
>J^dbQo^fkfkdy@yJ^dbyyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy50/5y
>MofbpqQo^fkfkdy@yMofbpqyyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy5231y
>M^i^afkQo^fkfkdy@yM^i^afkyyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy6343y

QErkqboQo^fkfkdy@yErkqboyyKyO^kdboP^iifk^%06)/-+.&yyNFAy6060y
QT^oil`hQo^fkfkdy@yT^oil`hyyKyPrjjlkboQbif$I^ofbk%05+6)/.+1&yyNFAy5230y
QOldrbQo^fkfkdy@yOldrbyyKyM^qepq^ihboH^ofbi%05+6)/-+.&yyNFAy606/y
QJ^dbQo^fkfkdy@yJ^dbyyKyGrif^Prkpqofhbo%06+/)/.+1&yyNFAy50/5y
QMofbpqQo^fkfkdy@yMofbpqyyKyJ^qolk>obk^%06+1)/-+1&yyNFAy5231y
QM^i^afkQo^fkfkdy@yM^i^afkyyKyGbpqebkfpPrkpqofhbo%06+1)/-+3&yyNFAy6343y


>TbiiT^q`eboPli^kf^ky@yErkqboyyKyO^kdboP^iifk^%06)/-+.&yyNFAy.--4-y
>TbiiT^q`eboPli^kf^ky@yT^oil`hyyKyPrjjlkboQbif$I^ofbk%05+6)/.+1&yyNFAy.--40y
>TbiiT^q`eboPli^kf^ky@yOldrbyyKyM^qepq^ihboH^ofbi%05+6)/-+.&yyNFAy.--4.y
>TbiiT^q`eboPli^kf^ky@yJ^dbyyKyGrif^Prkpqofhbo%06+/)/.+1&yyNFAy.--35y
>TbiiT^q`eboPli^kf^ky@yMofbpqyyKyJ^qolk>obk^%06+1)/-+1&yyNFAy.--4/y
>TbiiT^q`eboPli^kf^ky@yM^i^afkyyKyGbpqebkfpPrkpqofhbo%06+1)/-+3&yyNFAy.--36y

QTbiiT^q`eboPli^kf^ky@yErkqboyyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy.--4-y
QTbiiT^q`eboPli^kf^ky@yT^oil`hyyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy.--40y
QTbiiT^q`eboPli^kf^ky@yOldrbyyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy.--4.y
QTbiiT^q`eboPli^kf^ky@yJ^dbyyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy.--35y
QTbiiT^q`eboPli^kf^ky@yMofbpqyyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy.--4/y
QTbiiT^q`eboPli^kf^ky@yM^i^afkyyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy.--36y

>QebPeofkblcA^qe$Obj^oyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy5012y
>Pli^kf^k$p?bilkdfkdpyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy500-y
>>CfpqcrilcPifsbopyKy>o`^kfpqFqe^k^p%05+0).6+/&yyNFAy5003y
>QefopqRkbkafkdyKy>o`^kfpqEbiflk%04+/).6&yyNFAy5013y

@Rkcloqrk^qbJb^probpyKy@liib`q5XIvku@lii^opZcoljpi^fkPmofkdm^tIvkubp^kaPmofkdm^t@r_p%03)//&yyNFAy50/3y
QRkcloqrk^qbJb^probpyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy50/3y
>ObmloqqlI^kqe^kMbofilkyKyJ^dfpqofuBolk^%05+/)/-+6&yyNFAy50/4y
QObmloqqlI^kqe^kMbofilkyKyI^kqe^kMbofilk%02+1)//+2&yyNFAy50/4y
>>ddobppflkyKyI^kqe^kMbofilk%02+1)//+2&yyNFAy5001y

@>ddobppflkyKyHfii4Qbkabop^ka4Cbo^iQbkabop%01)/3&yyNFAy5001y
@QebPeofkblcA^qe$Obj^oyKyOb^aqebmi^nrblkqebPeofkblcA^qe$Obj^o%/6).6&yyNFAy5012y
@QefopqRkbkafkdyKyRpbvlro>o`^kbQloobkqo^`f^i^_fifqvlk^J^k^Tvoj%02).6&yyNFAy5013y
@>CfpqcrilcPifsbopyKyHfiiqebJ^k^TvojpcloqebfoX>o`^kbPifsbopZ^olrka%02)/-&yyNFAy5003y
@Pli^kf^k$p?bilkdfkdpyKy@liib`qTbiiT^q`ebo$pXPli^kf^k$pGlrok^iZ%04)/1&)XP`oliilcP`lrodbJ^df`Z%0.)//&^kaXPli^kf^k$pP`ovfkdLo_Z%02)/5&yyNFAy500-y

QQefopqRkbkafkdyKy>o`^kfpqEbiflk%04+/).6&yyNFAy5013y
Q>CfpqcrilcPifsbopyKy>o`^kfpqFqe^k^p%05+0).6+/&yyNFAy5003y
QQebPeofkblcA^qe$Obj^oyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy5012y
QPli^kf^k$p?bilkdfkdpyKyTbiiT^q`eboPli^kf^k%05+5).6+2&yyNFAy500-y
Q>ddobppflkyKyI^kqe^kMbofilk%02+1)//+2&yyNFAy5001y

>Cbibkaobkqeb?^kfpebayKyI^kqe^kMbofilk%02+1)//+2&yyNFAy5002y
@Cbibkaobkqeb?^kfpebayKyHfii5>o`^kbTo^fqep^ka/Q^fkqba>o`^kbTo^fqep)^ptbii^pCbibkaobkqeb?^kfpebatelj`^k_bclrka^qqebqlmlcqebqltbo%0/)/2&yyNFAy5002y
QCbibkaobkqeb?^kfpebayKyI^kqe^kMbofilk%02+1)//+2&yyNFAy5002y

>>fafkdqebLrqorkkbopyKyI^kqe^kMbofilk%02+1)//+2&yyNFAy5014y
>Q^fkqba>o`^kbPifsboyIy/-150yyLyyKyQebfqbjXQ^fkqba>o`^kbPifsboZpq^oqpnrbpq*aolmplcQ^fkqba>o`^kbTo^qe^olrka%0/)/2&yyNFAy5005y
QQ^fkqba>o`^kbPifsboyLyyKy>o`^kfpqEbiflk%04+/).6&yyNFAy5005y

OA^tkfkdI^kbyKyOrkqlAt^tkfkdI^kb%1-+2)0/+/&yyNFAy64-1y
Q>fafkdqebLrqorkkbopyKyLrqorkkbo>i^oflk%1-+2)0/+/&yyNFAy5014y
>Pi^fk_vqebTobq`ebayKyLrqorkkbo>i^oflk%1-+2)0/+/&yyNFAy64-1y
QPi^fk_vqebTobq`ebayKyPi^fkLrqorkkbo%1/+-)02+3&yyNFAy64-1y
>M^`h^dbOb`lsbovyKyPi^fkLrqorkkbo%1/+-)02+3&yyNFAy64-2y
QM^`h^dbOb`lsbovyKyLrqorkkbo>i^oflk%1-+2)0/+/&yyNFAy64-2y
>@ljmibqfkdqebAbifsbovyKyLrqorkkbo>i^oflk%1-+2)0/+/&yyNFAy502-y

OC^i`lktfkdPnr^obyKyOrkqlC^i`lktfkdPnr^ob%14+/)13+0&yyNFAy514/y
>J^gloJ^icrk`qflkyKyJ^dfpqboG^olkfp%14+/)13+0&yyNFAy514/y
>Rkpq^_ibJ^k^@ovpq^ipyKy>bialkPrk_o^ka%15+.)13&yyNFAy5130y
>T^kqba7Qe^bifpqebErkdboboyKyT^kqba7Qe^bifpqebErkdbobo%15+.)13+0&yyNFAy5135y
Q@ljmibqfkdqebAbifsbovyKyFkkhbbmboAbi^kfbi%15+.)14+4&yyNFAy502-y
eC^i`lktfkdPnr^obyKyFkkhbbmboAbi^kfbi%15+.)14+4&yyNFAy5562y

@J^gloJ^icrk`qflkyKy@liib`q3X>o`^kb@lobpZcoljqeb>o`^kbM^qoliibop%11+/)22+0&yyNFAy514/y
@Rkpq^_ibJ^k^@ovpq^ipyKyD^qebo3XRkpq^_ibJ^k^@ovpq^ipZaolmmba_vTobq`ebaRo`efk%12)1-&yyNFAy5130y
@T^kqba7Qe^bifpqebErkdboboyKyHfiiQe^bifp%12)05&yyNFAy5135y

QJ^gloJ^icrk`qflkyKyJ^dfpqboG^olkfp%14+/)13+0&yyNFAy514/y
QRkpq^_ibJ^k^@ovpq^ipyKy>bialkPrk_o^ka%15+.)13&yyNFAy5130y
QT^kqba7Qe^bifpqebErkdboboyKyPbodb^kqH^k$obk%14+4)13+3&yyNFAy5135y
>AbifsbovqlqebKloqeP^k`qrjyKyJ^dfpqboG^olkfp%14+/)13+0&yyNFAy5562y
>A^ok^ppf^kFkqorpflkpyKy>bialkPrk_o^ka%15+.)13+-&yyNFAy602/y

OKloqeP^k`qrjyKyOrkqlKloqeP^k`qrj%12+/)23+1&yyNFAy6-02y
>Ol^apfab>j_rpeyKy>mmobkqf`bO^ibk%12+/)23+1&yyNFAy6-02y
QAbifsbovqlqebKloqeP^k`qrjyKyIbv*Hbbmbo@^fa^kfp%11+4)20+.&yyNFAy5562y
>J^icrk`qflk^qqebTbpqP^k`qrjyKyIbv*Hbbmbo@^fa^kfp%11+4)20+.&yyNFAy6..6y

QJ^icrk`qflk^qqebTbpqP^k`qrjyKyIbv*HbbmboSbi^kf^%03+4)24+2&yyNFAy6..6y
>>o`^kbFkpq^_fifqvyKyIbv*HbbmboSbi^kf^%03+4)24+2&yyNFAy5153y
@>o`^kbFkpq^_fifqvyKyHfii2J^k^to^fqep^ka2J^k^Pq^ihbop%03)25&yyNFAy5153y
@A^ok^ppf^kFkqorpflkpyKyHfii^A^ok^ppf^kP`lrq^qqebTbpqP^k`qrj%01)3.&yyNFAy602/y
Q>o`^kbFkpq^_fifqvyKyIbv*HbbmboSbi^kf^%03+4)24+2&yyNFAy5153y
QA^ok^ppf^kFkqorpflkpyKyIbv*HbbmboSbi^kf^%03+4)24+2&yyNFAy602/y

>CfpeEb^ap)CfpeEb^ap+++yKyE^qesbiflkPrkd^wb%0-)25+2&yyNFAy5551y
@CfpeEb^ap)CfpeEb^ap+++yKyHfiiqebJroil`p^kad^qebo5XDofjp`^ibJroil`Eb^apZ^olrka%/5)25&yyNFAy5551y
QCfpeEb^ap)CfpeEb^ap+++yKyE^qesbiflkPrkd^wb%0-)25+2&yyNFAy5551y
>QebOfkdlcJjjooodddiiiyKyE^qesbiflkPrkd^wb%0-)25+2&yyNFAy5552y
>Dofjp`^ibMfo^qbpyKy@^mq^fkHbifpbkao^)plrqelcTbpqP^k`qrj%03+0)34+4&yyNFAy5553y
>@^mq^fkHbifpbkao^$pIlpqOrqqbopyRy/.443yyLyyKyQebfqbjX@^mq^fkHbifpbkao^$pIlpqOrqqbopZpq^oqpnrbpq*aolmmba^olrka%/2)4-&^ka%/4)3-&yyNFAy5554y
Q@^mq^fkHbifpbkao^$pIlpqOrqqbopyLyyKy@^mq^fkHbifpbkao^%03+0)34+4&yyNFAy5554y
>Ilpq>oj^jbkqpyKySbibkaofpTefqbjlok%03+0)30+5&yyNFAy515-y

OC^fo_obbwbSfii^dbyKyCliiltqebol^aB^pq%11+4)36+4&yyNFAy516.y
>Mbiq@liib`qflkyKySbi^k?ofdeql^h%11+4)36+4&yyNFAy516.y
>QebT^vt^oa>mmobkqf`byKyJ^dfpqofuI^kao^A^tkpqofabo%11+/)4-+4&yyNFAy6/21y
>Pfqr^qflk^qPrkp^fi>k`elo^dbyKyO^kdboAbdlifbk%10+1)4-+5&yyNFAy556/y
eC^fo_obbwbSfii^dbyKyJ^okfbi>j_boifdeq%10+4)4.+/&yyNFAy6-3/y

QOl^apfab>j_rpeyKy>mmobkqf`bJbibalo%11+5)3-+6&yyNFAy6-02y
>Pl^hbaM^dbpyKy>mmobkqf`bJbibalo%11+5)3-+6&yyNFAy6-3/y
@Pl^hbaM^dbpyKyX>kqebli$pBibjbkq^iDofjlfobZfpfkqebt^qbo%11)3/&grpqplrqetbpqlcqe^q_ofadbyyNFAy6-3/y
QPl^hbaM^dbpyKy>mmobkqf`bJbibalo%11+5)3-+6&yyNFAy6-3/y
>Q^hfkdqebC^iiyKy>mmobkqf`bJbibalo%11+5)3-+6&yyNFAy6-31y

OC^i`lktfkdPnr^obyKyOrkqlC^i`lktfkdPnr^ob%15+/)13+-&yyNFAy5150y
>Fk`ofjfk^qfkdAl`rjbkqpyRy/-432yyLyyKyQebfqbjXFk`ofjfk^qfkdAl`rjbkqpZpq^oqpnrbpq*aolmmba_vA^ok^ppf^kP`lrqp^olrka%01)3-&yyNFAy515/y
QFk`ofjfk^qfkdAl`rjbkqpyLyyKy>bialkPrk_o^ka%15+/)13+-&yyNFAy515/y
>QebAt^osbkPmvyKy>bialkPrk_o^ka%15+/)13+-&yyNFAy5150y
@QebAt^osbkPmvyKyQ^ihqlMolpmb`qlo>ksfit^oa^qqebKloqeP^k`qrj+Cliiltefjrmqebpmfo^ipq^fop^ka^qq^`hefjtebkebqrokpelpqfib%11)20&yyNFAy5150y
QQebAt^osbkPmvyKy>bialkPrk_o^ka%15+/)13+-&yyNFAy5150y

>QebAb^aP`^oyKyO^kdboG^bi^%2-+0)2.&yyNFAy5142y
@QebAb^aP`^oyKyPi^v5Mi^drb_lkbMfii^dbop%16)25&yyNFAy5142y
QQebAb^aP`^oyKyO^kdboG^bi^%2-+0)2.&yyNFAy5142y
QQ^hfkdqebC^iiyKyFkpqor`qlo>kqebli%22+4)21+2&yyNFAy6-31y
>PtfcqAfp`fmifkbyKyFkpqor`qlo>kqebli%22+4)21+2&yyNFAy6-33y

OC^opqofaboObqob^qyKyOrkqlC^opqofaboObqob^q%3-+/)3.+2&yyNFAy5143y
>>j^kfBk`ol^`ejbkqyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy5143y
>QebPmb^o`o^cqbo$pE^jjboyKy>o^qebiPrkclodb%26+3)3/+3&yyNFAy5144y
>QebJ^dfpqbo$p>mmobkqf`byKyJ^dfpqboArphtfqebo%3-+/)3.+2&yyNFAy5555y

QQebT^vt^oa>mmobkqf`byKy>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy6/21y
>@loormqbaPlfiyKy>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy5154y
@@loormqbaPlfiyKy@liib`q5XQ^fkqbaPlfiP^jmibpZ^olrka%20)36&yyNFAy5154y
Q@loormqbaPlfiyKy>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy5154y
>Rkbumb`qbaObpriqpyKy>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy5155y
@Rkbumb`qbaObpriqpyKyMolqb`q>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy5155y
QRkbumb`qbaObpriqpyKy>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy5155y
>Obpb^o`eKlqbpyKy>mmobkqf`bJfosba^%21+0)4.+-&yyNFAy6/22y

EC^fo_obbwbSfii^dbyRy3615yyNFAy6/25y
>QebP`lo`ebaDolsbyKy>oabvkOfsbotfka%10+3)4.+/&yyNFAy6/25y
>O^kdboP^obvkyKyJ^okfbi>j_boifdeq%10+4)4.+/&yyNFAy6025y
QObpb^o`eKlqbpyKyJ^dfpqofuI^kao^A^tkpqofabo%11+.)4-+4&yyNFAy6/22y
>P^iqebofi$pE^sbkyKyJ^dfpqofuI^kao^A^tkpqofabo%11+.)4-+4&yyNFAy6062y

KHfii^kv`^qpcloMbiq@liib`qflkyNFAy516.y
OP^iqebofi$pE^sbkyKyOrkqlP^iqebofi$pE^sbktbpq^q%05+/)40+2&yyNFAy6-34y
QP^iqebofi$pE^sbkyKyIloaP^iqebofi%05+/)40+2&yyNFAy6062y
>QebM^oqvKbsboBkapyKyIloaP^iqebofi%05+/)40+2&yyNFAy6-34y

@QebOfkdlcJjjooodddiiiyKyHfiiJjjooodddiiilkqebpelob%/2)36&yyNFAy5552y
@Dofjp`^ibMfo^qbpyKyD^qebo3lcX@^mq^fkHbifpbkao^$p@^odlZ^olrka%/1)35&yyNFAy5553y
QQebOfkdlcJjjooodddiiiyKyE^qesbiflkPrkd^wb%0-)25+2&yyNFAy5552y

@Ilpq>oj^jbkqpyKyD^qebo5XPfk$alobf>oj^jbkqpZqlqebPlrqe^qPrkp^fi>k`elo^db%01)35&yyNFAy515-y
@Pfqr^qflk^qPrkp^fi>k`elo^dbyKyHfii2Tobq`ebaQerdp^ka2Tobq`ebaEllifd^kp%0/)4-&yyNFAy556/y
QIlpq>oj^jbkqpyKySbibkaofpTefqbjlok%03+0)30+5&yyNFAy515-y
QDofjp`^ibMfo^qbpyKy@^mq^fkHbifpbkao^%03+0)34+4&yyNFAy5553y
>Tobq`ebaOfkdib^aboyKySbibkaofpTefqbjlok%03+0)30+5&yyNFAy6-43y
@Tobq`ebaOfkdib^aboyKyHfii>ia^olkqebOb`hibpp^qqebsbovqlmlc_rfiafkd^qqebPrkp^fi>k`elo^db%0/+4)4-&yyNFAy6-43y
QTobq`ebaOfkdib^aboyKySbibkaofpTefqbjlok%03+0)30+5&yyNFAy6-43y
@Mbiq@liib`qflkyKyHfiiPmofkdm^t^kad^qebo3XPmofkdm^tMbiqpZ%13)34&yyNFAy516.y

QMbiq@liib`qflkyKySbi^k?ofdeql^h%11+4)36+4&yyNFAy516.y
QPfqr^qflk^qPrkp^fi>k`elo^dbyKyO^kdboAbdlifbk%10+1)4-+5&yyNFAy556/y
>JfppfkdfkqebDelpqi^kapyKyJ^dfpqofuI^kao^A^tkpqofabo%11+.)4-+4&yyNFAy6.11y
QO^kdboP^obvkyKyO^kdboP^obvk%14)4.+6&yyNFAy6025y
>AbcbkafkdC^fo_obbwbSfii^dbyKyO^kdboP^obvk%14)4.+6&yyNFAy6/2/y

QJfppfkdfkqebDelpqi^kapyKy@lrofboA^tkpqofabo%16)56&yyNFAy6.11y
>QebC^iibk@lrofboyKy>mlqeb`^ovQebao^%16)56&yyNFAy6.14y
@QebC^iibk@lrofboyKyHfiiJfpq_^qp^kaPq^osfkdDelpq`i^tpcloqebXMi^drba?illaP^jmibpZ%14).0&yyWyDelpqi^kapyyNFAy6.14y
QQebC^iibk@lrofboyKy>mlqeb`^ovQebao^%16)56&yyNFAy6.14y
>AbifsbovqlQo^knrfiifbkyKy@lrofboA^tkpqofabo%16)56&yyNFAy6.15y
@AbcbkafkdC^fo_obbwbSfii^dbyKyPi^v1Olqifj_J^o^rabop^ka1A^ohto^fqep%2-)42&yyNFAy6/2/y
>MltbofkdlroAbcbkpbpyKyOrkbt^oabkAbov^k)^qqeborkbpqlkb%1/)52+2&yyNFAy516-y
@MltbofkdlroAbcbkpbpyKyMi^`bqebXFkcrpba@ovpq^iZ^qqebB^pqbokOrkbpqlkb^kamolqb`qfqcoljqebP`lrodbclo.jfkrqb%22)51&yyRy//360yyNFAy516-y
@PtfcqAfp`fmifkbyKyRpbX>kqebli$pAfp`fmifk^ovOlaZlkefpqtlpqrabkqp)Jbibalo%11)3-&^kaO^ibk%12)23&yyRy//140yyNFAy6-33y
QPtfcqAfp`fmifkbyKyFkpqor`qlo>kqebli%22+4)21+2&yyNFAy6-33y

>PbbhqebC^opqofabopy@yErkqboyyKyQbibkrp%15)12+6&yyLyyNFAy63.4y
QPbbhqebC^opqofabopy@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyLyyNFAy63.4y

>Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6151y
@Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyRpbqebXQ^jfkdOlaZqlq^jb^k@o^wbaAo^dlke^thkb^oqebqltk%3-)3/&yyRy/0364yyNFAy6151y
QQ^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6151y
>Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6153y
@Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyRpbqebXQ^jfkdOlaZlk^BiaboPmofkdm^tkb^oqebqltk%3/)3/&yyRy/04-/yyNFAy6153y
QQ^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6153y
>Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6152y
ODelpqi^kay@yErkqboyyKyOrkqlDelpqi^ka%15)63&yyNFAy6340y
@Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyDlplrqeqlDelpqi^ka^karpbqebXQ^jfkdOlaZlk^Jfpq_^q%15).2&yyRy/04-0yyWyDelpqi^kapyyNFAy6152y
QQ^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6152y
>?b^pqQo^fkfkdy@yErkqboyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6340y

OPfisbojllk@fqvyKyOrkqlPfisbojllk@fqv%23+4)13+6&yyNFAy5556y
?XPrkqlr`ebaPmb`f^iObpbosbZyKySfkbj^pqboPrkqlr`eba%5-)25&)cloQebM^oqvKbsboBkapyyWyPfisbojllk@fqvyyIy//442yyNFAy5556y
Q?b^pqQo^fkfkdy@yErkqboyyKyE^iqebkfp%5/)/5&yyNFAy6340yyWyPfisbojllk@fqvy
>QebPqlkby@yT^oil`hyyKyQ^iflkf^%40+2)13+2&yyNFAy62/6yyWyPfisbojllk@fqvy
ePfisbojllk@fqvy@yT^oil`hyyKyFkkhbbmboGlsf^%34+4)40+-&yyWyPfisbojllk@fqvyyNFAy5556y
ODelpqi^kay@yT^oil`hyyKyOrkqlDelpqi^ka%15)63&yyNFAy5556y
QQebPqlkby@yT^oil`hyyKySlfapqlkb%10).2&yyNFAy62/6yyWyDelpqi^kapy
>QebOrkblcPrjjlkfkdy@yT^oil`hyyKySlfapqlkb%10).2&yyNFAy63.6yyWyDelpqi^kapy
@QebOrkblcPrjjlkfkdy@yT^oil`hyyKyDlqlqeb0oacillolcqebq^iibpq_rfiafkdfkDliabkjfpqSfii^db%/3).2&^karpbqebXSlfapqlkbZqlprjjlk^kahfii^slfat^ihboyyRy/040/yyNFAy63.6yyWyDelpqi^kapy
EPfisbojllk@fqvy@yT^oil`hyyRy3615yyNFAy5556y
QQebOrkblcPrjjlkfkdy@yT^oil`hyyKyQ^iflkf^%40+2)13+2&yyNFAy63.6yyWyPfisbojllk@fqvy

OBsboplkdTllapyKyOrkqlBsboplkdTllap%4/+3)62+0&yyWyPfisbojllk@fqvyyNFAy5556y
QQebJ^dfpqbo$p>mmobkqf`byKy>mmobkqf`bIlo^iqe^ifp%34+5)23+2&yyNFAy5555y
>Ab^`qfs^qfkdqebPmfobyKy>mmobkqf`bIlo^iqe^ifp%34+5)23+2&yyNFAy5556y
>Tebob$pTviifqebk<yKy>mmobkqf`bIlo^iqe^ifp%34+5)23+2&yyNFAy6061y
@Ab^`qfs^qfkdqebPmfobyKyRpbXAb^`qfs^qfkdGbtbiZqlab^`qfs^qbqeb0ArphtfqeboPmfobMltboPlro`bpfkpfabArphtfqeboPmfob%34)23&yyRy/1004yyNFAy5556y
>>_^kalkbaFksbpqfd^qflkpyKyJ^dfpqboArphtfqebo$pGlrok^i%36+/)2/+.&yyNFAy556.y
QTebob$pTviifqebk<yKyDolrkaphbbmboTviifqebk%35+4)14&yyNFAy6061y
>@ib^kfkdrmqebDolrkapyKyDolrkaphbbmboTviifqebk%35+4)14&yyNFAy5561y
@@ib^kfkdrmqebDolrkapyKyHfii3J^k^Pbombkqp^ka3BqeboCfbkap%34)16&yyNFAy5561y
Q@ib^kfkdrmqebDolrkapyKyDolrkaphbbmboTviifqebk%35+4)14&yyNFAy5561y
QAb^`qfs^qfkdqebPmfobyKy>mmobkqf`bIlo^iqe^ifp%34+5)23+2&yyNFAy5556y
>TloacoljqebPmfobyKy>mmobkqf`bIlo^iqe^ifp%34+5)23+2&yyNFAy556-y

OC^opqofaboObqob^qyKyOrkqlC^opqofaboObqob^q%3-+/)3.+2&yyNFAy5146y
QTloacoljqebPmfobyKyJ^dfpqboArphtfqebo%3-+/)3.+2&yyNFAy556-y
Q>_^kalkbaFksbpqfd^qflkpyKyJ^dfpqboArphtfqebo%3-+/)3.+2&yyNFAy556.y
@QebPmb^o`o^cqbo$pE^jjboyKyHfiiPmb^o`o^cqboLqbj_b^kaillqqebE^jjbo%4-)4/&yyNFAy5144y
>Wri$J^olpeyKySbk$g^pef%4-+2)4/+1&yyNFAy5146y
@Wri$J^olpeyKyHfii@efbcq^fkWri$J^olpefkWb_$T^qe^%3.+3)46+3&yyNFAy5146y
QWri$J^olpeyKySbk$g^pef%4-+2)4/+1&yyNFAy5146y
>>j^kfFks^pflkyRy/0/16yyKyQebfqbjX>j^kfFks^pflkMi^kpZpq^oqpnrbpq*aolmmba_v@efbcq^fkWri$J^olpe%3.+3)46+3&yyLyyNFAy603-y
@>j^kfBk`ol^`ejbkqyKyHfii2>j^kf?bopbohbop^ka2>j^kf>ubQeoltbop%36)4/&yyNFAy5143y

QQebPmb^o`o^cqbo$pE^jjboyKy>o^qebiPrkclodb%26+3)3/+3&yyNFAy5144y
?XPmofkdm^t>mmbqfwbopZyKyColjW^ibkbCfopqifdeq%3-)30&)cloQebM^oqvKbsboBkapyyIy//443yyNFAy6030y
Q>j^kfBk`ol^`ejbkqyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy5143y
Q>j^kfFks^pflkyLyyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy603-y
>T^okfkdC^fo_obbwbSfii^dbyKyIfbrqbk^kqA^tkorkkbo%3-+1)3/+5&yyNFAy6030y

OC^fo_obbwbSfii^dby@yT^oil`hyyKyOrkqlC^fo_obbwbSfii^db%10+1)4-+5&yyNFAy5140y
EC^fo_obbwbSfii^dby@yErkqbo)Oldrb)J^db)Mofbpq)M^i^afkyyRy3615yyNFAy5140y
QT^okfkdC^fo_obbwbSfii^dbyKyO^kdboAbdlifbk%10+1)4-+5&yyNFAy6030y
?X?rkaiblcCfobtlohpZyKyColjqebDbkbo^idllapsbkalo)cloQebM^oqvKbsboBkapyyIy//444yyNFAy5140y
QAbcbkafkdC^fo_obbwbSfii^dbyKyO^kdboP^obvk%14)4/&yyNFAy6/2/y

QQebM^oqvKbsboBkapyKyIloaP^iqebofi%05+/)40)2&)mf`hrmqebm^oqvdllaplkqebq^_ibpyyNFAy6-34y
QQebP`lo`ebaDolsbyKyI^of^kk^Ofsbotfka%00+2)5-&yyNFAy6/25y
>>Plj_boQ^phyKyI^of^kk^Ofsbotfka%00+2)5-&yyNFAy5140y
@>Plj_boQ^phyKyPi^v.-TfqebobaDobbkHbbmbop^qqebP`lo`ebaDolsb%0/)50&yyNFAy5140y
>LiaTefqb_^oh$pMbka^kqyKyRpbXLiaTefqb_^oh$pMbka^kqZql_bdfknrbpq)aolmmba_vLiaTefqb_^oh%02)52&yyRy/0//5yyNFAy5141y
Q>Plj_boQ^phyKyI^of^kk^Ofsbotfka%00+2)5-&yyNFAy5140y
QLiaTefqb_^oh$pMbka^kqyKyI^of^kk^Ofsbotfka%00+2)5-&yyNFAy5141y
>Tefqb_^oh$pJbjlovyKyDfsbk_vXLiaTefqb_^oh$pMbka^kqZyyNFAy.-.33y
@Tefqb_^oh$pJbjlovyKy?rovXLiaTefqb_^oh$pMbka^kqZ^q%04+2)52+5&^kacfdeqefppmfofqqlilteb^iqeyyRy/5/-6yyNFAy.-.33y
QTefqb_^oh$pJbjlovyKyTefqb_^oh$pPmfofq%04+2)52+5&&yyNFAy.-.33y
QMltbofkdlroAbcbkpbpyKyOrkbt^oabkAbov^k%11+/)52+2&yyNFAy516-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

--[[
A Windows to the Source |C|Warlock| |N|Summoner Teli'Larien (38.9, 21.4)| |QID|8344|
C Windows to the Source |C|Warlock| |N|Kill Arcane Wraiths and gather 4 [Wraith Essences] and 1 [Tainted Wraith Essence] around (32, 25)| |QID|8344|
T Windows to the Source |C|Warlock| |N|Summoner Teli'Larien (38.9, 21.4)| |QID|8344|
]]
