
DugisGuideViewer:RegisterGuide("The Barrens (22-23)", "Stonetalon Mountains (23-25)", "Horde", "L", function()
return [[
AAA

C@^jmQ^ro^glyKyAbso^h%2.+2)0-+0&yyNFAy560y
QHbk$wfdi^$pAo^rdeqy@yT^oil`hyyKyDorkqIldj^o%40+/)62+.&yyNFAy.2..y
>Aldo^k$p@^mqfsfqvy@yT^oil`hyyKyDorkqIldj^o%40+/)62+.&yyNFAy.2.2y
QGlokPhvpbboyKyPhfm%U&qefpnrbpqfcvlralk$qe^sbfq*GlokPhvpbbo%11+5)26+.&yyNFAy0/3.y
>Fpe^jre^ibyKyGlokPhvpbbo%11+5)26+.&yyNFAy55/y
e@^jmQ^ro^glyKyFkkhbbmbo?vri^%12+3)26&yyNFAy560y
>Tb^mlkplc@elf`byKyQ^qqbok^`hPqbbiclodb%12+.)24+4&yyNFAy560y

QAldo^k$p@^mqfsfqvy@yT^oil`hyyKyDorkqAldo^k%10+0)14+6&yyNFAy.2.2y
>Ilsb$pDfcqy@yT^oil`hyyKyDorkqAldo^k%10+0)14+6&yyNFAy.2./y
CLodofjj^oy@yT^oil`hyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy.2.0y
QIlsb$pDfcqy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2./y
>Qeb?fkafkdy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2.0y
@Qeb?fkafkdy@yT^oil`hyyKyRpbXAldo^k$pMbka^kqZqlprjjlk^Pr``r_rp^kahfiifqyyRy33/3yyNFAy.2.0y
QQeb?fkafkdy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2.0y
E@^jmQ^ro^gly@yT^oil`hyyRy3615yyNFAy510y

CO^q`ebqy@yPe^j^kyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy.20-y
Q@^iilcT^qbo%M^oq.&y@yPe^j^kyyKyFpibkT^qbopbbo%32+5)10+5&yyNFAy.2/6y
>@^iilcT^qbo%M^oq/&y@yPe^j^kyyKyFpibkT^qbopbbo%32+5)10+5&yyNFAy.20-y
Q@^iilcT^qbo%M^oq/&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.20-y
>@^iilcT^qbo%M^oq0&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.202y
@@^iilcT^qbo%M^oq0&y@yPe^j^kyyKyRpbXBjmqv?oltkT^qbophfkZlkqebtbii%11)44&yyRy4433yyNFAy.202y
Q@^iilcT^qbo%M^oq0&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.202y
>@^iilcT^qbo%M^oq1&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.203y

CLodofjj^oy@yPe^j^kyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy160y
CQfofpc^iDi^abpy@yPe^j^kyyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy160y
OPfisbomfkbClobpqy@yPe^j^kyyKyOrkqlPfisbomfkbClobpq%2-)46+0&yyWyQfofpc^iDi^abpyyNFAy160y
cQebPbmri`eboy@yPe^j^kyyKyH^olpO^wlh%12+3)1/+2&yyWyPfisbomfkbClobpqyyNFAy160y
>GlrokbvqlEfiip_o^aCllqefiipy@yPe^j^kyyKy>mlqeb`^ovObkcboobi%1/+6)1-+6&yyWyPfisbomfkbClobpqyyNFAy160y
OEfiip_o^aCllqefiipy@yPe^j^kyyKyOrkaltkqeolrdePfisbomfkbqebkb^pqqlEfiip_o^aCllqefiip%4.+0)5-+2&yyWyPfisbomfkbClobpqyyNFAy161y
>QfjbQlPqofhby@yPe^j^kyyKyAb^qepq^ihboIbpe^qqebPlrqemlfkqQltbo%/-+5)14+1&yyWyEfiip_o^aCllqefiipyyNFAy161y

OQ^oobkJfiiy@yPe^j^kyyKyOrkqlQ^oobkJfii%3/+0)/-+0&yyWyEfiip_o^aCllqefiipyyNFAy.201y
cQ^oobkJfiiy@yPe^j^kyyKyW^ofpb%3-+/).5+4&yyWyEfiip_o^aCllqefiipyyNFAy.201y
QQfjbQlPqofhby@yPe^j^kyyKyEfdeBub`rqloA^oqe^if^%3/+0)/-+0&yyWyEfiip_o^aCllqefiipyyNFAy161y
QGlrokbvqlEfiip_o^aCllqefiipy@yPe^j^kyyKy>mlqeb`^ovIvalk%3.+2).6+/&yyWyEfiip_o^aCllqefiipyyNFAy160y
@@^iilcT^qbo%M^oq1&y@yPe^j^kyyKyRpbXBjmqvObaT^qbophfkZlkqebtbii%3/)/-&yyWyEfiip_o^aCllqefiipyyRy4435yyNFAy.203y
E@^jmQ^ro^gly@yPe^j^kyyRy3615yyNFAy.201y

Q@^iilcT^qbo%M^oq1&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.203y
>@^iilcT^qbo%M^oq2&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.201y

@BddErkqyKyRpbXAfddfkd@i^tZlkqebjlrkap^qqebCfbialcDf^kqp%12)4/&yyRy2-26yyNFAy535y
@?bqo^v^icoljTfqefk%M^oq.&yKyHfiiHrw%10)5.&)K^h%10)50&)^kaIlhLo`_^kb%1-)5-&yyNFAy546y
@Tb^mlkplc@elf`byKyHfiit^ocobkwfbpcloqebXO^wloj^kbT^oPefbiaZ)pbbopcloqebX@e^oobaO^wloj^kbT^kaZ)^kapq^ihbopcloqebXO^wloj^kb?^`hpq^__boZ%1/)45&yyNFAy560y
>D^kk$pOb`i^j^qflkyKyD^kkPqlkbpmfob)m^qolipqebol^a%13+.)43+1&%13+.)5.+0&yyNFAy510y
@D^kk$pOb`i^j^qflkyKyHfii.2?^bi$arkBu`^s^qlop^ka2?^bi$arkClobjbk^q?^biJla^k%13)52&yyNFAy510y
QD^kk$pOb`i^j^qflkyKyD^kkPqlkbpmfob)m^qolipqebol^a%13+.)43+1&%13+.)5.+0&yyNFAy510y
>ObsbkdblcD^kk%M^oq.&yKyD^kkPqlkbpmfob)m^qolipqebol^a%13+.)43+1&%13+.)5.+0&yyNFAy513y

E@^jmQ^ro^glyKyLoork_^`hyyRy3615yyNFAy6-3y
QTb^mlkplc@elf`byKyQ^qqbok^`hPqbbiclodb%12+.)24+4&yyNFAy560y
Q?bqo^v^icoljTfqefk%M^oq.&yKyJ^kdibqllqe%11+3)26+/&yyNFAy546y
>?bqo^v^icoljTfqefk%M^oq/&yKyJ^kdibqllqe%11+3)26+/&yyNFAy6-3y

CQeb@olppol^apyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy.-62y
Q?bqo^v^icoljTfqefk%M^oq/&yKyQeloh%2.+2)0-+5&yyNFAy6-3y
QBddErkqyKyHloo^k%2.+.)/6+3&yyNFAy535y

HHfiiWebso^clo@^o`^ppyKyHfiiWebso^%3.)0/&rkqfivlrcfka^XCobpeWebso^@^o`^ppZyyIy.-005yyNFAy55/y
@Fpe^jre^ibyKyHfii^Webso^qldbq^XCobpeWebso^@^o`^ppZ)qebkrpbfq^qqebqobbkloqetbpqlcO^q`ebq%26)0-&qlprjjlkqebo^mqloqe^qvlrkbbaqlhfiiyyRy.-005yyNFAy55/y

QCroqeboFkpqor`qflkp%M^oq.&yKyPmrqqbos^isb%30+-)04+/&yyNFAy.-61y
>CroqeboFkpqor`qflkp%M^oq/&yKyPmrqqbos^isb%30+-)04+/&yyNFAy.-62y
QAbbmjlppPmfaboBddpyLyyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.-36y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
