DugisGuideViewer:RegisterGuide("Hillsbrad Foothills (29-30)", "Arathi Highlands (30)", "Horde", "L", function()
return [[
AAA

CO^q`ebqy@yT^oil`hyyKyKvpb%12+.)16+/&yyWyQelrp^kaKbbaibpyyNFAy.5-.y
>Qljblc@^_^i%M^oq.&y@yT^oil`hyyKyQefpfp^Ibsbi0-nrbpqqlprjjlkCbierkqboj^hbprobvlrdbqqefp)Pqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.5-.y

CLodofjj^oyKyCivqlLodofjj^oyyNFAy.03.y
eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+3&yyWyLodofjj^oyyNFAy.03.y
>QebFpi^kaboy@yT^oofloyyKyQefpfp^Ibsbi0-nrbpqclo?bopbohboPq^k`b)Plobh%5-+/)0/+1&yyWyLodofjj^oyyNFAy.4.5y
CO^q`ebqyKyAlo^p%12+/)31&yyWyLodfjj^oyyNFAy.03.y
QQebFpi^kaboy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.5y
>Qeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
@Qeb>cco^vy@yT^oofloyyKyHfiiqebpbofbplcJl_p)_^ka^db^kab^qfk_bqtbbkJl_p+>pclo?fdTfii)vlr$obdfsbkqebmofsfibdbql^qq^`hefjcfopq_b`^rpbeb$pkbrqo^i)plgrpqork_^`h^ka`e^odbqebkrpbvlroObq^if^qflkclo?fdTfii%35+3)15+4&yyWyQeb?^oobkpyyNFAy.4.6y
QQeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
ELodfjj^oyRy3615yyNFAy.03.y

CQfofpc^iDi^abpyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy.03.y

ORkabo`fqvyKyOrkqlRkabo`fqv%3.+6)35+.&yyWyQfofpc^iDi^abpyyNFAy.03.y
cRkabo`fqvy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyOyLo`)Qolii)Q^robkyyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy.03.y

CQ^oobkJfiiy@yPe^j^kyyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy.03.y

QQljblc@^_^i%M^oq.&y@yT^oil`hyyKyGlo^e>kkfplk%44)02+3&yyWyRkabo`fqvyyNFAy.5-.y
>Qljblc@^_^i%M^oq/&y@yT^oil`hyyKyGlo^e>kkfplk%44)02+3&yyWyRkabo`fqvyyNFAy.5-0y
OQfofpc^iDi^abpy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyOyLo`)Qolii)Q^robkyyKyBufqqeolrdeqebpbtbop%.2+/)0/+1&yyWyRkabo`fqvyyNFAy.03.y

OPfisbomfkbClobpqy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKyOrkqlPfisbomfkbClobpq%2-)46+0&yyWyQfofpc^iDi^abpyyNFAy160y
>GlrokbvqlEfiip_o^aCllqefiipy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKy>mlqeb`^ovObkcboobi%1/+6)1-+6&yyWyPfisbomfkbClobpqyyNFAy160y
OEfiip_o^aCllqefiipy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKyOrkaltkqeolrdePfisbomfkbqebkb^pqqlEfiip_o^aCllqefiip%4.+0)5-+2&yyWyPfisbomfkbClobpqyyNFAy161y
>QfjbQlPqofhby@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKyAb^qepq^ihboIbpe^qqebPlrqemlfkqQltbo%/-+5)14+1&yyNFAy161yyKLAB?RDy
KDbqXJliavQljbZy@yT^oil`hyyKyMf`hrmqebXJliavQljbZcoljQljblcqeb@^_^i%/4+4)4/+5&yyIy360.yyNFAy.5-0y

OQ^oobkJfiiy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKyOrkqlQ^oobkJfii%3/+0)/-+0&yyNFAy.03.y
QQfjbQlPqofhby@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKyEfdeBub`rqloA^oqe^if^%3/+0)/-+0&yyNFAy161yyKLAB?RDy
QGlrokbvqlEfiip_o^aCllqefiipy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKy>mlqeb`^ovIvalk%3.+2).6+/&yyNFAy160y
cQ^oobkJfiiy@yAorfa)Erkqbo)T^oil`h)Oldrb)J^db)Mofbpq)M^i^afk)T^oofloyyKyW^ofpb%3-+/).5+4&yyNFAy.03.y
>Obdqe^oAb^qed^qbyKyHorph%30+/)/-+4&yyNFAy.03.y
>QebE^jjboJ^vC^iiyKyQ^iilt%3.+6).6+4&yyNFAy343y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
