DugisGuideViewer:RegisterGuide("Children's Week (10+ Azeroth)", nil, "Horde", "E", function()
return [[
AAA

CLodofjj^o
>@efiaobk$pTbbhyKyLome^kJ^qolk?^qqibt^fi%4-+5)/2+2&yyNFAy.4/yyWyLodofjj^oy
RXLo`fpeLome^kTefpqibZyKyRpbqebXLo`fpeLome^kTefpqibZql`^iiqeblome^kyyRy.5264yyWyLodofjj^oy
Q@efiaobk$pTbbhyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyRy.5264yyNFAy.4/yyWyLodofjj^oy

>Altk^qqebAl`hpyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6.-yyWyLodofjj^oy
>D^qbt^vqlqebColkqfboyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6..yyWyLodofjj^oy
>Iloa^bolkQeolkbOlljyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy.5--yyWyLodofjj^oy

CO^q`ebqyKyCivqlO^q`ebqy
@Altk^qqebAl`hpyKyDlqlqebAl`hp^qO^q`ebq%30+1)05+1&^karpbXLo`fpeLome^kTefpqibZyyRy.5264yyNFAy6.-yyWyQeb?^oobkpy
QAltk^qqebAl`hpyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6.-yyWyQeb?^oobkpy

CQeb@olppol^apyKyCivqlQeb@olppol^apy
@D^qbt^vqlqebColkqfboyKyDlqlqebJlo$pe^kO^jm^oq%14)2&^karpbXLo`fpeLome^kTefpqibZyyRy.5264yyNFAy6..yyWyQeb?^oobkpy
QD^qbt^vqlqebColkqfboyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6..yyWyQeb?^oobkpy

CRkabo`fqvyKyCivqlRkabo`fqvy
@Iloa^bolkQeolkbOlljyKyDlqlqebIloa^bolkQeolkbOllj%34)03+5&fkRkabo`fqv^karpbXLo`fpeLome^kTefpqibZyyRy.5264yyNFAy.5--yyWyRkabo`fqvy
QIloa^bolkQeolkbOlljyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy.5--yyWyRkabo`fqvy

>VlrP`ob^j)FP`ob^j+++yKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6.2yyWyRkabo`fqvy
>@^fokb$pEllcmofkqyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6/2yyWyRkabo`fqvy

CLodofjj^oyKyCivqlLodofjj^oy
?XQfdrib^kaClolo$pPqo^t_boovF`b@ob^jZyKy?rvXQfdrib^kaClolo$pPqo^t_boovF`b@ob^jZcolj>iltf`flrp@wbosfh%2/)36+/&yyWyLodofjj^oyyIy4//5y
RXLo`fpeLome^kTefpqibZyKyRpbqebXLo`fpeLome^kTefpqibZql`^iiqeblome^kyyRy.5264yyWyLodofjj^oy
QVlrP`ob^j)FP`ob^j+++yKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyNFAy6.2yyWyLodofjj^oy

CQerkabo?irccyKyCivqlQerkabo?irccy
@@^fokb$pEllcmofkqyKyPmb^hql@^fokb?illaellc%3-)2.&fkQerkabo?irccyyNFAy6/2yyWyQerkabo?irccy
Q@^fokb$pEllcmofkqyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyRy.5264yyNFAy6/2yyWyQerkabo?irccy

>>T^oabklcqebEloabyKyQ^ihqlqebLo`fpeLome^kqe^qvlrprjjlktfqeXLo`fpeLome^kTefpqibZyyRy.5264yyNFAy22-/yyWyQerkabo?irccy

CLodofjj^oyKyCiv?^`hqlLodofjj^oy
Q>T^oabklcqebEloabyKyLome^kJ^qolk?^qqibt^fi%4-+5)/2+2&yyNFAy22-/yyWyLodofjj^oy

KDrfab@ljmibqb
]]
end)
