DugisGuideViewer:RegisterGuide("Children's Week (60+ Outland)", nil, "Horde", "E", function()
return [[
AAA

CPe^qqo^qe@fqv
ePe^qqo^qe@fqvyKyPbqvlroeb^oqeqlPe^qqo^qeyyWyPe^qqo^qe@fqvy
>@efiaobk$pTbbhyKyLome^kJ^qolkJbo`v%42)15&yyNFAy.-61/yyWyPe^qqo^qe@fqvy
RX?illaBicLome^kTefpqibZyKyRpbqebX?illaBicLome^kTefpqibZql`^iiqeblome^kyyRy0.55-yyWyPe^qqo^qe@fqvy
Q@efiaobk$pTbbhyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyRy0.55-yyNFAy.-61/yyWyPe^qqo^qe@fqvy

>SfpfqqebQeolkblcqebBibjbkqpyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-620yyWyPe^qqo^qe@fqvy
>E`e$rr^kaqebJrpeolljMblmibyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-612yyWyPe^qqo^qe@fqvy
>>QofmqlqebA^ohMloq^iyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-62.yyWyPe^qqo^qe@fqvy

CK^do^kayKyCivqlK^do^kay
@SfpfqqebQeolkblcqebBibjbkqpyKyDlqlQeolkblcqebBibjbkqp%3-+3)//+/&grpqKloqelcD^o^a^o^kaprjjlkqebLome^kyyRy0.55-yyNFAy.-620yyWyK^do^kay
QSfpfqqebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqPe^os^h%3-+3)//+/&yyRy0.55-yyNFAy.-620yyWyK^do^kay

CW^kd^oj^opeyKyCivqlW^kd^oj^opey
@E`e$rr^kaqebJrpeolljMblmibyKyDlqlE`e$rr%.5+4)2.+.&fkPmlobd^oo^karpbX?illaBicLome^kTefpqibZyyRy0.55-yyNFAy.-612yyWyW^kd^oj^opey
QE`e$rr^kaqebJrpeolljMblmibyKyE`e$rr%.5+4)2.+.&fkPmlobd^ooyyRy0.55-yyNFAy.-612yyWyW^kd^oj^opey

CEbiicfobMbkfkpri^yKyCivqlEbiicfobMbkfkpri^y
@>QofmqlqebA^ohMloq^iyKyPq^ka^olrka%55)2-&^qqebqlmlcqebpq^fopfk)fkqebjfaaibqfibfkcolkqlcqebA^ohMloq^i^karpbX?illaBicLome^kTefpqibZyyRy0.55-yyNFAy.-62.yyWyEbiicfobMbkfkpri^y
Q>QofmqlqebA^ohMloq^iyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-62.yyWyEbiicfobMbkfkpri^y

>Klt)TebkFDoltRm+++yKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy..642yyWyEbiicfobMbkfkpri^y

CPe^qqo^qe@fqvyKyDl_^`hqlPe^qqo^qe@fqvy
OPfisbojllk@fqvyKyQ^hbqebmloq^iqlPfisbojllky
@Klt)TebkFDoltRm+++yKyDlql%43+2)5.+3&_vqebDrfiaObdfpqo^qflkLccf`b^kaprjjlkX?illaBicLome^kTefpqibZyyRy0.55-yyNFAy..642yyWyPfisbojllk@fqvy
QKlt)TebkFDoltRm+++yKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy..642yyWyPfisbojllk@fqvy

>QfjbqlSfpfqqeb@^sbokpyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-630yyWyPfisbojllk@fqvy

CD^adbqw^kyKyCivqlD^adbqw^kfkQ^k^ofpy
KQ^ihqlPqbt^oalcQfjbyKyQ^ihqlPqbt^oalcQfjb%33)16)4&^kaq^hbqebcifdeqaltkql@^sboklcQfjbyyWyQ^k^ofpy
?XQlvAo^dlkZyKy?rvXQlvAo^dlkZcolj>irojf%30+3)24+3&yyWyQ^k^ofpyyIy0.62.y
@QfjbqlSfpfqqeb@^sbokpyKyDlqlW^i^alojr%3-+1)24+1&^kaprjjlkX?illaBicLome^kTefpqibZyyRy0.55-yyNFAy.-630yyWyQ^k^ofpy
QQfjbqlSfpfqqeb@^sbokpyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-630yyWyQ^k^ofpy

>?^`hqlqebLome^k^dbyKyQ^ihqlqeb?illaBicLome^kqe^qvlrprjjlktfqeX?illaBicLome^kTefpqibZyyNFAy.-634yyWyQ^k^ofpy
EPe^qqo^qe@fqvyRy3615y
Q?^`hqlqebLome^k^dbyKyLome^kJ^qolkJbo`v%42)15&yyNFAy.-634yyWyPe^qqo^qe@fqvy
KDrfab@ljmibqb
]]
end)
