DugisGuideViewer:RegisterGuide("Pilgrim's Bounty Cooking 1-300", nil, "Horde", "E", function() 
return [[
AAA

CRkabo`fqvyKyDlqlRkabo`fqvy

KIb^ok%Pmf`b?ob^a&yKySfpfqOl_boq^@^oqbo%30+1)6&qeb`llhfkdqo^fkbo^kaib^okqebob`fmb%Pmf`b?ob^a&qebkqf`hqefppqbmyyWyRkabo`fqvy

K?rvX?lrkqfcri@llh_llhZyKyOlpbPq^kafpe%31+2).-+5&yyIy135.-yyWyRkabo`fqvy
R?lrkqfcri@llh_llhyKyLmbkqeb_llhyyRy135.-y

>Pmf`b?ob^aPqrccfkdyKyJfibpPq^kafpe%31+2).-+5&yyNFAy.1-04yyWyRkabo`fqvy
K@llh%Pmf`b?ob^aPqrccfkd&Rkqfi++yKyHbbm`llhfkd%Pmf`b?ob^aPqrccfkd&rkqfivlrob^`eibsbi.--`llhfkdphfiiqlib^okqebkbuqob`fmb%MrjmhfkMfb&qebkqf`hqefppqbmy
K?rv2*5-XOfmbQfofpc^iMrjmhfkZyKy?rv2u%lo^olrka5-fcvlro`llhfkdphfii.--&XOfmbQfofpc^iMrjmhfkZcoljcoljqebMfidofj$p?lrkqvsbkalolrqpfablcRkabo`fqv_rv^_lrq/--fcvlrfkqbkalkalfkdqebA^fifbpi^qboy
@Pmf`b?ob^aPqrccfkdyKy@llh^ka_ofkd2XPmf`b?ob^aPqrccfkdZqlTfiif^jJriifkpfkRkabo`fqv$p`lroqv^oa%qebOrfkplcIloa^bolk&+Alk$qclodbqqlj^hbprobvlre^sbib^okbaqebPmf`b?ob^aklk*pb^plk^iob`fmb+yyNFAy.1-04y
QPmf`b?ob^aPqrccfkdyKyTfiif^jJriifkp%32+/).1+.&yyNFAy.1-04yyWyRkabo`fqvy


>MrjmhfkMfbyKyTfiif^jJriifkp%32+/).1+.&yyNFAy.1-1-yyWyRkabo`fqvy
@MrjmhfkMfbyKy@llh^ka_ofkd2mfb`bplc%MrjmhfkMfb&qlCo^k`fpB^qlklrqpfablcLodofjj^o+Tefibvlr^obpqfiifkQfofpc^iDi^abpyyNFAy.1-1-y
K?rv2*5-XQ^kdvPlrqecrov@o^k_boofbpZyKyTefibvlr^obpqfiifkArolq^o)_bprobqlmro`e^pb2u%lo^olrka5-fcvlro`llhfkdphfii.3-&XQ^kdvPlrqecrov@o^k_boofbpZcoljqebMfidofj$p?lrkqvsbkalolrqpfablcLodofjj^o+_rv^_lrq/--fcvlrfkqbkalkalfkdqebA^fifbpi^qboy
K@llh%MrjmhfkMfb&Rkqfi++yKyHbbm`llhfkd%Pmf`b?ob^aPqrccfkd&rkqfivlrob^`eibsbi.3-`llhfkdphfiiqlib^okqebkbuqob`fmb%@o^k_boov@erqkbv&qebkqf`hqefppqbmy
CArolq^oyKyDlqlArolq^oy
QMrjmhfkMfbyKyCo^k`fpB^qlk%13+3).0+5&yyNFAy.1-1-yyWyArolq^oy

>@o^k_boov@erqkbvyKyCo^k`fpB^qlk%13+3).0+5&yyNFAy.1-1.yyWyArolq^oy
@@o^k_boov@erqkbvyKy@llh^ka_ofkd2pbosfkdplcX@o^k_boov@erqkbvZqlAlhfkC^omi^fklrqpfablcQerkabo?ircc+yyNFAy.1-1.y
K@llh%@o^k_boov@erqkbv&Rkqfi++yKyHbbm`llhfkd%@o^k_boov@erqkbv&rkqfivlrob^`eibsbi//-`llhfkdphfiiqlib^okqebkbuqob`fmb%@^kafbaPtbbqMlq^qlbp&qebkqf`hqefppqbmy
K?rv2*5-XJridlobPtbbqMlq^qlZyKyTefibvlr^obpqfiifkJridlob)_bprobqlmro`e^pb2u%lo^olrka5-fcvlro`llhfkdphfii//-&XJridlobPtbbqMlq^qlZcoljqebMfidofj$p?lrkqvsbkalolrqpfablcQerkabo?ircc)_rv^_lrq/--fcvlrfkqbkalkalfkdqebA^fifbpi^qboy
CQerkabo?irccyKyDlqlQerkabo?irccy
Q@o^k_boov@erqkbvyKyAlhfkC^omi^fk%0-+6)31+3&yyNFAy.1-1.yyWyQerkabo?irccy

>@^kafbaPtbbqMlq^qlbpyKyAlhfkC^omi^fk%0-+6)31+3&yyNFAy33-01yyWyQerkabo?irccy
@@^kafbaPtbbqMlq^qlbpyKy@llh^ka_ofkd2@^kafbaPtbbqMlq^qlqlCo^k`fpB^qlklrqpfablcLodofjj^o+Tefibvlr^obpqfiifkJridlobyyNFAy33-01y
K@llh%@^kafbaPtbbqMlq^qlbp&Rkqfi++yKyHbbm`llhfkd%@^kafbaPtbbqMlq^qlbp&rkqfivlrob^`eibsbi/5-`llhfkdphfiiqlib^okqebkbuqob`fmb%@^kafbaPtbbqMlq^qlbp&qebkqf`hqefppqbmy
Q@^kafbaPtbbqMlq^qlbpyKCo^k`fpB^qlk%13+3).0+5&yyNFAy33-01yyWyArolq^oy

>RkaboprmmifbafkqebRkabo`fqvyKyCo^k`fpB^qlk%13+3).0+5&yyWyArolq^oyyNFAy.1-11y
@RkaboprmmifbafkqebRkabo`fqvyKy@llh^ka_ofkd2uXPmf`b?ob^aPqrccfkdZ^ka2uX@o^k_boov@erqkbvZqlJfibpPq^kafpefkRkabo`fqv$p`lroqv^oa%qebOrfkplcIloa^bolk&+yyNFAy.1-11y
QRkaboprmmifbafkqebRkabo`fqvyKyJfibpPq^kafpe%31+2).-+5&yyWyRkabo`fqvyyNFAy.1-11y

>Pilt*ol^pqbaQrohbvyKyJfibpPq^kafpe%31+2).-+5&yyNFAy.1-14yyWyRkabo`fqvy
KCfka2uXTfiaQrohbvZyKyTefibvlr^obpqfiifkQfofpc^iDi^abp)_bprobqleb^alrq^kaerkqaltkpljbTfiaQrohbvcloqeb2XTfiaQrohbvZqebkbuqnrbpqtfiiobnrfob)dbq^_lrq/2jlobXTfiaQrohbvZfcvlrtfpeqlibsbirmql0--y
@Pilt*ol^pqbaQrohbvyKy@llh^ka_ofkd2XPilt*Ol^pqbaQrohbvZqlCo^k`fpB^qlklrqpfablcLodofjj^o+yyNFAy.1-14y
QPilt*ol^pqbaQrohbvyKyCo^k`fpB^qlk%13+3).0+5&yyNFAy.1-14yyWyArolq^oy

K@llhfkdDrfab@ljmibqb

]]
end)
