DugisGuideViewer:RegisterGuide("Hallow's End Azeroth + Achievement Quest", nil, "Horde", "E", function() 
return [[
AAA

K?bdfk^qPfisbojllkyKyQ^hbqebmloq^iqlPfisbojllkcoljA^i^o^ky

QPfisbojllk)QebOlv^iBu`e^kdbyKyQebOlv^iBu`e^kdb%46+3)24+5&yyNFAy./036yyWyPfisbojllk@fqvy
QPfisbojllk)Qeb?^w^^oyKyQeb?^w^^o%34+4)40+/&yyNFAy./04-yyWyPfisbojllk@fqvy
QBsboplkdTllap)C^i`lktfkdPnr^obyKyC^i`lktfkdPn%15+.)14+5&yyNFAy./031yyWyBsboplkdTllapy
QBsboplkdTllap)C^fo_obbwbSfii^dbyKyC^fo_obbwbSfii^db%10+4)4.+.&yyNFAy./032yyWyBsboplkdTllapy
QDelpqi^kap)Qo^knrfiifbkyKyQo^knrfiifbk%15+3)0/&yyNFAy./040yyWyDelpqi^kapy

CIfdeq$pElmb@e^mbiyKyCivqlB^pqbokMi^drbi^kap%12+1)0-+2&yyWyDelpqi^kapy
QB^pqbokMi^drbi^kap)Ifdeq$pElmb@e^mbiyKyIfdeq$pElmb@e^mbi%42+6)2/+0&yyNFAy./1-/yyWyB^pqbokMi^drbi^kapy

CRkabo`fqvyKyCivqlqebRkabo`fqv%41+2)2.+/&yyWyB^pqbokMi^drbi^kapy
QRkabo`fqv)QebQo^abNr^oqboyKyQebQo^abNr^oqbo%35)04+0&yyNFAy./035yyWyRkabo`fqvy
QQfofpc^iDi^abp)?ofiiyKyQfofpc^iDi^abp)?ofii%3.+5)2/+/&yyNFAy./030yyWyQfofpc^iDi^abpy
>OlqqbkBddpyKyA^oh`^iiboV^kh^%22+2)36+6&yyNFAy51-6yyWyQfofpc^iDi^abpy
>PqfkhfkdRmPlrqepelobyKyA^oh`^iiboV^kh^%22+2)36+6&yyNFAy.324yyWyQfofpc^iDi^abpy

QPfisbomfkbClobpq)QebPbmri`eboyKyQebPbmri`ebo%10+/)1.+1&yyNFAy./04.yyWyPfisbomfkbClobpqy
CQ^oobkJfiiyKyCivqlEfiip_o^aCllqefiip%12+3)1/+3&yyWyPfisbomfkbClobpqy
QEfiip_o^aCllqefiip)Q^oobkJfiiyKyQ^oobkJfii%3/+5).6&yyNFAy./043yyWyEfiip_o^aCllqefiipy
@PqfkhfkdRmPlrqepelobyKyDlql%16)26&^kaqeoltfqfkqebjfaaiblcPlrqepelobyyNFAy.324yyWyEfiip_o^aCllqefiipyyRy/-054y
QOlqqbkBddpyKyLk`bvlrbkqboqebfkk%2.+/)25+6&)vlr$iipbb^mvo^jfalchbdpkb^oqebpq^fopdlfkdqlqebpb`lkacillo+Pfjmiv`if`hfkdlkqebhbdfpbklrdeql`ljmibqbqebnrbpq8fqalbpk$qcrk`qflkifhb^`ebpqtebobvlre^sbqlt^fq2pb`lkapyyNFAy51-6yyWyEfiip_o^aCllqefiipy
>OrfkbaHbdpyKyHbd%2.+0)25+6&yyNFAy51-6yyWyEfiip_o^aCllqefiipy

CE^jjboc^iiyKyCivql>o^qefEfdei^kap%3-+.).5+3&yyWyEfiip_o^aCllqefiipy
Q>o^qefEfdei^kap)E^jjboc^iiyKyE^jjboc^ii%40+6)0/+3&yyNFAy./05-yyWy>o^qefEfdei^kapy

CObs^kqrphSfii^dbyKyCivqlqebEfkqboi^kap%40)0/+4&yyWy>o^qefEfdei^kapy
QEfkqboi^kap)Obs^kqrphSfii^dbyKyObs^kqrphSfii^db%45+/)5.+2&yyWyQebEfkqboi^kapy

CH^od^qeyKyCivqlH^od^qe%5.+4)5.+5&yyWyQebEfkqboi^kapy
Q?^ai^kap)H^od^qeyKyH^od^qe%/+6)03&yyNFAy./052yyWy?^ai^kapy

CPqlk^oayKyCivqlPt^jmlcPlooltp%1)11+5&yyWy?^ai^kapy
QPt^jmlcPlooltp)Pqlk^oayKyPqlk^oa%12+.)23+2&yyNFAy./051yyWyPt^jmlcPlooltpy

CDolj$dli?^pb@^jmyKyCivqlPqo^kdibqelokS^ib%13+.)21+5&yyWyPt^jmlcPlooltpy
QPqo^kdibqelokS^ib)Dolj$dli?^pb@^jmyKyDolj$dli?^pb@^jm%02+.)/6+4&yyNFAy./05/yyWyPqo^kdibqelokS^iby

C?llqv?^vyKyCivql?llqv?^v%0/+2)/6+1&yyWyPqo^kdibqelokS^iby
QPqo^kdibqelokS^ib)?llqv?^vyKy?llqv?^v%/4+.)44+0&yyNFAy./064yyWyPqo^kdibqelokS^iby

_O^q`ebqyKyQ^hbqeb_l^qqlO^q`ebq%/3)40+/&yyWyPqo^kdibqelokS^iby
Q?^oobkp)O^q`ebqyKyQeb?^oobkp*O^q`ebq%3/)06&yyNFAy./063yyWyQeb?^oobkpy

CQeb@olppol^apyKyCivql@olppol^ap%30+.)04+/&yyWyQeb?^oobkpy
Q?^oobkp)Qeb@olppol^apyKyQeb?^oobkp*Qeb@olppol^ap%2/)0-&yyNFAy./041yyWyQeb?^oobkpy

C@^jmQ^ro^glyKyCivql@^jmQ^ro^gl%2.+2)0-+0&yyWyQeb?^oobkpy
Q?^oobkp)@^jmQ^ro^glyKyQeb?^oobkp*@^jmQ^ro^gl%41)3.&yyNFAy./042yyWyQeb?^oobkpy

C?o^`hbkt^iiSfii^dbyKyCivql?o^`hbkt^iiSfii^db%11+2)26+/&yyWyQeb?^oobkpy
QArpqt^iiltJ^ope)?o^`hbkt^iiSfii^dbyKy?o^`hbkt^iiSd%03)0/&yyNFAy./050yyWyArpqt^iiltJ^opey

CJrapmol`hbqyKyCivqlJrapmol`hbq%02+3)0.+6&yyWyArpqt^iiltJ^opey
QArpqt^iiltJ^ope)Jrapmol`hbqyKyJrapmol`hbq%1.)41&yyNFAy./065yyWyArpqt^iiltJ^opey

CCobbtfkaMlpqyKyCivqlCobbtfkaMlpq%1/+5)4/+1&yyWyArpqt^iiltJ^opey
QQelrp^kaKbbaibp)CobbtfkaMlpqyKyQelrp^kaKbbaibp*CobbtfkaMlpq%13)2.&yyNFAy./046yyWyQelrp^kaKbbaibpy

CD^adbqw^kyKyCivqlD^adbqw^k%12+.)16+.&yyWyQelrp^kaKbbaibpy
QQ^k^ofp)D^adbqw^kyKyQ^k^ofp*D^adbqw^k%2/)/5&yyNFAy./066yyWyQ^k^ofpy

C@bk^oflkEliayKyCivql@bk^oflkElia%2.+3)/2+1&yyWyQ^k^ofpy
QPfifqerp)@bk^oflkEliayKyPfifqerp*@bk^oflkElia%2.)06&yyNFAy./1-.yyWyPfifqerpy

C@^jmJlg^`ebyKyCivql@^jmJlg^`eb%15+4)03+4&yyWyPfifqerpy
QCbo^i^p)@^jmJlg^`ebyKyCbo^i^p*@^jmJlg^`eb%42)12&yyNFAy./053yyWyCbo^i^py

CQerkabo?irccyKyCivqlQerkabo?ircc%42+2)11+1&yyWyCbo^i^py
QQerkabo?ircc)IltboOfpbyKyQerkabo?ircc*IltboOfpb%12)31&yyNFAy./034yyWyQerkabo?irccy
eQerkabo?irccyKyPbqvlroeb^oqeqlQerkabo?irccfkk%12)31&yyWyQerkabo?irccy

QJridlob)?illaellcSfii^dbyKyJridlob*?illaellcSfii^db%14)3.&yyNFAy./03/yyWyJridloby
EQerkabo?irccyRy3615yyKyEb^oqeqlQerkabo_irccy

CPe^altmobvSfii^dbyKyCivqlPe^altmobvSfii^db%14)16+5yyWyQerkabo?irccy
QAbpli^`b)Pe^altmobvSfii^dbyKyAbpli^`b*Pe^altmobvSfii^db%/1)35&yyNFAy./05.yyWyAbpli^`by

CPrkOl`hObqob^qyKyCivqlPrkOl`hObqob^q%/.+3)41+/&yyWyAbpli^`by
QPqlkbq^ilkJlrkq^fkp)PrkOl`hObqob^qyKyPqlkbq^ilkJkqp*PrkOl`hOoq%14)3/&yyNFAy./045yyWyPqlkbq^ilkJlrkq^fkpy

CPmifkqboqobbMlpqyKyCivqlPmifkqboqobbMlpq%12+.)26+6&yyWyPqlkbq^ilkJlrkq^fkpy
Q>pebks^ib)PmifkqboqobbMlpqyKy>pebks^ib*PmifkqboqobbMlpq%41)3-&yyNFAy./044yyWy>pebks^iby

CBsboillhyKyCivqlBsboillh%40+/)3.+3&yyWy>pebks^iby
QTfkqbopmofkd)BsboillhyKyTfkqbopmofkd*Bsboillh%3.)06&yyNFAy./1--yyWyTfkqbopmofkdy

CLodofjj^oyKyCivqlLodofjj^o%3-+2)03+3&yyWyTfkqbopmofkdy
QLodofjj^o)S^iibvlcPqobkdqeyKyLodofjj^o*S^iibvlcPqobkdqe%21)36&yyNFAy./033yyWyLodofjj^oy

QArolq^o)O^wloEfiiyKyArolq^o*O^wloEfii%2.)1.&yyNFAy./03.yyWyArolq^oy

CQfofpc^iDi^abpyKyQ^hbqebWbmmbifkqlQfofpc^iDi^abp%2-+6).0+6&yyWyArolq^oy
QOrfkbaHbdpyKyA^oh`^iiboV^kh^%22+2)36+6&yyNFAy51-6yyWyQfofpc^iDi^abpy
QPqfkhfkdRmPlrqepelobyKyA^oh`^iiboV^kh^%22+2)36+6&yyNFAy.324yyWyQfofpc^iDi^abpy

K>wbolqeDrfab@ljmibqb

]]
end)
