DugisGuideViewer:RegisterGuide("Winter Veil: Quest Chain", nil, "Horde", "E", function() 
return [[
AAA

CLodofjj^oyKyDlqlLodofjj^oy
>Dob^q*c^qeboTfkqbofpEbobyKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy363.yyWyLodofjj^oy
>PqlibkTfkqboSbfiQob^qpyKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy3630yyWyLodofjj^oy
>JbqwbkqebObfkabboyKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy5413yyWyLodofjj^oy
RXPjlhvtllaP^q`ebiZyKyLmbkXPjlhvtllaP^q`ebiZyyRy/.0.2y
>QebOb^plkcloqebPb^plkyKyCrojfka%2.)33&yNFAy3631yyWyLodofjj^oy

QDob^q*c^qeboTfkqbofpEbobyKyDob^qc^qeboTfkqbo%2/+2)36&yyNFAy363.yyWyLodofjj^oy
>Qob^qpcloDob^q*c^qeboTfkqboyKyDob^qc^qeboTfkqbo%2/+2)36&yyNFAy363/yyWyLodofjj^oy

QQebOb^plkcloqebPb^plkyKyP^dlokb@obpqpqofabo%05+3)03+/&yyNFAy3631yyWyLodofjj^oy
>QebCb^pqlcTfkqboSbfiyKyP^dlokb@obpqpqofabo%05+3)03+/&yyNFAy4-3.yyWyLodofjj^oy

CQ^oobkJfiiyKyCivqlQ^oobkJfiiy
QPqlibkTfkqboSbfiQob^qpyKyPqo^kdbPkltj^k%02+/)4/+.&yyNFAy3630yyWy>iqbo^`Jlrkq^fkpy
KDbqPljbPklt_^iipyKyDbqpljbPklt_^iiptefibvlr$obebob)vlrpelriacfkapkltmfibp^olrkaqeb^ob^)p^sb^qib^pq.cloP`olldb^`efbsbjbkqyyIy.4/-/y
>Vlr$ob^Jb^kLkb+++yKyPqo^kdbPkltj^k%02+/)4/+.&yyNFAy3650yyWy>iqbo^`Jlrkq^fkpy
@Vlr$ob^Jb^kLkb+++yKyHfiiQeb>_ljfk^_ibDobbk`e^ka`liib`qqebXPqlibkQob^qpZ%0-)21&)%06+4)30+3&)%00)36&)%0-)31&)%1-)40&yyNFAy3650yyWy>iqbo^`Jlrkq^fkpy
QVlr$ob^Jb^kLkb+++yKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy3650yyWyLodofjj^oy
>>PjlhvtllaM^pqrobp$Qe^khVlryKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy3651yyWyLodofjj^oy

CH^od^qeyKyCivqlH^od^qey
KHfiiPqlkbDlibjplkvlrot^v+++yKyHfii^kvPqlkbDlibjpvlrpbbfkPb^ofkdDlodb^ka`liib`q2uXAbbmol`hP^iqZ%34+6)00+4&yyIy5.2-yyWyPb^ofkdDlodby
@JbqwbkqebObfkabboyKyCfkaJbqwbkqebObfkabbo%34+6)00+4&^kaq^ihqlefjyyNFAy5413yyWyPb^ofkdDlodby
KDbqXAbbmol`hP^iqZyKyHfii^kvPqlkbDlibjpvlrpbbfkPb^ofkdDlodb^ka`liib`qXAbbmol`hP^iqZyyIy5.2-y

CQerkabo?irccyKyDlqlQerkabo?irccy
QQebCb^pqlcTfkqboSbfiyKy@^fokb?illaellc%3-)2.+4&yyNFAy4-3.yyWyQerkabo?irccy
RQeoltXPklt_^iiZ^q@^fokb++yKyQeoltXPklt_^iiZ^q@^fokb?illaellc%3-)2.+4&clo^`efbsbjbkqyyRy.4/-/y

CLodofjj^oyKyDlqlLodofjj^oy

Q>PjlhvtllaM^pqrobp$Qe^khVlryKyDob^qc^qeboTfkqbo%2/+2)36&yyNFAy3651yyWyLodofjj^oy
QJbqwbkqebObfkabboyKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy5413yyWyLodofjj^oy
KQebEbollcqebA^vyKyQefpnrbpqobnrfobpvlrqle^sbibsbi0--`llhfkdphfiiqlmf`hrmy
>QebEbollcqebA^vyKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy5466yyWyLodofjj^oy
QQebEbollcqebA^vyKyH^vj^oa@lmmbomfk`e%2/+3)33+0&yyNFAy5466yyWyLodofjj^oy

?.uXF`b@liaJfihZyKy?rv.uXF`b@liaJfihZcolj?^ohbbmJlo^d%21+3)35&yyIy..46yyWyLodofjj^oy
KDfkdbo_ob^a@llhfbyKyBfqebo_rv2uXDfkdbo_ob^a@llhfbZcoljqeb>Elo`llhfqvlropbicvlrlkivkbbaibsbi.`llhfkdphfii)qebob`fmb^kaXElifa^vpmf`bpZfpplia_vMbkkbv@lmmbomfk`e%20+2)33+.&^kaqebbddp`^k_bclrka_vhfiifkdqebAo^dlke^thpfkBsboplkdTllapyyIy.4.642yyWyLodofjj^oy
QQob^qpcloDob^q*c^qeboTfkqboyKyDob^qc^qeboTfkqbo%2/+2)36&yyNFAy363/yyWyLodofjj^oy

KTfkqboSbfiNrbpqp@ljmibqb

]]
end)
