DugisGuideViewer:RegisterGuide("Redridge Mountains (18-20)", "Darkshore (20-22)", "Alliance", "L", function()
return [[
AAA

CPqlojtfka@fqvyKyDovqeQeroabk%22+4)15&yyWyFolkclodbyyNFAy/11y
QPqlojmfhb$pLoaboyKyCrobkIlkd_b^oa%31+4)04+2&yyWyPqlojtfka@fqvyyNFAy.005y

OBitvkkClobpqyKyOrkqlBitvkkClobpq%42)61&yyNFAy/11y
OObaofadbJlrkq^fkpyKy%63+1)4/+1&yyNFAy/11y
>Bk`ol^`efkdDkliipyKyDr^oaM^ohbo%.3)4-&yyNFAy/11y
QBk`ol^`efkdDkliipyKyAbmrqvCbialk%0-)26&yyNFAy/11y
>>ppbppfkdqebQeob^qyKyAbmrqvCbialk%0-)26&yyNFAy/13y
>QebIlpqQllipyKyClobj^kLpilt%0/+/)15+3&yyNFAy./2y
>Efi^ov$pKb`hi^`byKyPe^tk%/6+0)20+2&yyNFAy041.y
>PbiifkdCfpeyKyAl`hj^pqbo?^obk%/4+5)14+0&yyNFAy./4y
>>CobbIrk`eyKyA^o`v%/4)12&yyNFAy./6y
>ObaofadbDlri^peyKy@ebc?ob^kk^%//+4)11&yyNFAy6/y

HDob^qDlobqrphpyKyTbpqlcqebi^hb)kbbaXDob^qDlobqrphPklrqZu2cloObaofadbDlri^pe%.3+2)16+3&yyIy//632yyNFAy6/y
KHbbm^iiJroil`CfkpvlrcfkayNFAy.2-y
@Efi^ov$pKb`hi^`byKy>kbu^`qil`^qflklcqebjramfib`^kklq_bp^fa^pfq`lkqfkrbpql`e^kdb_rqfq`^k_bclrka^kvtebob_bqtbbk%//)20&^ka%03)21&yyNFAy041.y
@QebIlpqQllipyKyVlr`^kcfkaXLpilt$pQlli_luZfkqebPrkhbk@ebpq^q%1/)22&yyNFAy./2y
@PbiifkdCfpeyKyDbq.-XPmlqqbaPrkcfpeZclrka^olrka%/6)2.&+CloqefpnrbpqvlrjrpqbfqeboCfpeqebpblrqlcqebt^qbolohfiiqebJroil`pfkqebt^qbo+Cfpefkdphfiijrpq_b^olrka4-(yyNFAy./4y
HHfiiJroil`pclo5uCfkpyKyKbbaXJroil`CfkZu5cloi^qboyyIy.1355yyNFAy.2-y

QQebIlpqQllipyKyClobj^kLpilt%0/+/)15+3&yyNFAy./2y
>QebBsbopqfii?ofadbyKyClobj^kLpilt%0/+/)15+3&yyNFAy56y
QEfi^ov$pKb`hi^`byKyEfi^ov%/6+0)20+2&yyNFAy041.y
QPbiifkdCfpeyKyAl`hj^pqbo?^obk%/4+5)14+0&yyNFAy./4y
Q>CobbIrk`eyKyDr^oaM^ohbo%.3)4-&yyNFAy./6y
>SfpfqqebEbo_^ifpqyKyDr^oaM^ohbo%.3)4-&yyNFAy.0-y

HHfiiPmfabopclo2uPmfaboJb^qyKy>olrka%.4)4/&^ka%0-)42&+KbbaX@ofpmPmfaboJb^qZu2cloObaofadbDlri^peyyIy.-5.2yyNFAy6/y
@>ppbppfkdqebQeob^qyKyHfii.-ObaofadbJlkdobip^ka3ObaofadbMl^`eboptef`e`^k_bclrkaqlqebplrqe^olrka%0-)5-&yyNFAy/13y
@ObaofadbDlri^peyKy@liib`q2XDob^qDlobqrphPklrqpZaolmmba_vDob^qDlobqrph^olrka%0-)42&^ka2mfb`bplcXQlrde@lkaloJb^qZaolmmba_vAfob@lkalop^olrka%02)4-&%22)44&yyIy.-5-2yyNFAy6/y

Q>ppbppfkdqebQeob^qyKyAbmrqvCbialk%0-)26&yyNFAy/13y
QSfpfqqebEbo_^ifpqyKyJ^oqfbG^fkolpb%//)13+0&yyNFAy.0-y
>AbifsbofkdA^cclafipyKyJ^oqfbG^fkolpb%//)13+0&yyNFAy.0.y
QObaofadbDlri^peyKy@ebc?ob^kk^%//+4)11&yyNFAy6/y
QAbifsbofkdA^cclafipyKyA^o`v%/4)12&yyNFAy.0.y
@QebBsbopqfii?ofadbyKyQebObaofadbDkliip`^k_bclrkaqlqebKloqe^olrka%06)03&^ka`lkqfkrbtbpqt^oacoljqe^q^ob^yyNFAy56y
QQebBsbopqfii?ofadbyKyClobj^kLpilt%0/+/)15+3&yyNFAy56y

>Jroil`Ml^`ebopyKyAl`hj^pqbo?^obk%/4+5)14+0&yyNFAy.2-y
@Jroil`Ml^`ebopyKyDbq5XJroil`CfkpZaolmmba_vJroil`P`lrq^olrka%1-)15&+Vlr`^kcfkaJroil`pqeolrdelrqqebi^hbfkObaofadbJlrkq^fkpyyNFAy.2-y
QJroil`Ml^`ebopyKyAl`hj^pqbo?^obk%/4+5)14+0&yyNFAy.2-y

>JbppbkdboqlPqlojtfka%M^oq.&yKyJ^dfpqo^qbPliljlk%0-)11&yyNFAy./-y
CPqlojtfka@fqvyKy>ofbk^Pqlojcb^qebo%0-+4)26+0&yyNFAy./.y
QJbppbkdboqlPqlojtfka%M^oq.&yKyDbkbo^iJ^o`rpGlk^qe^k%36+2)50+/&yyWyPqlojtfka@fqvyyNFAy./-y
>JbppbkdboqlPqlojtfka%M^oq/&yKyDbkbo^iJ^o`rpGlk^qe^k%36+2)50+/&yyWyPqlojtfka@fqvyyNFAy./.y

>J^qef^p^kaqebAbcf^py@yOldrbyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy/03-y

KQ^ihqlArqelof^kO^iiyKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyWyPqlojtfka@fqvyyNFAy.316y
>QebQljblcS^ilo%M^oq.&yKyQebfqbjXQljblcS^iloZpq^oqpqefpnrbpqyy@yM^i^afkyyNFAy.316y
QQebQljblcS^ilo%M^oq.&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyWyPqlojtfka@fqvyyNFAy.316y
>QebQljblcS^ilo%M^oq/&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyWyPqlojtfka@fqvyyNFAy.32-y

CPbkqfkbiEfiiyKyArkd^oIlkdaofkh%4.)4/+3&yy@yM^i^afk)OldrbyyWyPqlojtfka@fqvy

QJ^qef^p^kaqebAbcf^py@yOldrbyyKy>dbkqHb^okbk%35+1)4-&yyWyTbpqc^iiyyNFAy/03-y
>Hi^sbk$pQltboy@yOldrbyyKy>dbkqHb^okbk%35+1)4-&yyWyTbpqc^iiyyNFAy/026y
@Hi^sbk$pQltboy@yOldrbyyKyDlqlqebqltbo^q%36+2)41&^kap^m^dr^oaqebkrpbMf`hMl`hbqqldbqqebXAbcf^pQltboHbvZ)qebkvlr`^kdbqqebXHi^sbkJloqt^hb$pGlrok^iZcoljqeb`ebpq^q%4-+2)41&yyWyTbpqc^iiyyNFAy/026y

QQebQljblcS^ilo%M^oq/&yKyA^mekbPqfitbii%1/)55&yy@yM^i^afkyyWyTbpqc^iiyyNFAy.32-y
>QebQljblcS^ilo%M^oq0&yKyA^mekbPqfitbii%1/)55&yy@yM^i^afkyyWyTbpqc^iiyyNFAy.32.y
@QebQljblcS^ilo%M^oq0&yKyAbcbkaA^mekbPqfitbii%1/)55&coljqebAbcf^p^qq^`h+Kbfqebolcvlropmfofqpjrpq_bobib^pbacoljqebfojloq^i`lfipfcvlrtfpeqlpr``bbayy@yM^i^afkyyWyTbpqc^iiyyNFAy.32.y
QQebQljblcS^ilo%M^oq0&yKyA^mekbPqfitbii%1/)55&yy@yM^i^afkyyWyTbpqc^iiyyNFAy.32.y
>QebQljblcS^ilo%M^oq1&yKyA^mekbPqfitbii%1/)55&yy@yM^i^afkyyWyTbpqc^iiyyNFAy.32/y

CPqlojtfka@fqvyKyQelo%23+2)2/+3&yy@yM^i^afk)OldrbyyWyTbpqc^iiy

QHi^sbk$pQltboy@yOldrbyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy/026y
>QebQlr`elcW^kwfiy@yOldrbyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy/3-4y
QQebQlr`elcW^kwfiy@yOldrbyyKyAl`Jfufimfufi%5-+.)4-+.&yyWyPqlojtfka@fqvyyNFAy/3-4y

QQebQljblcS^ilo%M^oq1&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyWyPqlojtfka@fqvyyNFAy.32/y

>AbslrobolcPlripyKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.4.3y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
