DugisGuideViewer:RegisterGuide("Wetlands (30-31)", "Hillsbrad Foothills (31-33)", "Alliance", "L", function()
return [[
AAA

C>r_boafkbyKyPro^i^fpC^otfka%51+4)10+5&yyWy>pebks^ibyyNFAy14/y

_>wrobjvpqFpiby@yPe^j^kyyKyQ^hbqebjfaaib_l^qql>wrobjvpqFpibyyNFAy622.y
OQebBula^oy@yPe^j^kyyKyDlqlQebBula^o%00+2)10+0&yyWy>wrobjvpqFpibyyNFAy622.y
>@^iilc>fo%M^oq.&y@yPe^j^kyyKyPri^^%00+/)/0+0&yyNFAy622.yyWyQebBula^oy
Q@^iilc>fo%M^oq.&y@yPe^j^kyyKyC^opbboKl_rkal%0-)0-&yyNFAy622.yyWyQebBula^oy
>@^iilc>fo%M^oq/&y@yPe^j^kyyKyC^opbboKl_rkal%0-)0-&yyNFAy622/yyWyQebBula^oy
Q@^iilc>fo%M^oq/&y@yPe^j^kyyKyBufqkloqeqebefii%/3)/3&^kacfkaSbi^^a^%/1+5)02+6&yyNFAy622/yyWy>wrobjvpqFpiby
>@^iilc>fo%M^oq0&y@yPe^j^kyyKySbi^^a^%/1+5)02+6&yyNFAy6220yyWy>wrobjvpqFpiby
Q@^iilc>fo%M^oq0&y@yPe^j^kyyKyPrproorp%//+05)0/+2&yyNFAy6220yyWy>wrobjvpqFpiby
>@^iilc>fo%M^oq1&y@yPe^j^kyyKyPrproorp%//+05)0/+2&yyNFAy6221yyWy>wrobjvpqFpiby
Q@^iilc>fo%M^oq1&y@yPe^j^kyyKyC^opbboKl_rkal%0-)0-&yyNFAy6221yyWyQebBula^oy
_A^ohpeloby@yPe^j^kyyKyQ^hbqeb?l^qql>r_boafkb%/.+3)21&yyWy>wrobjvpqFpibyyNFAy14/y

_Pqlojtfka@fqvyKyQ^hbqeb?l^qqlPqlojtfka@fqvyyWyA^ohpelobyyNFAy14/y

>PbbhfkdPqo^e^ayKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyNFAy.465yyWyPqlojtfka@fqvy
>QebFpi^kaboy@yT^oofloyyKyTrPebk%5-+3)26+4&yyNFAy.4.5yyWyPqlojtfka@fqvy

CJbkbqefiE^o_loy@yT^oil`h)T^oofloyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy14/y

eAbbmt^qboQ^sboky@yT^oil`h)T^oofloyyKyFkJbkbqefiE^o_lo%.-+4)3-+6&yyNFAy14/y
_Qebo^jlobFpiby@yT^oil`h)T^oofloyyKyQ^hbqeb_l^qqlQebo^jlobFpibyyNFAy14/y

QQebFpi^kaboy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.5y
>Qeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
@Qeb>cco^vy@yT^oofloyyKyHfiiqebpbofbplcJl_p)_^ka^db^kab^qfk_bqtbbkJl_p)>pclo?fdTfii)vlr$obdfsbkqebmofsfibdbql^qq^`hefjcfopq_b`^rpbeb$pkbrqo^i)plgrpqork_^`h^ka`e^odbqebkrpbvlroObq^if^qflkclo?fdTfii%35+3)15+4&yyWyQeb?^oobkpyyNFAy.4.6y
QQeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
KPhfmkbuqnrbpq++y@yT^oofloyyNFAy14/y

CO^q`ebqy@yT^oil`hyyKy@^pp^@ofjplktfkd%34+0)2.&yyWyArpqt^iiltJ^opeyyNFAy.425y
QPbbhfkdPqo^e^ay@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.465y
>Qljblcqeb@^_^i%M^oq.&y@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.425y

C@fqvlcFolkclodby@yT^oil`hyyKyCivqlQebo^jlob+Qebkq^hbqeb_l^qqlJbkbqefiE^o_lo^kacivqlFolkclodbyyNFAy.5-/y
QQljblcqeb@^_^i%M^oq.&yKyHoljPqlrq^oj%41+0)6+1&yy@yT^oil`hyyNFAy.425yyWyFolkclodby
>Qljblcqeb@^_^i%M^oq/&yKyHoljPqlrq^oj%41+0)6+1&yy@yT^oil`hyyNFAy.5-/yyWyFolkclodby
CQebo^jlobFpiby@yT^oil`hyyKyCivqlJbkbqefiE^o_lo^kaq^hbqeb_l^qlkqebplrqebokmfboyyNFAy14/y

OQeb?^oobkpyKyDlqlQeb?^oobkp%/5+1)13+4&yy@yT^oil`hyyWyArpqt^iiltJ^opeyyNFAy14/y
OQelrp^kaKbbaibpyKyDlqlQelrp^kaKbbaibp%1/+3)62+.&yy@yT^oil`hyyWyQeb?^oobkpyyNFAy14/y
KDbqqebXQ^qqbobaJ^krp`ofmqZyKyFkpfabqeb`^sbb^pqlcqebDob^qIfcqfkQelrp^kaKbbaibp%10+2)0/+4&yyIy3664yy@yT^oil`hyyWyQelrp^kaKbbaibpyyNFAy.5-/y
EJbkbqefiE^o_loy@yT^oil`h)T^oofloyyRy3615yyNFAy14/y

CJbkbqefiE^o_loyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy14/y
>C^iilcArkJlaoyKyE^oil?^ok^_v%.-+6)22+6&yyNFAy14/y

@Ifcqfkdqeb@ropbyKyHfiiqeb@^mq^fkcloqebXFkqobmfaPqolkd_luHbvZ)t^ihrmqeboraaboqlob^`eefj%.2+2)/0+2&yyNFAy/6-y
QIfcqfkdqeb@ropbyKyFkqobmfa$pIl`hbaPqolkd_lu%.1+2)/1+.&+Lmbkqeb_lulk_lqqljcillolcqeb_l^q)fq$prkabot^qboyyNFAy/6-y
>QebBvblcM^ibqeyKyFkqobmfa$pIl`hbaPqolkd_lu%.1+2)/1+.&yyNFAy/6/y
QKbh$olpe$pD^j_fqyKyAo^dlkj^t@^q^mriq%14+2)13+6&+Phfmqebcliilt*rmyyNFAy132y

QC^iilcArkJlaoyKyIlkd_o^faqebDofj%16+5).5+0&yyNFAy14/y
>QebA^ohFolkT^oyKyJlqibvD^oj^plk%16+4).5+0&yyNFAy0-0y
>>DofjQ^phyKyIlkd_o^faqebDofj%16+5).5+0&yyNFAy0-1y

>QebQe^kaliPm^k%M^oq.&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy30.y
QQebQe^kaliPm^k%M^oq.&yKyB_bkbwboOrpqil`hb$p@lompb*Eb^alrqqlqebjfaaiblcQe^kaliPm^k)eb^aaltkqebpq^fopqlqebofdeq%2.+/)5+-&yyNFAy30.y
>QebQe^kaliPm^k%M^oq/&yKyB_bkbwboOrpqil`hb$p@lompb%2.+/)5+-&yyNFAy30/y
QQebQe^kaliPm^k%M^oq/&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy30/y
>QebQe^kaliPm^k%M^oq0&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy300y

@>DofjQ^phyKyHfii?^id^o^pqebClriqldbqefpb^o+@eb`h^qqeb`^jmqlqebb^pq%3-)/4&yyNFAy0-1y
@QebA^ohFolkT^oyKyVlr`^kcfkaqebjfk_lqe`^jmp%14+5).4+0&^ka%3-+4)/.+4&yyNFAy0-0y

Q>DofjQ^phyKyIlkd_o^faqebDofj%16+5).5+0&yyNFAy0-1y
QQebA^ohFolkT^oyKyJlqibvD^oj^plk%16+4).5+0&yyNFAy0-0y

@QebQe^kaliPm^k%M^oq0&yWy>o^qefEfdei^kapyyKy>`olppQe^kaliPm^k)qebk^`olppqebpj^ii_ofadbqlqebb^pq%15)55&yyNFAy300y
QQebQe^kaliPm^k%M^oq0&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy300y
>Mib^QlQeb>iif^k`byKyOe^dD^oj^plk%16+6).5+0&yyNFAy301y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
