DugisGuideViewer:RegisterGuide("Mana-Tombs (64-66)", "", "Horde", "I", function()
return [[
AAA


OJ^k^Qlj_pyKyQo^sbiqlJ^k^Qlj_p%06+3/)3/+03&%06+2)25+2&yyWy.62/yyNFAy.-/.3y
>P^cbqvFpGl_LkbyKy%km`7.634-&%06+2)25+2&yyWy.62/yyNFAy.-/.3yyKM@y.634-y
>Rkabo`rqqfkdqeb@ljmbqfqflkyKy%km`7.6341&%06+1)25+2&yyWy.62/yyNFAy.-.32yyKM@y.6341y

OJ^k^*Qlj_pyNFAy.-/.5yyKyNrbrbcloJ^k^*Qlj_prpfkdqebarkdblkcfkaboyyNFAy.-/.3yyFy
@P^cbqvFpGl_LkbyKyHfii.-Bqebob^i@ovmqO^fabop)2Bqebob^iPlo`bobop)2KburpPq^ihbop^ka2Bqebob^iPmbii_fkabopfkqebJ^k^Qlj_pyyNFAy.-/.3yyAJ>MyJ^k^\Qlj_pyyKM@y.50..).50.0).50.1).50./y
QP^cbqvFpGl_LkbyKyBqebob^iQo^kpmloqbo@lkqoliM^kbi%1.+2/)5.+/3&@if`hqeb`r_bqebkqebpmb^h_r__ibql^`qfs^qbfqyyNFAy.-/.3yyAJ>MyJ^k^\Qlj_pyyL?Gy3563y
@Rkabo`rqqfkdqeb@ljmbqfqflkyKyHfiiKburp*Mofk`bPe^cc^o^kadbqXPe^cc^o$pTo^mmfkdpZ+Ebalbpmofj^oivj^df`^ia^j^db)^kae^p^aapqe^qtfiikrhbvlr^ipl+Hfiiqeb^aapofdeq^t^v^katebkqebvpm^tkrmarofkdqebcfdeq+Vlrkbbaqlork^olrkaqlpq^vfko^kdb%0/+2)50+1&%0/+2)16+0&yyNFAy.-.32yyAJ>MyJ^k^\Qlj_pyyKM@y.5011y
>PljblkbBipb$pE^oaTlohM^vpLccyKy%km`7.634.&%1.+2/)5.+/3&_vqebBqebob^iQo^kpmloqbo@lkqoliM^kbiyyNFAy.-/.5yyAJ>MyJ^k^\Qlj_pyyKM@y.634.y
@PljblkbBipb$pE^oaTlohM^vpLccyKyBp`loq%km`7.634.&yyNFAy.-/.5yyAJ>MyJ^k^\Qlj_pyyKM@y.634.y

OQbolhh^oClobpqyKyBufqqlQbolhh^oClobpqcoljqebbkqo^k`b%0/+6)02+0&%1-+/)01+.&%1-+/)/5+2&%00+6)/2+3&%00+2)..&yyWy.62/yyNFAy.-.31y
QPljblkbBipb$pE^oaTlohM^vpLccyKy%km`7.6341&%06+1)25+2&yyWy.62/yyNFAy.-/.5yyKM@y.6341y
QRkabo`rqqfkdqeb@ljmbqfqflkyKy%km`7.6341&%06+1)25+2&yyWy.62/yyNFAy.-.32yyKM@y.6341y

O>r`ebk^f@ovmqpyKyWlkbfkql>r`ebk^f@ovmqpyyNFAy.-.31yyFy
@BsbovqefkdTfii?b>iofdeqyKyHfiiqebcfk^i_lpp%km`7.5040&yyNFAy.-.31yyKM@y.5040yyAJ>My>r`ebk^f\@ovmqpy

OQbolhh^oClobpqyKyQo^sbi_^`hqlQbolhh^oClobpq%02+.)32+/&yyWy.62/yyFy
QBsbovqefkdTfii?b>iofdeqyKy%km`7.6365&%02+.)32+/&ebfplrqpfabqebfkpq^k`bplvlre^sbillhcloefj^qqeb_lqqljyyNFAy.-.31yyWy.62/yyKM@y.6365y

KDrfab@ljmibqbyKy@lkqfkrbql%drfab7/23%32*34&&y


]]
end)