DugisGuideViewer:RegisterGuide("Argent Tournament (Champion Dailies)", nil, "Horde", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky

>Qeob^qColj>_lsbyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.05./yyWyF`b`oltkyyAy
>?^qqib?bclobQeb@fq^abiyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.0530yyWyF`b`oltkyyAy
>Q^hfkd?^qqibQlQebBkbjvyKyWlo$_bqeb?illaibqqbo%40+5).6+1&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.0yyWyF`b`oltkyyAy
>>jlkdqeb@e^jmflkpyKyFiivofbKfdeqc^ii%40+3)/-&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.1yyWyF`b`oltkyyAy

>Qeob^qColj>_lsbyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.05-6yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>?^qqib?bclobQeb@fq^abiyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.053/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>Q^hfkd?^qqibQlQebBkbjvyKy@biif^kA^v_ob^h%36+6)/0+2&)A^fivyyNFAy.05.-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.05..yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

KMf`hrm0S^if^kqNrbpqpyKyMf`hrm0NrbpqpfkPrkob^sbopM^sfiflk%43+0)/1+1&$>S^if^kq$pCfbiaQo^fkfkd$)$QebDo^kaJbibb$)^ka$>qqebBkbjvpD^qbp$yyWyF`b`oltky

>>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

>QebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy

>>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmXEloabI^k`bZ^kadbq^Jlrkq%42+3)/0+3&lo%4.+52)/-&yyRy13-4-yyWyF`b`oltky
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0454yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.045/yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0434yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0444yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.044/yyLyyWyF`b`oltkyyAy
@>jlkdqeb@e^jmflkpyKyQ^ihqlPnrfobA^kkv%35+3)/.&ql_bdfkqebcfdeqyyNFAy.05.1yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@>jlkdqeb@e^jmflkpyKyAbcb^q1@e^jmflkp^qqebOfkdlc@e^jmflkp%4.+2)/0+5&yyNFAy.05..yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0453yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.045.yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0432yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0443yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.044.yyLyyWyF`b`oltkyyAy
@Q^hfkd?^qqibQlQebBkbjvyKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.05.0yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@Q^hfkd?^qqibQlQebBkbjvyKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.05.-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0526yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.053-yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0523yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0525yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0524yyLyyWyF`b`oltkyyAy

@?^qqib?bclobQeb@fq^abiyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo)rpbvlroPefbia?ob^hboqlhfiid^odlvibp+Orklsbo^kvobdri^op`lrodbphbiifbp^karpbqebrpr^iq^`qf`^d^fkpqvlrojlrkqbalmmlkbkqp+yyNFAy.053/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyLyyWyF`b`oltkyyAy
@?^qqib?bclobQeb@fq^abiyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo)rpbvlroPefbia?ob^hboqlhfiid^odlvibp+Orklsbo^kvobdri^op`lrodbphbiifbp^karpbqebrpr^iq^`qf`^d^fkpqvlrojlrkqbalmmlkbkqp+yyNFAy.0530yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy

@Qeob^qColj>_lsbyKyHfii@efiij^t%12+3)0.+5&^ka0u@riqfpq?lj_^oafboyyNFAy.05./yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@Qeob^qColj>_lsbyKyHfii@efiij^t%12+3)0.+5&^ka0u@riqfpq?lj_^oafboyyNFAy.05-6yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

Q>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

QQebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

QQeob^qColj>_lsbyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.05./yyWyF`b`oltkyyAy
QQ^hfkd?^qqibQlQebBkbjvyKyWlo$_bqeb?illaibqqbo%40+5).6+1&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.0yyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyFiivofbKfdeqc^ii%40+3)/-&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.1yyWyF`b`oltkyyAy
Q?^qqib?bclobQeb@fq^abiyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.0530yyWyF`b`oltkyyAy

QQeob^qColj>_lsbyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.05-6yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
QQ^hfkd?^qqibQlQebBkbjvyKy@biif^kA^v_ob^h%36+6)/0+2&)A^fivyyNFAy.05.-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q?^qqib?bclobQeb@fq^abiyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.053/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.05..yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.046-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
