DugisGuideViewer:RegisterGuide("Argent Tournament (Champion + Exalted Sunreaver + Crusader Dailies)", nil, "Horde", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky

>Qeob^qColj>_lsbyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.05./yyWyF`b`oltkyyAy
>?^qqib?bclobQeb@fq^abiyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.0530yyWyF`b`oltkyyAy
>Q^hfkd?^qqibQlQebBkbjvyKyWlo$_bqeb?illaibqqbo%40+5).6+1&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.0yyWyF`b`oltkyyAy
>>jlkdqeb@e^jmflkpyKyFiivofbKfdeqc^ii%40+3)/-&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.1yyWyF`b`oltkyyAy

>Qeob^qColj>_lsbyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.05-6yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>?^qqib?bclobQeb@fq^abiyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.053/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>Q^hfkd?^qqibQlQebBkbjvyKy@biif^kA^v_ob^h%36+6)/0+2&)A^fivyyNFAy.05.-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.05..yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

KMf`hrm/@orp^aboNrbpqyKyMf`hrm/@orp^aboNrbpq%36+2)/0+/&)qebpbnrbpqfplkiv^s^fi^_ibfcvlre^sbb^okqeb9@orp^abo;qfqib_vdbqqfkdbu^iqbaql^iiqebc^`qflkyyWyF`b`oltky

>Jfpq`^iiboVkds^oyLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-/yyWyF`b`oltkyyAy
>AolqqfkkEolqed^oyLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-.yyWyF`b`oltkyyAy
>LoklicQebP`^oobayLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-1yyWyF`b`oltkyyAy
>Ab^qepmb^hboHe^olpyLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-2yyWyF`b`oltkyyAy

>QebC^qbLcQebC^iibkyLyyKy@orp^aboPfisboa^tk%36+2)/0+.&yyNFAy.1.-4yyWyF`b`oltkyyAy
>DbqHo^hbkyLyyKy@orp^aboPfisboa^tk%36+2)/0+.&yyNFAy.1.-5yyWyF`b`oltkyyAy

KMf`hrm0Prkob^sboNrbpqyKyMf`hrm0Bu^iqbaPrkob^sbopNrbpqp.coljQvilpA^tkorkkbo^ka/coljDfo^k^qeb?illaba%43+.)/1+.&yyWyF`b`oltky
>Vlr$sbOb^iivAlkbFqQefpQfjb)HriyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.1/yyLyyWyF`b`oltkyyAy
>Obp`rb^qPb^yKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.03yyLyyWyF`b`oltkyyAy
>PqlmQeb>ddobpplopyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.1-yyLyyWyF`b`oltkyyAy
>QebIfdeq$pJbo`vyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.11yyLyyWyF`b`oltkyyAy
>>IbdRmyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.10yyLyyWyF`b`oltkyyAy

>Te^qAlVlrCbba^Vbqf)>kvt^v<yKyQvilpA^tkorkkbo%43+.)/1+.&yyNFAy.1.12yyLyyWyF`b`oltkyyAy
>?ob^hc^pqLc@e^jmflkpyKyQvilpA^tkorkkbo%43+.)/1+.&yyNFAy.1-6/yyLyyWyF`b`oltkyyAy
>DlojlhT^kqpEfpPkl_liapyKyQvilpA^tkorkkbo%43+.)/1+.&yyNFAy.1.1.yyLyyWyF`b`oltkyyAy

@DbqHo^hbkyLyyKyGrjmlkqebDovmelkJlrkq%36+5)//+/&^kaHfii5uKloqePb^Ho^hbk^ka3Hs^iafoAbbm`^iibotfqevlropmb^oyyNFAy.1.-5yyRy13621yyWyF`b`oltkyyAy

KMf`hrm0S^if^kqNrbpqpyKyMf`hrm0NrbpqpfkPrkob^sbopM^sfiflk%43+0)/1+1&$>S^if^kq$pCfbiaQo^fkfkd$)$QebDo^kaJbibb$)^ka$>qqebBkbjvpD^qbp$yyWyF`b`oltky

>>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

>QebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy

>>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmXEloabI^k`bZ^kadbq^Jlrkq%42+3)/0+3&yyRy13-4-yyWyF`b`oltky
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0454yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.045/yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0434yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0444yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.044/yyLyyWyF`b`oltkyyAy
@>jlkdqeb@e^jmflkpyKyQ^ihqlPnrfobA^kkv%35+3)/.&ql_bdfkqebcfdeqyyNFAy.05.1yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@>jlkdqeb@e^jmflkpyKyAbcb^q1@e^jmflkp^qqebOfkdlc@e^jmflkp%4.+2)/0+5&yyNFAy.05..yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@Vlr$sbOb^iivAlkbFqQefpQfjb)HriyKyHfiiqebA^ohOfqr^ifpq^kaA^ohWb^ilq^olrkaqldbqqebhbv^karpbfqqllmbkqeb`^db%3.)/0&yyNFAy.1.1/yyLyyWyF`b`oltkyyAy
@Ab^qepmb^hboHe^olpyLyyKyHfiiAb^qepmb^hboHe^olp%31+1)/.+2&yyNFAy.1.-2yyWyF`b`oltkyyAy

KTe^qAlVlrCbba^Vbqf)>kvt^v<yKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$Te^qAlVlrCbba^Vbqf)>kvt^v<$+Mf`hrmXCobpe@erjmZcoljqeb_l^q^q%41)6&yyWyF`b`oltkyyIy14-03yyAy
@Te^qAlVlrCbba^Vbqf)>kvt^v<yKyGrjmfkqebt^qbo%41+5)6+.&^karpbqebXCobpe@erjZql^qqo^`qqebPe^ohpyyRy14-03yyNFAy.1.12yyLyyWyF`b`oltkyyAy

@Obp`rb^qPb^yKyHfii5uHs^iafo?bopbohbo^ka0uHs^iafoE^omllkbo%11)20&%16)16&yyNFAy.1.03yyLyyWyEolqed^o$pI^kafkdyyAy
@PqlmQeb>ddobpplopyKyHfii.-uHs^iafo%2-)/6&%11)20&%16)16yyNFAy.1.1-yyLyyWyEolqed^o$pI^kafkdyyAy
@QebIfdeq$pJbo`vyKyCfkaPi^fkQr^ifnSfii^dbo%11)0.&%2.)0-&%22)/-&qebkrpbX@lkcbpplo$pMo^vbo?llhZlkqeb_lafbpyyRy1354-yyNFAy.1.11yyLyyWyEolqed^o$pI^kafkdyyAy
@IbdRmyKy@liib`q.-uXPqlibkQ^iipqofaboIbdZ%11)0.&%2.)0-&%22)/-&yyNFAy.1.10yyLyyWyEolqed^o$pI^kafkdyyAy

@Jfpq`^iiboVkds^oyLyyKyBkqboqeb`^sb^q%10)/2&^kaRpbXJfpq`^iibo$p@e^ojZqlprjjlkJfpq`^iiboVkds^o^kahfiiefjyyRy14--6yyNFAy.1.-/yyWyEolqed^o$pI^kafkdyyAy
@AolqqfkkEolqed^oyLyyKyRpbXHs^iafoT^oElokZqlprjjlkAolqqfkkEolqed^o^kahfiiefj%2-).2&yyRy14--3yyNFAy.1.-.yyWyEolqed^o$pI^kafkdyyAy
@LoklicQebP`^oobayLyyKyRpbX@^mqrobaHs^iafo?^kkboZqlprjjlkLoklicQebP`^ooba^kahfiiefj%15+4)0.+1&yyRy14-/6yyNFAy.1.-1yyWyEolqed^o$pI^kafkdyyAy

@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0453yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.045.yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0432yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0443yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyWyF`b`oltkyyNFAy.044.yyLyyWyF`b`oltkyyAy
@Q^hfkd?^qqibQlQebBkbjvyKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.05.0yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@Q^hfkd?^qqibQlQebBkbjvyKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.05.-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@QebC^qbLcQebC^iibkyLyyKyDlql%2-+/)1.+0&^kad^qebopfuXAfp`^oabaPlri@ovpq^ipZ^karpbqebXIfdeq*?ibppbaObif`ZlkpfuC^iibkEbol$pPmfofqpyyNFAy.1.-4yyRy14-00yyWyF`b`oltkyyAy

@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0526yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.053-yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0523yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0525yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0524yyLyyWyF`b`oltkyyAy

@?^qqib?bclobQeb@fq^abiyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo)rpbvlroPefbia?ob^hboqlhfiid^odlvibp+Orklsbo^kvobdri^op`lrodbphbiifbp^karpbqebrpr^iq^`qf`^d^fkpqvlrojlrkqbalmmlkbkqp+yyNFAy.053/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyLyyWyF`b`oltkyyAy
@?^qqib?bclobQeb@fq^abiyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo)rpbvlroPefbia?ob^hboqlhfiid^odlvibp+Orklsbo^kvobdri^op`lrodbphbiifbp^karpbqebrpr^iq^`qf`^d^fkpqvlrojlrkqbalmmlkbkqp+yyNFAy.0530yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy

@?ob^hc^pqLc@e^jmflkpyKy@liib`q1XGlojrkd^oBddP^`pZrpbqebXB^oqepe^hboAorjZ^qqebpkltjlrkap^ob^olrka%12)24&fkPqlojMb^hpyyRy13560yyNFAy.1-6/yyLyyWyQebPqlojMb^hpyyAy
@DlojlhT^kqpEfpPkl_liapyKyRpbXTbfdeqbaKbqZql`^mqrob5Pklt_ifkaCliiltbop^olrka%11+-)5/+.&^qqebPqlojMb^hpyyRy13552yyNFAy.1.1.yyLyyWyQebPqlojMb^hpyyAy

@Qeob^qColj>_lsbyKyHfii@efiij^t%12+3)0.+5&^ka0u@riqfpq?lj_^oafboyyNFAy.05./yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@Qeob^qColj>_lsbyKyHfii@efiij^t%12+3)0.+5&^ka0u@riqfpq?lj_^oafboyyNFAy.05-6yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

Q>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

QQebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

QJfpq`^iiboVkds^oyLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-/yyWyF`b`oltkyyAy
QAolqqfkkEolqed^oyLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-.yyWyF`b`oltkyyAy
QLoklicQebP`^oobayLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-1yyWyF`b`oltkyyAy
QAb^qepmb^hboHe^olpyLyyKyEfde@orp^abo>abi^oa%36+2)/0+/&yyNFAy.1.-2yyWyF`b`oltkyyAy

QQebC^qbLcQebC^iibkyLyyKy@orp^aboPfisboa^tk%36+2)/0+.&yyNFAy.1.-4yyWyF`b`oltkyyAy
QDbqHo^hbkyLyyKy@orp^aboPfisboa^tk%36+2)/0+.&yyNFAy.1.-5yyWyF`b`oltkyyAy
>FabkqfcvfkdqebObj^fkpyLyyKyRpbXHo^hbkQllqeZql^``bmqqebnrbpqyyIy13622yyNFAy.1-62yyWyF`b`oltkyyAy
QFabkqfcvfkdqebObj^fkpyLyyKy@orp^aboPfisboa^tk%36+2)/0+.&yyNFAy.1-62yyWyF`b`oltkyyAy

QVlr$sbOb^iivAlkbFqQefpQfjb)HriyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.1/yyLyyWyF`b`oltkyyAy
QObp`rb^qPb^yKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.03yyLyyWyF`b`oltkyyAy
QPqlmQeb>ddobpplopyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.1-yyLyyWyF`b`oltkyyAy
QQebIfdeq$pJbo`vyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.11yyLyyWyF`b`oltkyyAy
Q>IbdRmyKyDfo^k^qeb?illaba%43+.)/1+.&yyNFAy.1.10yyLyyWyF`b`oltkyyAy

QTe^qAlVlrCbba^Vbqf)>kvt^v<yKyQvilpA^tkorkkbo%43+.)/1+.&yyNFAy.1.12yyLyyWyF`b`oltkyyAy
Q?ob^hc^pqLc@e^jmflkpyKyQvilpA^tkorkkbo%43+.)/1+.&yyNFAy.1-6/yyLyyWyF`b`oltkyyAy
QDlojlhT^kqpEfpPkl_liapyKyQvilpA^tkorkkbo%43+.)/1+.&yyNFAy.1.1.yyLyyWyF`b`oltkyyAy

QQeob^qColj>_lsbyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.05./yyWyF`b`oltkyyAy
QQ^hfkd?^qqibQlQebBkbjvyKyWlo$_bqeb?illaibqqbo%40+5).6+1&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.0yyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyFiivofbKfdeqc^ii%40+3)/-&)A^fivyy@yAb^qeHkfdeqyyNFAy.05.1yyWyF`b`oltkyyAy
Q?^qqib?bclobQeb@fq^abiyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyy@yAb^qeHkfdeqyyNFAy.0530yyWyF`b`oltkyyAy

QQeob^qColj>_lsbyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.05-6yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
QQ^hfkd?^qqibQlQebBkbjvyKy@biif^kA^v_ob^h%36+6)/0+2&)A^fivyyNFAy.05.-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q?^qqib?bclobQeb@fq^abiyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.053/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.05..yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.046-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
