DugisGuideViewer:RegisterGuide("Argent Tournament (Valiant Dailies)", nil, "Horde", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky

KMf`hrm1NrbpqpyKyMf`hrm1NrbpqpfkPrkob^sbopM^sfiflk%43+0)/1+1&yyWyF`b`oltky
>>?i^abCfqClo>@e^jmflkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0450yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0445yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.043/yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0440yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0435yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0452yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.045-yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0431yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0442yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyWri$qlob%43)/1+2&)A^fivyyNFAy.044-yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0451yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0446yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0430yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0441yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0436yyLyyWyF`b`oltkyyAy

>>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

>QebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmXEloabI^k`bZ^kadbq^Jlrkq%42+3)/0+3&lo%4.+52)/-&yyRy13-4-yyWyF`b`oltky
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0454yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.045/yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0434yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0444yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.044/yyLyyWyF`b`oltkyyAy

@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0453yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyWyF`b`oltkyyNFAy.045.yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0432yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyWyF`b`oltkyyNFAy.0443yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyWyF`b`oltkyyNFAy.044.yyLyyWyF`b`oltkyyAy

@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0526yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.053-yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0523yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0525yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0524yyLyyWyF`b`oltkyyAy

@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0450yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0445yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.043/yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0440yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0435yyLyyAy
KQebBadbLcTfkqboyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$QebBadbLcTfkqbo$CfkaIloaBsbo_i^wb^olrka%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZqebkqf`hqefpl_gb`qfsbyyIy12--2yyWy@ovpq^iplkdClobpqy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0452yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.045-yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0431yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0442yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.044-yyLyyAy
K>TloqevTb^mlkyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$>TloqevTb^mlk$@liib`q1XTfkqboEv^`fkqeZ^olrka%4.)41+2&fkF`b`oltkqebkqf`hqefpl_gb`qfsbyyIy12---1yyWyF`b`oltky
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0451yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0446yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0430yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0441yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0436yyLyyAy

Q>?i^abCfqClo>@e^jmflkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0450yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0445yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.043/yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0440yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0435yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0452yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.045-yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0431yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0442yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyWri$qlob%43)/1+2&)A^fivyyNFAy.044-yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0451yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0446yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0430yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0441yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0436yyLyyWyF`b`oltkyyAy

Q>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

QQebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
