DugisGuideViewer:RegisterGuide("Argent Tournament (78+ Quest Chain)", nil, "Horde", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky
cMf`hrmcifdeqmlfkqyKyEbifa^kIfdeqtfkd%4/+3)//+3&yyWyF`b`oltky

>Qeb>odbkqQlrok^jbkqyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0335yyWyF`b`oltky

QQeb>odbkqQlrok^jbkqyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0335yyWyF`b`oltky

>J^pqbovLcJbibbyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.05/6yyWyF`b`oltky
>J^pqbovLcQeb@e^odbyKy>j^ofbiPrkptlok%43+0)/1+1&yyNFAy.0506yyWyF`b`oltky
>J^pqbovLcQebPefbia*?ob^hboyKyD^i^qef^?ofdeqa^tk%43+0)/1+1&yyNFAy.0505yyWyF`b`oltky

KDbqlkJlrkqyKyBnrfmXEloabI^k`bZ^kadbq^Jlrkq%42+3)/0+3&lo%4.+52)/-&yyRy13-4-yyWyF`b`oltky

KPmb^hqlGbo^kIl`htllayKyDbqGbo^kIl`htlla%4/+1).6+0&^asf`byyNFAy.05/6yyNLyGbo^kIl`htlla$p^asf`b7.,.yyWyF`b`oltky
@J^pqbovLcJbibbyKyEfqqebarjjv2qfjbp_vmobppfkd1)/%4/+0).6+0&yyNFAy.05/6yyWyF`b`oltky
KPmb^hqlS^ifpTfka`e^pboyKyDbqS^ifpTfka`e^pbo%40+/).6+/&^asf`byyNFAy.0505yyNLyS^ifpTfka`e^pbo$p^asf`b7.,.yyWyF`b`oltky
@J^pqbovLcQebPefbia*?ob^hboyKyMobpp/qlrpbqebPefbia?ob^hbo^_fifqvlk^O^kdbaQ^odbq%40+.).6&yyNFAy.0505yyWyF`b`oltky
KPmb^hqlOrd^kPqbbi_biivyKyDbqOrd^kPqbbi_biiv%4/+4).5+6&^asf`byyNFAy.0506yyNLyOrd^kPqbbi_biiv$p^asf`b7.,.yyWyF`b`oltky
@J^pqbovLcQeb@e^odbyKyMobpp/qlrpbqebPefbia?ob^hbo^_fifqvlk^@e^odbaQ^odbq%4/+6).5+6&obmb^qfsbivrkqfisrikbo^_ibqebkmobpp0ql@e^odbyyNFAy.0506yyWyF`b`oltky

QJ^pqbovLcQeb@e^odbyKy>j^ofbiPrkptlok%43+0)/1+1&yyNFAy.0506yyWyF`b`oltky
QJ^pqbovLcJbibbyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.05/6yyWyF`b`oltky
QJ^pqbovLcQebPefbia*?ob^hboyKyD^i^qef^?ofdeqa^tk%43+0)/1+1&yyNFAy.0505yyWyF`b`oltky

>RmQlQeb@e^iibkdbyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0345yyWyF`b`oltky

KPtfq`eDrfab#@ljmibqb0A^fifbpQebk+++yKyPtfq`evlrodrfabql>odbkqQlrok^jbkq%O^kh7>pmfo^kqA^fifbp&qebk`ljb_^`hqlqefpdrfab^cqbovlr`ljmibqbyyWyF`b`oltky

>Qeb?i^`hHkfdeqlcPfisbomfkb<yKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0301yyWyF`b`oltky
CA^i^o^kyKyCiv_^`hqlA^i^o^k)Ebifa^kIfdeqtfkd%4/+3)//+3&yyWyF`b`oltky
eA^i^o^kyKyPbqvlroeb^oqeqlA^i^o^ky
ORkabo`fqvyKyDl_^`hqlA^i^o^k^kaq^hbqebqbibmloqqlRkabo`fqvy
CQebPbmri`eboyKyCivqlQebPbmri`ebofkPfisbomfkbClobpqy
@Qeb?i^`hHkfdeqlcPfisbomfkb<yKyCfkaqebXArpqvGlrok^iZlkqeb_lqqljcillolcqebofdeqelrpb^q%20+.)/5+.&yyNFAy.0301yyWyPfisbomfkbClobpqy
EA^i^o^kyRy3615y
C>odbkqQlrok^jbkqDolrkapyKy>ira^kbTefqb`ilra%4/+4)12+4&yyWyA^i^o^ky
QQeb?i^`hHkfdeqlcPfisbomfkb<yKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0301yyWyF`b`oltky

>QebPbbo$p@ovpq^iyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.031.yyWyF`b`oltky
CA^i^o^kyKyCiv_^`hqlA^i^o^k)Ebifa^kIfdeqtfkd%4/+3)//+3&yyWyF`b`oltky
@QebPbbo$p@ovpq^iyKyHfiiRk_lrkaPbbopfkqebCloilokTllap%10+0)13+3&qfiivlr`liib`q^XPbbo$p@ovpq^iZyyNFAy.031.yyWy@ovpq^iplkdClobpqy
QQebPbbo$p@ovpq^iyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.031.yyWyF`b`oltky

>QebPqlofbpAb^aJbkQbiiyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0310yyWyF`b`oltky
@QebPqlofbpAb^aJbkQbiiyKyRpbqebXPbbo$p@ovpq^iZlkqebqeobbdo^sbp^q%46+1)/0&yyRy12-4-yyNFAy.0310yyWyF`b`oltky
QQebPqlofbpAb^aJbkQbiiyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0310yyWyF`b`oltky

>Qebob$pPljbqefkd>_lrqqebPnrfobyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0321yyWyF`b`oltky
CA^i^o^kyKyCiv_^`hqlA^i^o^k)Ebifa^kIfdeqtfkd%4/+3)//+3&yyWyF`b`oltky
HHfiiPhbibq^iTlla`rqqbopyKyHfiiPhbibq^iTlla`rqqbop%05+0)26+1&fk@ovpq^iplkdClobpqrkqfivlrcfkaXI^odbCbjroZyyIy12-5-yyWy@ovpq^iplkdClobpqy
@Qebob$pPljbqefkd>_lrqqebPnrfobyKyRpbqebXI^odbCbjroyqefp_befkaJ^ilof`%05+0)26+1&^kaillqefjyyRy12-5-yyNFAy.0321yyWy@ovpq^iplkdClobpqy
C>odbkqQlrok^jbkqDolrkapyKy>ira^kbTefqb`ilra%4/+4)12+4&yyWyA^i^o^ky
QQebob$pPljbqefkd>_lrqqebPnrfobyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0321yyWyF`b`oltky

>Qeb?i^`hHkfdeq$pLoabopyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0330yyWyF`b`oltky
RDbq?i^`hHkfdeq$pDovmelkyKyDbq?i^`hHkfdeq$pDovmelk%44+5)/.+3&_vrpfkdqebXBk`e^kqba?ofaibZyyRy12-50yyWyF`b`oltky
@Qeb?i^`hHkfdeq$pLoabopyKyCivKloqeqlqebfpi^ka^kaillqqebXPqlibkQlrok^jbkqFksfq^qflkZfkpfabqebqbkq%21)5+1&^kaqebX?i^`hHkfdeq$pLoabopZyyNFAy.0330yyWyF`b`oltky
QQeb?i^`hHkfdeq$pLoabopyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0330yyWyF`b`oltky


K@liib`q.2uX>pmfo^kq$pPb^iZyKyPtfq`evlrodrfabql>odbkqQlrok^jbkq%O^kh7>pmfo^kqA^fifbp&rkqfivlr`liib`q.2u>pmfo^kq$pPb^i^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)vlrkbbaql`ljmibqbqeb>pmfo^kqa^fivnrbpqclo0a^vpql`liib`qvlropb^ipyyIy12.6/.2y

@RmQlQeb@e^iibkdbyKy@liib`q.2X>pmfo^kq$pPb^iZcoljalfkda^fifbplsbo0a^vp)b^`ea^v`liib`qfkd2X>pmfo^kq$pPb^iZyyNFAy.0345yyWyF`b`oltky
QRmQlQeb@e^iibkdbyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0345yyWyF`b`oltky

>Qeb>pmfo^kq$p@e^iibkdbyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.035-yyWyF`b`oltky
@Qeb>pmfo^kq$p@e^iibkdbyKyPmb^htfqePnrfobA^sfa%4.+1).6+3&)^kaabcb^qqeb>odbkqS^if^kqyyNFAy.035-yyWyF`b`oltky
QQeb>pmfo^kq$p@e^iibkdbyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.035-yyWyF`b`oltky

KMf`hrmS^if^kqLc9@fqv;yKyMf`hrmS^if^kqLc9@fqv;nrbpqcoljJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyWyF`b`oltky
>>S^if^kqLcPfisbojllkyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0363yyLyyWyF`b`oltky
>>S^if^kqLcRkabo`fqvyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0362yyLyyWyF`b`oltky
>>S^if^kqLcLodofjj^oyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.036.yyLyyWyF`b`oltky
>>S^if^kqLcQerkabo?irccyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0361yyLyyWyF`b`oltky
>>S^if^kqLcPbk$gfkyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&yyNFAy.0360yyLyyWyF`b`oltky

Q>S^if^kqLcPfisbojllkyKyPmb^htfqeBobppb^A^tkpfkdbo%43+12)/0+53&yyNFAy.0363yyLyyWyF`b`oltky
Q>S^if^kqLcRkabo`fqvyKyPmb^htfqeAb^qepq^ihboSfp`bof%43+2)/1+/&yyNFAy.0362yyLyyWyF`b`oltky
Q>S^if^kqLcLodofjj^oyKyPmb^htfqeJlho^qebPhrii`orpebo%43+1)/1+3&yyNFAy.036.yyLyyWyF`b`oltky
Q>S^if^kqLcQerkabo?irccyKyPmb^htfqeOrklhTfiaj^kb%43+/)/1+3&yyNFAy.0361yyLyyWyF`b`oltky
Q>S^if^kqLcPbk$gfkyKyPmb^htfqeWri$qlob%43)/1+2&yyNFAy.0360yyLyyWyF`b`oltky

KMf`hrm$QebS^if^kq$p@e^odb$yKyMf`hrmqebnrbpq$QebS^if^kq$p@e^odb$fkPrkob^sbopM^sfiflk%43+0)/1+1&y
>QebS^if^kq$p@e^odbyKyBobppb^A^tkpfkdbo%43+12)/0+53&yyNFAy.04//yyLyyWyF`b`oltky
>QebS^if^kq$p@e^odbyKyAb^qepq^ihboSfp`bof%43+2)/1+/&yyNFAy.04/.yyLyyWyF`b`oltky
>QebS^if^kq$p@e^odbyKyJlho^qebPhrii`orpebo%43+1)/1+3&yyNFAy.0364yyLyyWyF`b`oltky
>QebS^if^kq$p@e^odbyKyOrklhTfiaj^kb%43+/)/1+3&yyNFAy.04/-yyLyyWyF`b`oltky
>QebS^if^kq$p@e^odbyKyWri$qlob%43)/1+2&yyNFAy.04.6yyLyyWyF`b`oltky

K@liib`q/2uXS^if^kq$pPb^iZyKyPtfq`evlrodrfabql>odbkqQlrok^jbkq%O^kh7S^if^kqA^fifbp&rkqfivlr`liib`q/2uXS^if^kq$pPb^iZ^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)`ljmibqbqebS^if^kqa^fivnrbpqclo2a^vpql`liib`qvlropb^ipyyIy12.6//2y

@QebS^if^kq$p@e^odbyKyVlrkbba/2uXS^if^kq$pPb^iZ^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)`ljmibqbqebS^if^kqa^fivnrbpqclo2a^vpql`liib`qvlropb^ipyyNFAy.04//yyLy
@QebS^if^kq$p@e^odbyKyVlrkbba/2uXS^if^kq$pPb^iZ^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)`ljmibqbqebS^if^kqa^fivnrbpqclo2a^vpql`liib`qvlropb^ipyyNFAy.04/.yyLy
@QebS^if^kq$p@e^odbyKyVlrkbba/2uXS^if^kq$pPb^iZ^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)`ljmibqbqebS^if^kqa^fivnrbpqclo2a^vpql`liib`qvlropb^ipyyNFAy.0364yyLy
@QebS^if^kq$p@e^odbyKyVlrkbba/2uXS^if^kq$pPb^iZ^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)`ljmibqbqebS^if^kqa^fivnrbpqclo2a^vpql`liib`qvlropb^ipyyNFAy.04/-yyLy
@QebS^if^kq$p@e^odbyKyVlrkbba/2uXS^if^kq$pPb^iZ^kadbqqebkbuqo^khql`lkqfkrbqefpdrfab)`ljmibqbqebS^if^kqa^fivnrbpqclo2a^vpql`liib`qvlropb^ipyyNFAy.04.6yyLy

QQebS^if^kq$p@e^odbyKyBobppb^A^tkpfkdbo%43+12)/0+53&yyNFAy.04//yyLyyWyF`b`oltky
QQebS^if^kq$p@e^odbyKyAb^qepq^ihboSfp`bof%43+2)/1+/&yyNFAy.04/.yyLyyWyF`b`oltky
QQebS^if^kq$p@e^odbyKyJlho^qebPhrii`orpebo%43+1)/1+3&yyNFAy.0364yyLyyWyF`b`oltky
QQebS^if^kq$p@e^odbyKyOrklhTfiaj^kb%43+/)/1+3&yyNFAy.04/-yyLyyWyF`b`oltky
QQebS^if^kq$p@e^odbyKyWri$qlob%43)/1+2&yyNFAy.04.6yyLyyWyF`b`oltky

KMf`hrm$QebS^if^kq$p@e^iibkdb$yKyMf`hrmqebnrbpq$QebS^if^kq$p@e^iibkdb$fkPrkob^sbopM^sfiflk%43+0)/1+1&yyWyF`b`oltky
>QebS^if^kq$p@e^iibkdbyKyBobppb^A^tkpfkdbo%43+12)/0+53&yyNFAy.040.yyLyyWyF`b`oltky
>QebS^if^kq$p@e^iibkdbyKyAb^qepq^ihboSfp`bof%43+2)/1+/&yyNFAy.04/6yyLyyWyF`b`oltky
>QebS^if^kq$p@e^iibkdbyKyJlho^qebPhrii`orpebo%43+1)/1+3&yyNFAy.04/3yyLyyWyF`b`oltky
>QebS^if^kq$p@e^iibkdbyKyOrklhTfiaj^kb%43+/)/1+3&yyNFAy.04/5yyLyyWyF`b`oltky
>QebS^if^kq$p@e^iibkdbyKyWri$qlob%43)/1+2&yyNFAy.04/4yyLyyWyF`b`oltky

@QebS^if^kq$p@e^iibkdbyKyPmb^htfqePnrfobA^kkv%35+4)/.&)^kaabcb^qqeb>odbkq@e^jmflkyyNFAy.040.yyLyyWyF`b`oltky
@QebS^if^kq$p@e^iibkdbyKyPmb^htfqePnrfobA^kkv%35+4)/.&)^kaabcb^qqeb>odbkq@e^jmflkyyNFAy.04/6yyLyyWyF`b`oltky
@QebS^if^kq$p@e^iibkdbyKyPmb^htfqePnrfobA^kkv%35+4)/.&)^kaabcb^qqeb>odbkq@e^jmflkyyNFAy.04/3yyLyyWyF`b`oltky
@QebS^if^kq$p@e^iibkdbyKyPmb^htfqePnrfobA^kkv%35+4)/.&)^kaabcb^qqeb>odbkq@e^jmflkyyNFAy.04/5yyLyyWyF`b`oltky
@QebS^if^kq$p@e^iibkdbyKyPmb^htfqePnrfobA^kkv%35+4)/.&)^kaabcb^qqeb>odbkq@e^jmflkyyNFAy.04/4yyLyyWyF`b`oltky

QQebS^if^kq$p@e^iibkdbyKyBobppb^A^tkpfkdbo%43+12)/0+53&yyNFAy.040.yyLyyWyF`b`oltky
QQebS^if^kq$p@e^iibkdbyKyAb^qepq^ihboSfp`bof%43+2)/1+/&yyNFAy.04/6yyLyyWyF`b`oltky
QQebS^if^kq$p@e^iibkdbyKyJlho^qebPhrii`orpebo%43+1)/1+3&yyNFAy.04/3yyLyyWyF`b`oltky
QQebS^if^kq$p@e^iibkdbyKyOrklhTfiaj^kb%43+/)/1+3&yyNFAy.04/5yyLyyWyF`b`oltky
QQebS^if^kq$p@e^iibkdbyKyWri$qlob%43)/1+2&yyNFAy.04/4yyLyyWyF`b`oltky

KMf`hrm$>@e^jmflkOfpbp$yKyMf`hrmqebnrbpq$>@e^jmflkOfpbp$fkPrkob^sbopM^sfiflk%43+0)/1+1&yyWyF`b`oltky
>>@e^jmflkOfpbpyKyBobppb^A^tkpfkdbo%43+12)/0+53&yyNFAy.041-yyLyyWyF`b`oltky
>>@e^jmflkOfpbpyKyAb^qepq^ihboSfp`bof%43+2)/1+/&yyNFAy.0406yyLyyWyF`b`oltky
>>@e^jmflkOfpbpyKyJlho^qebPhrii`orpebo%43+1)/1+3&yyNFAy.0403yyLyyWyF`b`oltky
>>@e^jmflkOfpbpyKyOrklhTfiaj^kb%43+/)/1+3&yyNFAy.0405yyLyyWyF`b`oltky
>>@e^jmflkOfpbpyKyWri$qlob%43)/1+2&yyNFAy.0404yyLyyWyF`b`oltky

Q>@e^jmflkOfpbpyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.041-yyLyyWyF`b`oltky
Q>@e^jmflkOfpbpyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0406yyLyyWyF`b`oltky
Q>@e^jmflkOfpbpyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0403yyLyyWyF`b`oltky
Q>@e^jmflkOfpbpyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0405yyLyyWyF`b`oltky
Q>@e^jmflkOfpbpyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0404yyLyyWyF`b`oltky

>Qeb?i^`hHkfdeq$pC^iiyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0331yyWyF`b`oltky
KJlrkqPq^_iba>odbkqT^oelopbyKyBnrfmqqebX>odbkqI^k`bZ^kajlrkqPq^_iba>odbkqT^oelopb%4/+0)//+2&yyWyF`b`oltkyyRy13.-3y
@Qeb?i^`hHkfdeq$pC^iiyKyPmb^hqlPnrfob@^sfk%4.+0)/0+/&qlprjjlk^kaabcb^qqeb?i^`hHkfdeqyyNFAy.0331yyWyF`b`oltky
QQeb?i^`hHkfdeq$pC^iiyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.0331yyWyF`b`oltky
>Qeb?i^`hHkfdeq$p@ropbyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.1-.3yyWyF`b`oltky
@Qeb?i^`hHkfdeq$p@ropbyKyFksbpqfd^qbqebdo^sb^q%46)/0&yyNFAy.1-.3yyWyF`b`oltky
QQeb?i^`hHkfdeq$p@ropbyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.1-.3yyWyF`b`oltky
>Qeb?i^`hHkfdeq$pC^qbyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.1-.4yyWyF`b`oltky
@Qeb?i^`hHkfdeq$pC^qbyKyHfiiAl`qloHleibo%3.+3)//+2&^kamf`hrmXAl`qloHleibo$pLoabopZyyNFAy.1-.4yyWyF`b`oltky
QQeb?i^`hHkfdeq$pC^qbyKy@orp^aboOeva^ii^%36+2)/0+.&yyNFAy.1-.4yyWyF`b`oltky

>B^aof`qebMrobyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0461yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltky
>QebP`lrodb_^kbyKyGrpqf`^oJ^ofbiQorbeb^oq%36+3)//+6&yyNFAy.0462yy@yAb^qeHkfdeqyyWyF`b`oltky

QB^aof`qebMrobyKyB^aof`qebMrob%36+6)/0+1&yyNFAy.0461yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltky
QQebP`lrodb_^kbyKy@olhP`lrodb_^kb%40+5).6+5&yyNFAy.0462yy@yAb^qeHkfdeqyyWyF`b`oltky

KPtfq`eDrfabyKypbib`q>odbkqQlrok^jbkq%O^kh7@e^jmflkA^fifbp&y

KDrfab@ljmibqb

]]
end)
