DugisGuideViewer:RegisterGuide("Grizzly Hills (74+ Dailies)", nil, "Horde", "D", function()
return [[
AAA

C@lknrbpqEliayKyCivql@lknrbpqEliafkDofwwivEfiipy

>?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyAy
@?i^`hofsbo?o^tiyKyHfii.->iif^k`bKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./.4-yyAy
Q?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyAy

>Hbbm$BjlkQebfoEbbipyKy@ljj^kabo?^odlh%01+2)00&yyNFAy.//51yyAy
>Peobaqeb>iif^k`byKyDobhh%01+2)0/+3&yyNFAy.//4-yyAy
>J^hfkdObm^fopyKyIrow%01+0)0/+3&yyNFAy.//5-yyAy
>LsbotebijbayKy>rj^k^%00+6)0/+5&yyNFAy.//63yyAy

@LsbotebijbayKyCfkaqebTlrkabaPhfojfpebop%02)1-&^karpbqebXObkbtfkdQlrokfnrbqZlkqebjyyRy04235yyNFAy.//63yyAy
@J^hfkdObm^fopyKy@liib`q^iiqebmfb`bp^olrka%02)1-&yyNFAy.//5-yyAy
@Peobaqeb>iif^k`byKyMf`hrm^Peobaabo%02)1-&^ka_ofkdfq_^`hqlDobhh%01+2)0/+3&yyNFAy.//4-yyAy
@Hbbm$BjlkQebfoEbbipyKyHfii.2>iif^k`bKM@ploMi^vbopfk?irbPhvIlddfkdDolrkap%02)1-&yyNFAy.//51yyAy

QPeobaqeb>iif^k`byKyDobhh%01+2)0/+3&yyNFAy.//4-yyAy
QJ^hfkdObm^fopyKyIrow%01+0)0/+3&yyNFAy.//5-yyAy
QLsbotebijbayKy>rj^k^%00+6)0/+5&yyNFAy.//63yyAy
QHbbm$BjlkQebfoEbbipyKy@ljj^kabo?^odlh%01+2)00&yyNFAy.//51yyAy

>HbbmQebj^q?^vyKy@bkqroflkH^ddorj%.-+.)44+0&yyNFAy./0.4yyAy
>@orpe@^mq^fk?ofdeqt^qboyKyDbkbo^iHe^wd^o%.-+.)44+/&yyNFAy./0.2yyAy
>Pjlhb$BjLrqyKyPqlkbDr^oaO^dbqlqbj%..+0)43+5&yyNFAy./0/1yyAy
>PbbhfkdPlisbkqyLyyKyDroqlo%..+/)43+3&yyNFAy./100yyAy

@Pjlhb$BjLrqyKyDlql?rkhelrpb7%.2)43&P^tjfii7%.3)43&Pq^_ibp7%.5)5-&^ka^dol^iiqebSbkqrob@ljm^kvPqo^ddibop^karpbqebXPjlhb?lj_Zqebdolrm`e^pfkdvlryyRy043/.yyNFAy./0/1yyAy
@@orpe@^mq^fk?ofdeqt^qboyKyHfii@^mq^fk?ofdeqt^qbo%.4)5/&yyNFAy./0.2yyAy
@HbbmQebj^q?^vyKyHfii.->iif^k`bRkfqp%Tbpqc^ii?ofa^dbJ^ofkb&lo>iif^k`bmi^vbopfkSbkqrob?^v^ob^%.3+4)46&yyNFAy./0.4yyAy
@PbbhfkdPlisbkqyLyyKyDbqqebXBibjbkq..2ZfkqebDl_ifk_l^q%.3+2)5-+0&yyNFAy./100yyAy

QPbbhfkdPlisbkqyLyyKyDroqlo%..+/)43+3&yyNFAy./100yyAy
QHbbmQebj^q?^vyKy@bkqroflkH^ddorj%.-+.)44+0&yyNFAy./0.4yyAy
Q@orpe@^mq^fk?ofdeqt^qboyKyDbkbo^iHe^wd^o%.-+.)44+/&yyNFAy./0.2yyAy
QPjlhb$BjLrqyKyPqlkbDr^oaO^dbqlqbj%..+0)43+5&yyNFAy./0/1yyAy

>OfafkdqebObaOl`hbqyKyDbkbo^iDloilh%.1+5)53+2&yyNFAy./10/yyAy
KDbqBibjbkq..2yKyDbqqebXBibjbkq..2ZfkqebDl_ifk_l^q%.3+2)5-+0&yyIy04331y
KDlqlObaOl`hbq++yKyQf`hqefppqbm_bclobvlrgrjmlkqebObaOl`hbq%.0+4)55+5&y
@OfafkdqebObaOl`hbqyKyGrjmlk^ObaOl`hbq^karpbvlrohbvpqlpqbbo^kaj^hb^_fdRqrokqlt^oapqebEloab?l^q^ka^fjlcqebU%/.+23)51+60&ao^tklkqeb_l^qyyNFAy./10/yyAy
QOfafkdqebObaOl`hbqyKyDbkbo^iDloilh%.1+5)53+2&yyNFAy./10/yyAy

>Pb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-05yyAy
@Pb^obaP`lrodbyKyDlqlqebQolii^ob^%.3)/4&grpqlrqlc^dolo^kdbqeoltqebXJ^`h$pA^ohDoldZql_rokqebQoliipyyRy026-5yyNFAy./-05yyAy
QPb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-05yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
