DugisGuideViewer:RegisterGuide("Horde Expedition/Warsong Offensive (2500 +Rep)", nil, "Horde", "D", function()
return [[
AAA

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
>Hbbmfkdqeb>iif^k`b?ifkayKyPhv*Ob^sboHloj?i^`hp`^olkLodofj$pE^jjboyyNFAy.000.yyWyF`b`oltkyyAy
>?illalcqeb@elpbkyKyT^o_ofkdboA^slpOfleqlkLodofj$pE^jjboyyNFAy.000-yyWyF`b`oltkyyAy

@Hbbmfkdqeb>iif^k`b?ifkayKyRpbXPDJ*0Zqlhfii3Phv_ob^hboOb`lk^olrka%14+0)1-&)fqfpb^pvfcvlr`ob^qb^j^`olcloqefp),q^odbqPhv_ob^hboOb`lkXefqbkqboZ,`^pqPDJ*0yyRy11/./yyNFAy.000.yyWyF`b`oltkyyAy

>>pp^riq_vDolrkayKyHlo$holkPnr^aIb^abo%25+0)13+.&yyNFAy.00-.yyWyF`b`oltkyyAy
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.00-.yyWyF`b`oltkyyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.000-yyWyF`b`oltkyyAy
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00-.yyWyF`b`oltkyyAy

>>pp^riq_v>foyKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00.-yyWyF`b`oltkyyAy
@>pp^riq_v>foyKyDlql%26+3)13+-&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00.-yyWyF`b`oltkyyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00.-yyWyF`b`oltkyyAy

>HfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWyF`b`oltkyyAy
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21)26&yyNFAy.0/50yyWyF`b`oltkyyAy
QHfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWyF`b`oltkyyAy
@Pi^sbpqlP^olkfqbyKyDlqlqebP^olkfqbJfkbp%23)24&)pfjmivq^ihqlqebP^olkfqbJfkbPi^sbpfkqebjfkb)vlre^sb^`e^k`bqe^qqebvtfiiorklrqlcqebjfkb^kadfsbvlrnrbpq`obafq)loqrokelpqfiblkvlryyNFAy.00-/yyWyF`b`oltkyyAy

QHfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWyF`b`oltkyyAy

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
QHbbmfkdqeb>iif^k`b?ifkayKyPhv*Ob^sboHloj?i^`hp`^olkLodofj$pE^jjboyyNFAy.000.yyWyF`b`oltkyyAy
Q?illalcqeb@elpbkyKyT^o_ofkdboA^slpOfleqlkLodofj$pE^jjboyyNFAy.000-yyWyF`b`oltkyyAy

KCfkaCifdeqJ^pqboyKy@ilpbpqcifdeqj^pqbocoljLodofj$pE^jjbotlriabfqebo_bJloif^Alljtfkd%10+4)/1+2&fkPe^altS^riqloMbkrj_ofrp%46+2)4/+0&fk@orp^abo$pMfkk^`ibyyWyF`b`oltky
C@lknrbpqEliayKyCivql@lknrbpqEliafkDofwwivEfiipyyAy

>?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyWyDofwwivEfiipyyAy
@?i^`hofsbo?o^tiyKyHfii.->iif^k`bKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./.4-yyWyDofwwivEfiipyyAy
Q?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyWyDofwwivEfiipyyAy

>Hbbm$BjlkQebfoEbbipyKy@ljj^kabo?^odlh%01+2)00&yyNFAy.//51yyWyDofwwivEfiipyyAy
>Peobaqeb>iif^k`byKyDobhh%01+2)0/+3&yyNFAy.//4-yyWyDofwwivEfiipyyAy
>J^hfkdObm^fopyKyIrow%01+0)0/+3&yyNFAy.//5-yyWyDofwwivEfiipyyAy
>LsbotebijbayKy>rj^k^%00+6)0/+5&yyNFAy.//63yyWyDofwwivEfiipyyAy

@LsbotebijbayKyCfkaqebTlrkabaPhfojfpebop%02)1-&^karpbqebXObkbtfkdQlrokfnrbqZlkqebjyyRy04235yyNFAy.//63yyWyDofwwivEfiipyyAy
@J^hfkdObm^fopyKy@liib`q^iiqebmfb`bp^olrka%02)1-&yyNFAy.//5-yyWyDofwwivEfiipyyAy
@Peobaqeb>iif^k`byKyMf`hrm^Peobaabo%02)1-&^ka_ofkdfq_^`hqlDobhh%01+2)0/+3&yyNFAy.//4-yyWyDofwwivEfiipyyAy
@Hbbm$BjlkQebfoEbbipyKyHfii.2>iif^k`bKM@ploMi^vbopfk?irbPhvIlddfkdDolrkap%02)1-&yyNFAy.//51yyWyDofwwivEfiipyyAy

QPeobaqeb>iif^k`byKyDobhh%01+2)0/+3&yyNFAy.//4-yyWyDofwwivEfiipyyAy
QJ^hfkdObm^fopyKyIrow%01+0)0/+3&yyNFAy.//5-yyWyDofwwivEfiipyyAy
QLsbotebijbayKy>rj^k^%00+6)0/+5&yyNFAy.//63yyWyDofwwivEfiipyyAy
QHbbm$BjlkQebfoEbbipyKy@ljj^kabo?^odlh%01+2)00&yyNFAy.//51yyWyDofwwivEfiipyyAy

KDrfab@ljmibqb
]]
end)
