DugisGuideViewer:RegisterGuide("Howling Fjord (71+ Dailies)", nil, "Horde", "D", function()
return [[
AAA

CH^j^dr^yKyCivqlH^j^dr^fkEltifkdCgloay

>QebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyAy
K@liib`q^CfpeyKyRpbqebX>krkf^n$pKbqZlk^p`ellilccfpe^olrka%00)4.+5&yyRy1-613yyIy01./4y
@QebT^vqlEfpEb^oq+++yKyA^j^db^?rii%0.+6)41+.&pifdeqiv%_brk^ojbafcvlrjbibb^qq^`hefqpqlle^oa&^kaj^hbqebj`e^pbvlrqlqeb@lt)lk`bvlrob^`eqeb`ltrpbXQ^pqvObbcCfpeZlkqeb?riiyyRy01./4yyNFAy..14/yyAy
QQebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
