DugisGuideViewer:RegisterGuide("Speed Gold Run - AT Rank:Valiant (80 Dailies)", nil, "Horde", "D", function()
return [[
AAA

CH0yKyCivqlH0fkQebPqlojMb^hpyyWyQebPqlojMb^hpy
>Lsbopql`hyKyOf`hbq%1-+6)52+1&yyNFAy./500yyWyQebPqlojMb^hpyyAy
@Lsbopql`hyKyRpbqebXFjmolsbaI^kaJfkbpZ^q%1/)5/&qlhfii./uD^ojFks^abopyyRy1-343yyNFAy./500yyWyQebPqlojMb^hpyyAy
QLsbopql`hyKyOf`hbq%1-+6)52+1&yyNFAy./500yyWyQebPqlojMb^hpyyAy

CArkKfccbibjyKyCivqlArkKfccbibj)rpbPhfwwibPif`hpifab%1-+4)51+3&yyWyQebPqlojMb^hpy
KMf`hRm0*3NrbpqyKyMf`hrm0NrbpqfkArkKfccbibjfcvlr$obCofbkaiv)2Nrbpqfcvlr$obElkloba)3Nrbpqfcvlr$obObsbobaqebkqf`hqefp_lu%30+/)3/+6&)%31+/)31+1&)%31+2)26+3&)%30+2)26+5&)%32)3-+6&)%34+2)3-&yyWyQebPqlojMb^hpy
>Elq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWyQebPqlojMb^hpyyAy
>?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWyQebPqlojMb^hpyyAy
>MlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
>PmvErkqboyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*ColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyWyQebPqlojMb^hpyyAy
>QeorpqfkdElafo$pPmb^oyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*Elafo$pPmb^o%32)3-+6&yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
>Cbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyWyQebPqlojMb^hpyyAy

@Cbbafkd>okdofjyLyyKyFcvlre^sbmbqpmrqqebjfkqlm^ppfsbjlab+DlqlqebS^iibvlc>k`fbkqTfkqbop%24)31&^karpbX>okdofj$pQllqeZlkqebOl^jfkdGlojrkd^oqebob+Lk`bqebve^sb_b`ljbafpbj_lafba)vlrjrpqcfdeqqebjrkqfiqebv^obtb^hbkbayyRy1/441yyNFAy.0-13yyWyQebPqlojMb^hpyyAy
@PmvErkqboyLyyKyDllrqql%24+/)31&^karpbXBqebob^iTlod$pC^kdZcliiltqebtlicqe^q^mmb^opqebkhfiiqebAt^osbptebkebpm^tkpqebj)fcvlrdolrmtfqelqebomi^vbopalfkdqefpnrbpqfqtfii_bJR@EC>PQBOyyRy1/146yyNFAy./661yyWyQebPqlojMb^hpyyAy
@MlifpefkdqebEbijyKyBkqboEf_bok^i@^sboktbpqlcArkKfccbibj%22+3)3/+6&^ka`liib`q2rkfqplcXSfp`lrpLfiZcoljqebSfp`lrpLfipqebob+yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
@QeorpqfkdElafo$pPmb^oyRy1/436yyLyyKyFcvlr$obqovfkdqefpcloqeb.pqqfjbq^hblcc^iivlro^ojlofk`^pbvlrafb+RpbXPmb^olcElafoZlk^TfiaTvoj+Lk`bjlrkqbahbbmmobppfkd.^ka0)tebkvlrdbqqeb$`i^tt^okfkd$mobpp/qlaladbqebmobpp1+Fkqebkbuqme^pb)mobpp.rkqfivlrpq^`h^qib^pq.-$Mov$^ka^qqbjmqqlhfiifq_vmobppfkd/)fcfqc^fiphbbmmobppfkd.rkqfi/_b`ljbp^s^fi^_ib^d^fk+yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
@?iltfkdElafo$pElokyKyHfii2KfccbibjClobc^qebop^ka2ObpqibppColpq_lok^qQerkaboc^ii%4.)2/&QebkrpbXElafo$pElokZlsboqebfo`lompbpyyRy1/.31yyNFAy./644yyWyQebPqlojMb^hpyyAy
H?ofqqibObsbk^kqyKyHfii?ofqqibObsbk^kq^ka`liib`q3XBppbk`blcF`bZ%4-)26&yyIy1//133yyWyQebPqlojMb^hpy
@Elq^ka@liayKyillhcloQfkv_i^`hqefkdptfqepjlhb`ljfkdrmcoljqebj%41)3/&Qebv^obb^pfboqlpmlqfkqebpklt+Dbqkb^olkb)rpb^kXBppbk`blcF`bZ)qebkofdeq*`if`hillqqebjbq^ip`o^m+Alqefprkqfivlre^sb2yyRy1//13yyNFAy./65.yyWyQebPqlojMb^hpyyAy

QElq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWyQebPqlojMb^hpyyAy
Q?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWyQebPqlojMb^hpyyAy
QMlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
QPmvErkqboyLyyKyColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyWyQebPqlojMb^hpyyAy
QQeorpqfkdElafo$pPmb^oyLyyKyElafo$pPmb^o%32)3-+6&yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
QCbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyWyQebPqlojMb^hpyyAy

C>odbkqQlrok^jbkqDolrkapyKyrpbE^isa^k%3/+4)3-+6&yyWyQebPqlojMb^hpy

KMf`hrm1S^if^kqNrbpqpyKyMf`hrm0NrbpqpfkPrkob^sbopM^sfiflk%43+0)/1+1&$>S^if^kq$pCfbiaQo^fkfkd$)$QebDo^kaJbibb$)^ka$>qqebBkbjvpD^qbp$yyWyF`b`oltky
ePrkob^sboM^sfiflkyKyJ^hbprobvlropbqvlroeb^oqepqlkbql>odbkqQlrok^jbkqDolrkapG^ofkA^tkdilt%43+.)/1&yyWyF`b`oltky

>>?i^abCfqClo>@e^jmflkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0450yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0445yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.043/yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0440yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0435yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0452yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.045-yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0431yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0442yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyWri$qlob%43)/1+2&)A^fivyyNFAy.044-yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0451yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0446yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0430yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0441yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0436yyLyyWyF`b`oltkyyAy

>>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

>QebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy

>>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmXEloabI^k`bZ^kadbq^Jlrkq%42+3)/0+3&lo%4.+52)/-&yyRy13-4-yyWyF`b`oltky
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0454yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.045/yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0434yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0444yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQebEloab$pS^if^kqOfkd%42+0)/2+6&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.044/yyLyyWyF`b`oltkyyAy

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
>Ao^d^kaAolmyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0020yyWyF`b`oltkyyAy
>Klq^?rdyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0032yyWyF`b`oltkyyAy
>Qe^q$p>_ljfk^_ibyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0/43yyWyF`b`oltkyyAy
>Hbbmfkdqeb>iif^k`b?ifkayKyPhv*Ob^sboHloj?i^`hp`^olkLodofj$pE^jjboyyNFAy.000.yyWyF`b`oltkyyAy
>Pi^sbpqlP^olkfqbyKy?olqeboHbiq^klkLodofj$pE^jjboyyNFAy.00-/yyWyF`b`oltkyyAy
>?illalcqeb@elpbkyKyT^o_ofkdboA^slpOfleqlkLodofj$pE^jjboyyNFAy.000-yyWyF`b`oltkyyAy
>Sli^qfifqvyKy@efbcBkdfkbbo@lmmbo`i^tlkLodofj$pE^jjboyyNFAy.0/3.yyWyF`b`oltkyyAy
>ObqbpqKltyKy@efbcBkdfkbbo@lmmbo`i^tlkLodofj$pE^jjboyyNFAy.0024yyWyF`b`oltkyyAy

>>pp^riq_vDolrkayKyHlo$holkPnr^aIb^abo%25+0)13+.&yyNFAy.00-.yyWyF`b`oltkyyAy
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.00-.yyWyF`b`oltkyyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.000-yyWyF`b`oltkyyAy
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00-.yyWyF`b`oltkyyAy

>>pp^riq_v>foyKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00.-yyWyF`b`oltkyyAy
@>pp^riq_v>foyKyDlql%26+3)13+-&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00.-yyWyF`b`oltkyyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00.-yyWyF`b`oltkyyAy

>HfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWyF`b`oltkyyAy
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21+51)3-+.1&yyNFAy.0/50yyWyF`b`oltkyyAy
QHfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWyF`b`oltkyyAy
@Pi^sbpqlP^olkfqbyKyDlqlqebP^olkfqbJfkbp%23)24&)pfjmivq^ihqlqebP^olkfqbJfkbPi^sbpfkqebjfkb)vlre^sb^`e^k`bqe^qqebvtfiiorklrqlcqebjfkb^kadfsbvlrnrbpq`obafq)loqrokelpqfiblkvlryyNFAy.00-/yyWyF`b`oltkyyAy

@Ao^d^kaAolmyKyDlPlrqelcqeb_ofadb^olrka%20)13&)hfiiqebjl_pqebobcloqebLo_lcFiirpflknrbpqfqbjvlrkbba)qebkqeoltfq^qqebA^ohPr_grd^qlopcolj^afpq^k`btefiblrqlc`lj_^q+yyRy11/13yyNFAy.0020yyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%2-+/)10+4&yyWyF`b`oltkyyNFAy.0453yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%2-+/)10+4&yyWyF`b`oltkyyNFAy.045.yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%2-+/)10+4&yyWyF`b`oltkyyNFAy.0432yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%2-+/)10+4&yyWyF`b`oltkyyNFAy.0443yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%2-+/)10+4&yyWyF`b`oltkyyNFAy.044.yyLyyWyF`b`oltkyyAy

RAofkhRmyKyRpbXAfirqba@riqQlkf`ZcloqebnrbpqObqbpqKltyyRy110-4yyWyF`b`oltky
HHfii@riqKM@pyKyHfii@riqKM@p%16)00&^ka`liib`q.-uXQ^fkqbaBppbk`bZyyIy110-..-yyWyF`b`oltky
R@ob^qbXTofqefkdJ^ppZyKyOfdeq`if`hlkXQ^fkqbaBppbk`bZyyRy110-.yyWyF`b`oltky
@ObqbpqKltyKyRpbqebXQ^fkqbaBppbk`bZql`lj_fkbaqebjfkql^XTofqefkdJ^ppZ^karpbfqlk^`^riaolk^q%16)01&)A^oh@^riaolk7>qq^`hMltbo)?irb@^riaolk7Pmbiimltbo)Dobbk@^riaolk7Pq^jfk^yyRy110-1yyNFAy.0024yyWyF`b`oltkyyAy
HBkpi^sbaJfkflkpyKyHfiiBkpi^sbaJfkflkp%22)/6&qebkrpbXOlalcPfmelkfkdZql`liib`q2uXA^ohJ^qqboZyyRy11100yyIy111012yyWyF`b`oltky
@Klq^?rdyKyLk`bvlre^sb`liib`qba2uXA^ohJ^qqboZofdeq`if`hlkqebMromibPrjjlkfkdPqlkb^q%20+4)00+3&yyNFAy.0032yyWyF`b`oltkyyAy

@Hbbmfkdqeb>iif^k`b?ifkayKyRpbXPDJ*0Zqlhfii3Phv_ob^hboOb`lk^olrka%14+0)1-&)fqfpb^pvfcvlr`ob^qb^j^`olcloqefp),q^odbqPhv_ob^hboOb`lkXefqbkqboZ,`^pqPDJ*0yyRy11/./yyNFAy.000.yyWyF`b`oltkyyAy

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%10+.)/1+/&yyWyF`b`oltky
>SfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWyF`b`oltkyyAy
>Pellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWyF`b`oltkyyAy
>Ib^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWyF`b`oltkyyAy
@Pellq$BjRmyKyDlql%0/)/1&^ka`ellpblkblcqebe^omllkp+Vlrkbbaqlt^fqrkqfiqebao^dlkpcivsbovkb^o)fcvlrkbbajlobqe^k{2pelqp^kaqebvalk$qafbqe^qjb^kpqe^qqebv^obk$qkb^obklrde+Alkqqovqlpellqqeblkbptef`e^obc^o^t^v)vlr`^k$qhfiiqebj+yyNFAy.0-36yyWyF`b`oltkyyAy
@Ib^sbLroJ^ohyKyHfiiqebSvhrip%0-)/5&^karpbXB_lk?i^ab?^kkboZlkqeb`lompbpyyRy1/15-yyNFAy./662yyWyF`b`oltkyyAy
@SfibIfhbCfobyKyDlql%/4)06&^kajlrkq^Ao^hb)^ka_rokqeb_rfiafkdpfkqeb^ob^yyNFAy.0-4.yyWyF`b`oltkyyAy
QPellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWyF`b`oltkyyAy
QSfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWyF`b`oltkyyAy
QIb^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWyF`b`oltkyyAy

C@orp^abop$Mfkk^`ibyKyCivql@orp^abop$Mfkk^`ib)rpbJloif^Alljtfkd%10+4)/1+1&yyWyF`b`oltky

@Qe^q$p>_ljfk^_ibyKyHfii^Erihfkd>_ljfk^qflk%35)30&^ka`liib`q^X@efiiba>_ljfk^qflkDrqpZqebkrpbqebX>_ljfk^qflkOb^kfj^qflkHfqZqlprjjlk^k>_ljfk^qflkrpbfqql_iltrmqebdelrip+Alk$qbumilabtefibqebdelrip^obpqrkkbalobipbvlrtlk$qdbq^kv`obafq+Vlr`^k^iplqovjlrkqfkdrm^cqboprjjlkfkdqeb>_ljfk^qflkyyNFAy.0/43yyRy10635yyWyF`b`oltkyyAy
@Sli^qfifqvyKyMf`hrmqeb0l_gb`qpp`^qqboba^olrkaqeb^ob^%36)33&XMfiblc?lkbpZ)X>_^kalkbaEbijZ)^kaX>_^kalkba>ojloZ)dbq0lcb^`elcqebj^kaqebkrpbqebX@lmmbo`i^t$pSli^qfibLfiZnrbpqfqbj0qfjbp+yyRy103-5yyNFAy.0/3.yyWyF`b`oltkyyAy

@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0526yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.053-yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0523yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0525yyLyyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyNFAy.0524yyLyyWyF`b`oltkyyAy

@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0450yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0445yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.043/yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0440yyLyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyWyDofwwivEfiipyyNFAy.0435yyLyyAy
KQebBadbLcTfkqboyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$QebBadbLcTfkqbo$CfkaIloaBsbo_i^wb^olrka%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZqebkqf`hqefpl_gb`qfsbyyIy12--2yyWy@ovpq^iplkdClobpqy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0452yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.045-yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0431yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0442yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.044-yyLyyAy
K>TloqevTb^mlkyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$>TloqevTb^mlk$@liib`q1XTfkqboEv^`fkqeZ^olrka%4.)41+2&fkF`b`oltkqebkqf`hqefpl_gb`qfsbyyIy12---1yyWyF`b`oltky
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0451yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0446yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0430yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0441yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0436yyLyyAy

EPrkob^sboM^sfiflkyRy3615y

Q>S^if^kq$pCfbiaQo^fkfkdyKyHbqefbiPrki^k`b%43+12)/0+53&)A^fivyyNFAy.0453yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyP^o^e@e^ihb%43+2)/1+/&)A^fivyyNFAy.045.yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKy>hfklp%43+1)/1+3&)A^fivyyNFAy.0432yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyAbokO^dbqlqbj%43+/)/1+3&)A^fivyyNFAy.0443yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyPe^altErkqboJbwfi*hobb%43)/1+2&)A^fivyyNFAy.044.yyLyyWyF`b`oltkyyAy

QQebDo^kaJbibbyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0454yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.045/yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0434yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0444yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyD^egr%43)/1+2&)A^fivyyNFAy.044/yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kbbo^Qerolk%43+12)/0+53&)A^fivyyNFAy.0526yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyE^kaiboAobq`e%43+2)/1+/&)A^fivyyNFAy.053-yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyJlo^eTlodpfpqbo%43+1)/1+3&)A^fivyyNFAy.0523yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>kh^@i^tellc%43+/)/1+3&)A^fivyyNFAy.0525yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyD^egr%43)/1+2&)A^fivyyNFAy.0524yyLyyWyF`b`oltkyyAy

Q>?i^abCfqClo>@e^jmflkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0450yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0445yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.043/yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0440yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0435yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0452yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.045-yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0431yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0442yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyWri$qlob%43)/1+2&)A^fivyyNFAy.044-yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyBobppb^A^tkpfkdbo%43+12)/0+53&)A^fivyyNFAy.0451yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyAb^qepq^ihboSfp`bof%43+2)/1+/&)A^fivyyNFAy.0446yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyJlho^qebPhrii`orpebo%43+1)/1+3&)A^fivyyNFAy.0430yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyOrklhTfiaj^kb%43+/)/1+3&)A^fivyyNFAy.0441yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyWri$qlob%43)/1+2&)A^fivyyNFAy.0436yyLyyWyF`b`oltkyyAy

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
QAo^d^kaAolmyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0020yyWyF`b`oltkyyAy
QKlq^?rdyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0032yyWyF`b`oltkyyAy
QQe^q$p>_ljfk^_ibyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0/43yyWyF`b`oltkyyAy
QHbbmfkdqeb>iif^k`b?ifkayKyPhv*Ob^sboHloj?i^`hp`^olkLodofj$pE^jjboyyNFAy.000.yyWyF`b`oltkyyAy
QPi^sbpqlP^olkfqbyKy?olqeboHbiq^klkLodofj$pE^jjboyyNFAy.00-/yyWyF`b`oltkyyAy
Q?illalcqeb@elpbkyKyT^o_ofkdboA^slpOfleqlkLodofj$pE^jjboyyNFAy.000-yyWyF`b`oltkyyAy
QSli^qfifqvyKy@efbcBkdfkbbo@lmmbo`i^tlkLodofj$pE^jjboyyNFAy.0/3.yyWyF`b`oltkyyAy
QObqbpqKltyKy@efbcBkdfkbbo@lmmbo`i^tlkLodofj$pE^jjboyyNFAy.0024yyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
