DugisGuideViewer:RegisterGuide("Venomhide Ravasaur Quest and Dailies (50+)", nil, "Horde", "D", function()
return [[
AAA

KIltIbsbiNrbpqyKyFcvlr^obfkvlro4-$plo^q5-)qefpnrbpqtfii_b^iltibsbinrbpqclovlr)qroklkvlroiltibsbinrbpqqo^`hfkdql_b^_ibqlpbbqebnrbpqlkvlrojfkfj^my

>Qluf`Qlibo^k`byKyJlo$sbh%4.+2)40+1&yyNFAy.052-yyWyRk$Dlol@o^qboy
@Qluf`Qlibo^k`byKyDbqpmi^peba_vSbkljefabO^s^p^ro_illa/-qfjbp+>qq^`hSbkljefabO^s^p^rop%33+0)2.+2&clo^`e^k`bql_bmlfplkba+Jrpq?bSbkljefabO^s^p^rop+yyNFAy.052-yyWyRk$Dlol@o^qboy
QQluf`Qlibo^k`byKyJlo$sbh%4.+2)40+1&yyNFAy.052-yyWyRk$Dlol@o^qboy

>SbkljefabBddpyKyJlo$sbh%4.+2)40+1&yyNFAy.0554yyWyRk$Dlol@o^qboy
@SbkljefabBddpyKy?ofkd1SbkljefabO^s^p^roBddp%3.+2)25+-&%35+3)21+1&%4.+2)3-+-&%34+-)3/+4&%30+6)3/+6&3.+-)4/+0&qlJlo$sbhfkqebplrqeb^pqm^oqlcqebJ^opei^kap+yyNFAy.0554yyWyRk$Dlol@o^qboy
QSbkljefabBddpyKyJlo$sbh%4.+2)40+1&yyNFAy.0554yyWyRk$Dlol@o^qboy

>QebvDoltRmPlC^pqyKyJlo$sbh%4.+2)40+1&yyNFAy.06-3yyWyRk$Dlol@o^qboy

RSbkljefabE^q`eifkdyKyPrjjlkvlroSbkljefabE^q`eifkd+@^klkiv_bprjjlkbafkRk$Dlol@o^qbo)Q^k^ofp)loPfifqerp+yyRy1303/y
K>``bmqqebA^fivyKy>``bmqqebA^fivNrbpqcoljvlroSbkljefabe^q`eifkd+y
>Pb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06-2yyAy
>Pb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06.1yyAy
>Erkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.06.2yyAy
>Erkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.0556yyAy
>Ml^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyNFAy.06.3yyAy
>Ml^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyNFAy.06-1yyAy
>DlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06.4yyAy
>DlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06-0yyAy

@Pb^ofkdOl`Cb^qebopyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqldbq2mfb`bplcPb^ofkdOl`Mirj^db%04+.)35+6&%1.+2)31+3&%0.+6)3-+6&+yyWyQ^k^ofpyyNFAy.06-2yyAy
@Pb^ofkdOl`Cb^qebopyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqldbq2mfb`bplcPb^ofkdOl`Mirj^db%04+.)35+6&%1.+2)31+3&%0.+6)3-+6&+yyWyQ^k^ofpyyNFAy.06.1yyAy
@Erkdov)ErkdovE^q`eifkdyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.2mfb`bplcCobpeAfklp^roJb^q+HfiiAfklp^ropfkRk$dlol@o^qbocloqebjb^q%00+5)33+2&%0/+4)04+5&%22+-)3/+.&+yyWyRk$Dlol@o^qboyyNFAy.06.2yyAy
@Erkdov)ErkdovE^q`eifkdyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.2mfb`bplcCobpeAfklp^roJb^q+HfiiAfklp^ropfkRk$dlol@o^qbocloqebjb^q%00+5)33+2&%0/+4)04+5&%22+-)3/+.&+yyWyRk$Dlol@o^qboyyNFAy.0556yyAy
@Ml^`eba)P`o^j_iba)LoO^t<yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq./PfifqefaBddp+Qebbddp`^k_bclrka^iilsboQebKluflrpI^fo%00+3)06+2&yyWyQ^k^ofpyyNFAy.06.3yyAy
@Ml^`eba)P`o^j_iba)LoO^t<yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq./PfifqefaBddp+Qebbddp`^k_bclrka^iilsboQebKluflrpI^fo%00+3)06+2&yyWyQ^k^ofpyyNFAy.06-1yyAy
@DlofpefDor_yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.-PfifqefaJb^q+HfiiPfifqefap^qqebPifqebofkdP`^o%2-+1)45+5&yyWyRk$Dlol@o^qboyyNFAy.06.4yyAy
@DlofpefDor_yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.-PfifqefaJb^q+HfiiPfifqefap^qqebPifqebofkdP`^o%2-+1)45+5&yyWyRk$Dlol@o^qboyyNFAy.06-0yyAy

QPb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06-2yyAy
QPb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06.1yyAy
QErkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.06.2yyAy
QErkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.0556yyAy
QMl^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyyNFAy.06.3yyAy
QMl^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyyNFAy.06-1yyAy
QDlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06.4yyAy
QDlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06-0yyAy

KSbkljefab?^_vQllqeyKyTebkvlre^sb`liib`qba/-XSbkljefab?^_vQllqeZ)qebk`ljmibqbqebi^pqnrbpqqldbqvlroO^s^p^ro+y

@QebvDoltRmPlC^pqyKy/-XSbkljefab?^_vQbbqeZ)qebSbkljefabE^q`eifkd)/-XOrkb`ilqeZ)/-XOrddbaIb^qeboZ)^ka5-dliaqlJlo$sbhRk$Dlol@o^qbo+yyNFAy.06-3yyWyRk$Dlol@o^qboy
QQebvDoltRmPlC^pqyKyJlo$sbh%4.+2)40+1&yyNFAy.06-3yyWyRk$Dlol@o^qboy

KDrfab@ljmibqb
]]
end)
