DugisGuideViewer:RegisterGuide("Children's Week (10+ Azeroth)", nil, "Alliance", "D", function()
return [[
AAA

CPqlojtfka@fqv
>@efiaobk$pTbbhyKyLome^kJ^qolkKfdeqfkd^ib%23+0)21+/&yyNFAy.135yyWyPqlojtfka@fqvy
RXErj^kLome^kTefpqibZyKyRpbqebXErj^kLome^kTefpqibZql`^iiqeblome^kyyRy.5265yyWyPqlojtfka@fqvy
Q@efiaobk$pTbbhyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyRy.5265yyNFAy.135yyWyPqlojtfka@fqvy

>PmllhvIfdeqelrpbyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy.354yyWyPqlojtfka@fqvy
>QebPqlkbtolrdeqA^jyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy.225yyWyPqlojtfka@fqvy
>Qeb?lrdelcqebBqbok^ipyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy.146yyWyPqlojtfka@fqvy

CTbpqc^iiyKyCivqlTbpqc^iiy
@PmllhvIfdeqelrpbyKyDlqlqebpmlq^q%/6)53&^karpbXErj^kLome^kTefpqibZyyRy.5265yyNFAy.354yyWyTbpqc^iiy
QPmllhvIfdeqelrpbyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy.354yyWyTbpqc^iiy

CIl`eJla^kyKyCivqlIl`eJla^ky
@QebPqlkbtolrdeqA^jyKyDlqlqeba^j^q%15)./&^karpbXErj^kLome^kTefpqibZyyRy.5265yyNFAy.225yyWyIl`eJla^ky
QQebPqlkbtolrdeqA^jyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy.225yyWyIl`eJla^ky

CA^ok^pprpyKyCivqlA^ok^pprpy
@Qeb?lrdelcqebBqbok^ipyKyDlqlqeb_^khfkA^ok^pprp%1-)1/&^karpbXErj^kLome^kTefpqibZyyRy.5265yyNFAy.146yyWyA^ok^pprpy
QQeb?lrdelcqebBqbok^ipyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy.146yyWyA^ok^pprpy

>VlrP`ob^j)FP`ob^j+++yKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy15//yyWyA^ok^pprpy
>G^fk^$p>rqldo^meyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy225yyWyA^ok^pprpy

CQebo^jlobFpibyKyCivqlQebo^jlobFpiby
@G^fk^$p>rqldo^meyKyPmb^hqlI^avG^fk^Molrajllob%33+0)16+.&fkQebobjlobFpib^kadbqebo>rqldo^meyyNFAy225yyWyArpqt^iiltJ^opey
QG^fk^$p>rqldo^meyKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyRy.5265yyNFAy225yyWyArpqt^iiltJ^opey

_JbkbqefiE^o_loyKyQ^hbqeb_l^qqlJbkbqefiE^o_locoljQebo^jlobfpiby
CPqlojtfka@fqvyKyCivqlPqlojtfka@fqvy
??rvXQfdrib^kaClolo$pPqo^t_boovF`b@ob^jZyKy?rvXQfdrib^kaClolo$pPqo^t_boovF`b@ob^jZcoljBjjfqerbPj^fip%3.+0)42&yyWyPqlojtfka@fqvyyIy4//5y
RXErj^kLome^kTefpqibZyKyRpbqebXErj^kLome^kTefpqibZql`^iiqeblome^kyyRy.5265yyWyPqlojtfka@fqvy
QVlrP`ob^j)FP`ob^j+++yKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyNFAy15//yyWyPqlojtfka@fqvy

>>T^oabklcqeb>iif^k`byKyQ^ihqlqebErj^kLome^kqe^qvlrprjjlktfqeXErj^kLome^kTefpqibZyyRy.5265yyNFAy.4.yyWyPqlojtfka@fqvy
Q>T^oabklcqeb>iif^k`byKyLome^kJ^qolkKfdeqfkd^ib%23+0)21+/&yyNFAy.4.yyWyPqlojtfka@fqvy

KDrfab@ljmibqb
]]
end)
