DugisGuideViewer:RegisterGuide("Children's Week (70+ Northrend Oracles)", nil, "Alliance", "D", function()
return [[
AAA

CA^i^o^k
>IfqqibLome^kOllLcQebLo^`ibpyKyQ^ihqlLome^kJ^qolk>of^%16+0)30+0&yyWyA^i^o^kyyNFAy.06/3y
RXLo^`ibLome^kTefpqibZyKyRpbqebXLo^`ibLome^kTefpqibZql`^iiqeblome^kyyRy13064yyWyA^i^o^ky
@IfqqibLome^kOllLcQebLo^`ibpyKyQ^ihqlLome^kJ^qolk>of^%16+0)30+0&yyNFAy.06/3yyWyA^i^o^ky
QIfqqibLome^kOllLcQebLo^`ibpyKyQ^ihqlOllyyNFAy.06/3yyWyA^i^o^ky

>Qeb?fddbpqQobbBsboyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyNFAy.06/6yyWyA^i^o^ky
>Qeb?olkwbAo^dlkpeofkbyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyNFAy.0600yyWyA^i^o^ky
>Mi^vj^qbpyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyNFAy.062-yyWyA^i^o^ky

CDofwwivEfiipyKyCivqlDofwwivEfiipy
@Qeb?fddbpqQobbBsboyKyCivqlqebplrqebokbkqo^k`blcDofwwibj^t%2-+1)12+6&)`^iiOll)qebkt^ih^ilkdqebdolrkaqlqebfkqboflo+Fqtfiimol_^_iv_bkb`bpp^ovqlhfiipljbkb^o_vObac^kdqle^sbbklrdeolljqlt^ihfkyyRy13064yyNFAy.06/6yyWyDofwwivEfiipy
QQeb?fddbpqQobbBsboyKyQ^ihqlqebLome^kOllyyRy13064yyNFAy.06/6yyWyDofwwivEfiipy

CAo^dlk_ifdeqyKyCivqlAo^dlk_ifdeqy
@Qeb?olkwbAo^dlkpeofkbyKyCivqlqebpqbmp^qqebplrqetbpqbokbkalcqebpeofkb%4/)06&)`^iiOll)qebkt^ihaltkqebpqbmpqlt^oapqebpeofkbmolmbyyRy13064yyNFAy.0600yyWyAo^dlk_ifdeqy
QQeb?olkwbAo^dlkpeofkbyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0600yyWyAo^dlk_ifdeqy

C?lob^kQrkao^yKyCivql?lob^kQrkao^y
@Mi^vj^qbpyKyCivaltkqlqebTfkqbocfkObqob^q+I^kapljbtebobkb^oHfkdJodi*Jodi%10+2).0+6&^kaprjjlkOllfceb$pklq^iob^avlrq+yyRy13064yyNFAy.062-yyWy?lob^kQrkao^y
QMi^vj^qbpyKyQ^ihqlqebLome^kOllyyRy13064yyNFAy.062-yyWy?lob^kQrkao^y

>Jbbqfkd^Dob^qLkbyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0623y
>QebAo^dlkNrbbkyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0621y
CPeli^w^o?^pfkyKyCivPeli^w^o?^pfkyyWyPeli^w^o?^pfky
ORk$Dlol@o^qboyKyRpbqebT^vd^qb%1-)5/&qldbqqlPe^mbo$pQboo^`byyWyPeli^w^o?^pfky
@Jbbqfkd^Dob^qLkbyKySfpfqqebBqvjfaf^k^qqebPe^mbo$pQboo^`bfkRk$Dlol@o^qbo%14+1)6+/&yyRy13064yyNFAy.0623yyWyRk$Dlol@o^qboy
QJbbqfkd^Dob^qLkbyKySfpfqqebBqvjfaf^k^qqebPe^mbo$pQboo^`bfkRk$Dlol@o^qboyyRy13064yyNFAy.0623y

CAo^dlk_ifdeqyKyCivqlAo^dlk_ifdeqy
@QebAo^dlkNrbbkyKySfpfq>ibupqo^pw^qebIfcb*?fkabo%16+5)21+3&^qqebqlmlcTvojobpqQbjmibyyRy13064yyNFAy.0621yyWyAo^dlk_ifdeqy
QQebAo^dlkNrbbkyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0621yyWyAo^dlk_ifdeqy

>>QofmQlQebTlkabotlohpyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0604y
CA^i^o^kyKyCivloEb^oqe_^`hqlA^i^o^ky
?XPj^iiM^mboWbmmbifkZyKy?rv^XPj^iiM^mboWbmmbifkZcoljqebTlkabotlohp%11)13&yyIy13360yyWyA^i^o^ky
@>QofmQlQebTlkabotlohpyKyRpbXPj^iiM^mboWbmmbifkZtfqevlroLome^klrqyyRy13360yyNFAy.0604y
Q>QofmQlQebTlkabotlohpyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0604y

>?^`hQlQebLome^k^dbyKyQ^ihqlqebLome^kOllqe^qvlrprjjlktfqeXLo^`ibLome^kTefpqibZyyRy13064yyNFAy.0626y
Q?^`hQlQebLome^k^dbyKyQ^ihqlLome^kJ^qolk>of^%16+0)30+0&yyNFAy.0626yyWyA^i^o^ky

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj
]]
end)
