DugisGuideViewer:RegisterGuide("Children's Week (60+ Outland)", nil, "Alliance", "D", function()
return [[
AAA

CPe^qqo^qe@fqv
>@efiaobk$pTbbhyKyLome^kJ^qolkJbo`v%42)15&yyNFAy.-610yyWyPe^qqo^qe@fqvy
RXAo^bkbfLome^kTefpqibZyKyRpbqebXAo^bkbfLome^kTefpqibZql`^iiqeblome^kyyRy0.55.yyWyPe^qqo^qe@fqvy
Q@efiaobk$pTbbhyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyRy0.55.yyNFAy.-610yyWyPe^qqo^qe@fqvy

>Gebbifp^q>bofpI^kafkdyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-621yyWyPe^qqo^qe@fqvy
>>r`efkalrk^kaqebOfkdlcL_pbos^k`byKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-62-yyWyPe^qqo^qe@fqvy
>>QofmqlqebA^ohMloq^iyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-62/yyWyPe^qqo^qe@fqvy

CK^do^kayKyCivqlK^do^kay
@Gebbifp^q>bofpI^kafkdyKyDlqlGebbi%0.+.)24+/&fkK^do^ka+prjjlkqebLome^kyyRy0.55.yyNFAy.-621yyWyK^do^kay
QGebbifp^q>bofpI^kafkdyKyGebbi%0.+.)24+/&yyRy0.55.yyNFAy.-621yyWyK^do^kay

CQbolhh^oClobpqyKyCivqlQbolhh^oClobpqy
@>r`efkalrk^kaqebOfkdlcL_pbos^k`byKyDlql>r`efkalrkjbbqfkdpqlkb%06+5)31+4&fkQbolhh^oClobpq^karpbXAo^bkbfLome^kTefpqibZyyRy0.55.yyNFAy.-62-yyWyQbolhh^oClobpqy
Q>r`efkalrk^kaqebOfkdlcL_pbos^k`byKyE`e$rr%.5+4)2.+.&fkPmlobd^ooyyRy0.55.yyNFAy.-62-yyWyQbolhh^oClobpqy

CEbiicfobMbkfkpri^yKyCivqlEbiicfobMbkfkpri^y
@>QofmqlqebA^ohMloq^iyKyPq^ka^olrka%55)2-&^qqebqlmlcqebpq^fopfk)fkqebjfaaibqfibfkcolkqlcqebA^ohMloq^i^karpbXAo^bkbfLome^kTefpqibZyyRy0.55.yyNFAy.-62/yyWyEbiicfobMbkfkpri^y
Q>QofmqlqebA^ohMloq^iyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-62/yyWyEbiicfobMbkfkpri^y

>QebPb^qlcqebK^^oryKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-623yyWyEbiicfobMbkfkpri^y

CPe^qqo^qe@fqvyKyDl_^`hqlPe^qqo^qe@fqvy
OQebBula^oyKyQ^hbqebmloq^iqlQebBula^oy
@QebPb^qlcqebK^^oryKyDlqlL$olp%24)1-&^kaprjjlkXAo^bkbfLome^kTefpqibZyyRy0.55.yyNFAy.-623yyWyQebBula^oy
QQebPb^qlcqebK^^oryKyL$olp%24)1-&yyNFAy.-623yyWyQebBula^oy
>@^iilkqebC^opbboyKyL$olp%24)1-&yyNFAy.-635yyWyQebBula^oy
@@^iilkqebC^opbboyKyDlqlC^opbboKl_rkal%0-)0-&yyNFAy.-635yyRy0.55.yyWyQebBula^oy
Q@^iilkqebC^opbboyKyC^opbboKl_rkal%0-)0-&yyNFAy.-635yyWyQebBula^oy

>QfjbqlSfpfqqeb@^sbokpyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-63/yyWyQebBula^oy

CD^adbqw^kyKyCivqlD^adbqw^kfkQ^k^ofpy
KQ^ihqlPqbt^oalcQfjbyKyQ^ihqlPqbt^oalcQfjb%33)16)4&^kaq^hbqebcifdeqaltkql@^sboklcQfjbyyWyQ^k^ofpy
?XQlvAo^dlkZyKy?rvXQlvAo^dlkZcolj>irojf%30+3)24+3&yyWyQ^k^ofpyyIy0.62.y
@QfjbqlSfpfqqeb@^sbokpyKyDlqlW^i^alojr%3-+1)24+1&^kaprjjlkXAo^bkbfLome^kTefpqibZyyRy0.55.yyNFAy.-63/yyWyQ^k^ofpy
QQfjbqlSfpfqqeb@^sbokpyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-63/yyWyQ^k^ofpy

>?^`hqlqebLome^k^dbyKyQ^ihqlqebAo^bkbfLome^kqe^qvlrprjjlktfqeXAo^bkbfLome^kTefpqibZyyNFAy.-633yyWyQ^k^ofpy
EPe^qqo^qe@fqvyRy3615y
Q?^`hqlqebLome^k^dbyKyLome^kJ^qolkJbo`v%42)15&yyNFAy.-633yyWyPe^qqo^qe@fqvy

KDrfab@ljmibqb
]]
end)
