DugisGuideViewer:RegisterGuide("Children's Week (70+ Northrend Frenzyheart)", nil, "Alliance", "D", function()
return [[
AAA

CA^i^o^k
>IfqqibLome^kHbhbhLcQebTlis^oyKyQ^ihqlLome^kJ^qolk>of^%16+0)30+0&yyWyA^i^o^kyyNFAy.06/4y
RXTlis^oLome^kTefpqibZyKyRpbqebXTlis^oLome^kTefpqibZql`^iiqeblome^kyyRy13063yyWyA^i^o^ky
@IfqqibLome^kHbhbhLcQebTlis^oyKyQ^ihqlLome^kJ^qolk>of^%16+0)30+0&yyNFAy.06/4yyWyA^i^o^ky
QIfqqibLome^kHbhbhLcQebTlis^oyKyQ^ihqlHbhbhyyNFAy.06/4yyWyA^i^o^ky

>EljbLcQeb?b^o*JbkyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyNFAy.060-yyWyA^i^o^ky
>Qeb?olkwbAo^dlkpeofkbyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyNFAy.0601yyWyA^i^o^ky
>Mi^vj^qbpyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyNFAy.062.yyWyA^i^o^ky

CDofwwivEfiipyKyCivqlDofwwivEfiipy
@EljbLcQeb?b^o*JbkyKyCivqlqebplrqebokbkqo^k`blcDofwwibj^t%2-+1)12+6&)`^iiHbhbh)qebkt^ih^ilkdqebdolrkaqlqebfkqboflo+Fqtfiimol_^_iv_bkb`bpp^ovqlhfiipljbkb^o_vObac^kdqle^sbbklrdeolljqlt^ihfkyyRy13063yyNFAy.060-yyWyDofwwivEfiipy
QEljbLcQeb?b^o*JbkyKyQ^ihqlqebLome^kHbhbhyyRy13063yyNFAy.060-yyWyDofwwivEfiipy

CAo^dlk_ifdeqyKyCivqlAo^dlk_ifdeqy
@Qeb?olkwbAo^dlkpeofkbyKyCivqlqebpqbmp^qqebplrqetbpqbokbkalcqebpeofkb%4/)06&)`^iiHbhbh)qebkt^ihaltkqebpqbmpqlt^oapqebpeofkbmolmbyyRy13063yyNFAy.0601yyWyAo^dlk_ifdeqy
QQeb?olkwbAo^dlkpeofkbyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.0601yyWyAo^dlk_ifdeqy
@Mi^vj^qbpyKyQ^hbvlrolome^k)Hbhbh)qlsfpfqPkltc^iiDi^ab%13+0)3.&J^hbprobql`^iiefjfcebfpklqmobpbkqtebkvlrdbqqebob+yyRy13063yyNFAy.062.yyWyAo^dlk_ifdeqy
QMi^vj^qbpyKyQ^ihqlqebLome^kHbhbhyyRy13063yyNFAy.062.yyWyAo^dlk_ifdeqy

>QebJfdeqvEbjbqKbpfkdt^ovyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.0624y
>QebAo^dlkNrbbkyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.0622y
@QebAo^dlkNrbbkyKySfpfq>ibupqo^pw^qebIfcb*?fkabo%16+5)21+3&^qqebqlmlcTvojobpqQbjmibyyRy13063yyNFAy.0622yyWyAo^dlk_ifdeqy
QQebAo^dlkNrbbkyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.0622yyWyAo^dlk_ifdeqy

CPeli^w^o?^pfkyKyCivPeli^w^o?^pfkyyWyPeli^w^o?^pfky
@QebJfdeqvEbjbqKbpfkdt^ovyKyQ^hbvlrolome^k)Hbhbh)qlsfpfqEbjbqKbpfkdt^ov^qqebKbpfkdt^ov?^pb@^jm%/3+6)26+2&yyRy13063yyNFAy.0624yyWyPeli^w^o?^pfky
QQebJfdeqvEbjbqKbpfkdt^ovyKySfpfqEbjbqKbpfkdt^ovfkPeli^w^o?^pfkyyRy13063yyNFAy.0624yyWyPeli^w^o?^pfky

>>QofmQlQebTlkabotlohpyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.0605y
CA^i^o^kyKyCivloEb^oqe_^`hqlA^i^o^ky
?XPj^iiM^mboWbmmbifkZyKy?rv^XPj^iiM^mboWbmmbifkZcoljqebTlkabotlohp%11)13&yyIy13360yyWyA^i^o^ky
@>QofmQlQebTlkabotlohpyKyRpbXPj^iiM^mboWbmmbifkZtfqevlroLome^klrqyyRy13360yyNFAy.0605y
Q>QofmQlQebTlkabotlohpyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.0605y

>?^`hQlQebLome^k^dbyKyQ^ihqlqebLome^kHbhbhqe^qvlrprjjlktfqeXTlis^oLome^kTefpqibZyyRy13063yyNFAy.063-y
Q?^`hQlQebLome^k^dbyKyQ^ihqlLome^kJ^qolk>of^%16+0)30+0&yyNFAy.063-yyWyA^i^o^ky

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj
]]
end)
