DugisGuideViewer:RegisterGuide("Pilgrim's Bounty Cooking 1-300", nil, "Alliance", "D", function() 
return [[
AAA

CPqlojtfka@fqvyKyDlqlPqlojtfka@fqvy

KIb^ok%Pmf`b?ob^a&yKySfpfqBiibkJllob%00+4)2-+4&qeb`llhfkdqo^fkbo^kaib^okqebob`fmb%Pmf`b?ob^a&qebkqf`hqefppqbmyyWyBitvkkClobpqy
K?rvX?lrkqfcri@llh_llhZyKyTfijfk^Eli_b`h%01+.)2.+2&yyIy135-6yyWyBitvkkClobpqy
R?lrkqfcri@llh_llhyKyLmbkqeb_llhyyRy135-6y

>Pmf`b?ob^aPqrccfkdyKyDobdlovQ^_lo%01+.)2.+2&yyNFAy.1-/0yyWyBitvkkClobpqy
K@llh%Pmf`b?ob^aPqrccfkd&Rkqfi++yKyHbbm`llhfkd%Pmf`b?ob^aPqrccfkd&rkqfivlrob^`eibsbi.--`llhfkdphfiiqlib^okqebkbuqob`fmb%MrjmhfkMfb&qebkqf`hqefppqbmy
K?rv2*5-XOfmbBitvkkMrjmhfkZyKy?rv2u%lo^olrka5-fcvlro`llhfkdphfii.--&XOfmbBitvkkMrjmhfkZcoljcoljqebMfidofj$p?lrkqvsbkalolrqpfablcPqlojtfka@fqv+_rv^_lrq/--fcvlrfkqbkalkalfkdqebA^fifbpi^qboy
@Pmf`b?ob^aPqrccfkdyKy@llh^ka_ofkd2XPmf`b?ob^aPqrccfkdZqlG^pmboJllob^qqebd^qbplcPqlojtfka@fqv+Alk$qclodbqqlj^hbprobvlre^sbib^okbaqebPmf`b?ob^aklk*pb^plk^iob`fmb+yyNFAy.1-/0y
QPmf`b?ob^aPqrccfkdyKyG^pmboJllob%00+6)2-+6&yyNFAy.1-/0yyWyBitvkkClobpqy

>MrjmhfkMfbyKyG^pmboJllob%00+6)2-+6&yyNFAy.1-/1yyWyBitvkkClobpqy
K@llh%MrjmhfkMfb&Rkqfi++yKyHbbm`llhfkd%Pmf`b?ob^aPqrccfkd&rkqfivlrob^`eibsbi.3-`llhfkdphfiiqlib^okqebkbuqob`fmb%@o^k_boov@erqkbv&qebkqf`hqefppqbmy
K?rv2*5-XQ^kdvTbqi^ka@o^k_boofbpZyKyTefibvlr^obpqfiifkArkJlolde)_bprobqlmro`e^pbQ^kdvTbqi^ka@o^k_boofbpcoljqebMfidofj$p?lrkqvsbkalolrqpfablC@fqvlcFolkclodb+_rv^_lrq/--fcvlrfkqbkalkalfkdqebA^fifbpi^qboy
O@fqvlcFolkclodbyKyOrkqlFolkclodby
@MrjmhfkMfbyKy@llh^ka_ofkd2mfb`bplcMrjmhfkMfbqlFp^^`>iiboqlklrqpfablC@fqvlcFolkclodb+yyNFAy.1-/1y
QMrjmhfkMfbyKyFp^^`>iiboqlk%33)05+1&yyNFAy.1-/1yyWyArkJloldey

>@o^k_boov@erqkbvyKyFp^^`>iiboqlk%33)05+1&yyNFAy.1-/5yyWyArkJloldey
K@llh%@o^k_boov@erqkbv&Rkqfi++yKyHbbm`llhfkd%@o^k_boov@erqkbv&rkqfivlrob^`eibsbi//-`llhfkdphfiiqlib^okqebkbuqob`fmb%@^kafbaPtbbqMlq^qlbp&qebkqf`hqefppqbmy
K?rv2*5-XQbiao^ppfiPtbbqMlq^qlZyKyTefibvlr^obpqfiifkQbiao^ppfi)_bprobqlmro`e^pb2u%lo^olrka5-fcvlro`llhfkdphfii//-&XQbiao^ppfiPtbbqMlq^qlZcoljqebMfidofj$p?lrkqvsbkalolrqpfablcA^ok^pprp+_rv^_lrq/--fcvlrfkqbkalkalfkdqebA^fifbpi^qboy
@@o^k_boov@erqkbvyKy@llh^ka_ofkd2pbosfkdplcX@o^k_boov@erqkbvZqlG^pmboJllob^qqebd^qbplcPqlojtfka@fqv++yyNFAy.1-/5y
OPqlojtfka@fqvyKyOrkqlPqlojtfka@fqvy
Q@o^k_boov@erqkbvyKyG^pmboJllob%00+6)2-+6&yyNFAy.1-/5yyWyBitvkkClobpqy

>@^kafbaPtbbqMlq^qlbpyKyG^pmboJllob%00+6)2-+6&yyNFAy.1-00yyWyBitvkkClobpqy
K@llh%@^kafbaPtbbqMlq^qlbp&Rkqfi++yKyHbbm`llhfkd%@^kafbaPtbbqMlq^qlbp&rkqfivlrob^`eibsbi/5-`llhfkdphfiiqlib^okqebkbuqob`fmb%@^kafbaPtbbqMlq^qlbp&qebkqf`hqefppqbmy
@@^kafbaPtbbqMlq^qlbpyKy@llh^ka_ofkd2X@^kafbaPtbbqMlq^qlZqlFp^^`>iiboqlklrqpfablcLodofjj^o+Tefibvlr^obpqfiifkJridlobyyNFAy.1-00y
CA^ok^pprpyKyCivqlA^ok^pprpy
Q@^kafbaPtbbqMlq^qlbpyKFp^^`>iiboqlk%33)05+1&yyNFAy.1-00yyWyA^ok^pprpy

>Qebv$obO^sbklrpFkA^ok^pprpyKyFp^^`>iiboqlk%33)05+1&yyWyA^ok^pprpyyNFAy.1-0-y
@Qebv$obO^sbklrpFkA^ok^pprpyKy@llh^ka_ofkd2uXPmf`b?ob^aPqrccfkdZ^ka2uX@o^k_boov@erqkbvZqlJfibpPq^kafpefkRkabo`fqv$p`lroqv^oa%qebOrfkplcIloa^bolk&+yyNFAy.1-0-y
CPqlojtfka@fqvyKyDlqlPqlojtfka@fqvy
QQebv$obO^sbklrpFkA^ok^pprpyKyDobdlovQ^_lo%01+.)2.+2&yyWyBitvkkClobpqyyNFAy.1-0-y

KCfka2uXTfiaQrohbvZyKyQebXTfiaQrohbvZfpaolmmba_vqeb%^mmolmof^qbivk^jba&TfiaQrohbvqe^q`^k_bclrkafkBitvkkClobpq%^kaQfofpc^iDi^abp&+dbq^_lrq/2jlobXTfiaQrohbvZfcvlrtfpeqlibsbirmql0--y

>Pilt*ol^pqbaQrohbvyKyDobdlovQ^_lo%01+.)2.+2&yyNFAy.1-02yyWyBitvkkClobpqy
@Pilt*ol^pqbaQrohbvyKy@llh^ka_ofkd2XPilt*Ol^pqbaQrohbvZqlFp^^`>iiboqlklrqpfablcLodofjj^o+yyNFAy.1-02y
CA^ok^pprpyKyCivqlA^ok^pprpy
QPilt*ol^pqbaQrohbvyKyFp^^`>iiboqlk%33)05+1&yyNFAy.1-02yyWyA^ok^pprpy

K@llhfkdDrfab@ljmibqb

]]
end)
