DugisGuideViewer:RegisterGuide("Hallow's End Outland", nil, "Alliance", "D", function() 
return [[
AAA

KObnrfobpJ^kr^iQf`hp+++yKyArbqlqebrkfnrbk^qroblcqefpbsbkqnrbpqp)qebfk*d^jbdrfabfprk^_ibqlob`ldkfpb@^kav?r`hbqnrbpq`ljmibqflk+Vlrtfiikbbaqlj^kr^iivqf`hqebpqbmqlmol`bbaqlqebkbuqpqbm+y
KQ^hb^Mloq^iql?i^pqbaI^kap
OEbiicfobMbkfkpri^yKyDlqeolrdeqebA^ohMloq^i%25+4)26+3&yyWy?i^pqbaI^kapy
QEbiicfobMbkfkpri^)ElkloEliayKyElkloElia%21+0)30+3&yyNFAy./056yyWyEbiicfobMbkfkpri^y
QEbiicfobMbkfkpri^)QbjmiblcQbie^j^qyKyQbjmiblcQbie^j^q%/0+1)03+2&yyNFAy./020yyWyEbiicfobMbkfkpri^y
QW^kd^oj^ope)@bk^oflkObcrdbyKy@bk^oflkObcrdb%45+2)3/+6&yyNFAy./1-0yyWyW^kd^oj^opey
QW^kd^oj^ope)QbiobaloyKyQbiobalo%34+/)16&yyNFAy./021yyWyW^kd^oj^opey
Q?i^ab$pBadbJlrkq^fkp)Qlpeibv$pPq^qflkyKyQlpeibvß??pPq^qflk%3.)35+.&yyNFAy./026yyWy?i^ab$pBadbJlrkq^fkpy
QKbqebopqloj)>ob^2/yKy>ob^2/%0/+.)31+2&yyNFAy./1-4yyWyKbqebopqlojy
QKbqebopqloj)QebPqlojpmfobyKyQebPqlojpmfob%10+1)03+.&yyNFAy./1-5yyWyKbqebopqlojy
Q?i^ab$pBadbJlrkq^fkp)BsbodolsbyKyBsbodolsb%3/+6)05+0&yyNFAy./1-3yyWy?i^ab$pBadbJlrkq^fkpy
Q?i^ab$pBadbJlrkq^fkp)Pvis^k^^oyKyPvis^k^^o%05+2)30+5&yyNFAy./061yyWy?i^ab$pBadbJlrkq^fkpy
QW^kd^oj^ope)Lob_loE^o_lo^dbyKyLob_loE^o_lo^db%1.+6)/3+/&yyNFAy./022yyWyW^kd^oj^opey
QK^do^ka)Qbi^^oyKyQbi^^o%21+/)42+5&yyNFAy./025yyWyK^do^kay
QPe^qqo^qe@fqvyKyDlqlvlroc^`qflkP`ovbopQfbo%23+/)5.+5&>ialoOfpb%/5+.)16&yyNFAy./1-1yyWyPe^qqo^qe@fqvy
QQbolhh^oClobpq)>iibof^kPqolkdeliayKy>iibof^kPqolkdelia%23+3)20+/&yyNFAy./023yyWyQbolhh^oClobpqy
QPe^altjllkS^iibv)Tfiae^jjboPqolkdeliayKyTfiae^jjboPqolkdelia%04+.)25+/&yyNFAy./03-yyWyPe^altjllkS^iibvy
QPe^altjllkS^iibv)>ialoloP`ovboFkkyKyDlqlvlroc^`qflk>iq^olcPe^ß??q^o%3.)/5+/&P^k`qrjlcqebPq^op%23+0)26+5&yyNFAy./1-6yyWyPe^altjllkS^iibvy
KLrqi^kaDrfab@ljmibqb

]]
end)
