DugisGuideViewer:RegisterGuide("Hallow's End Azeroth + Achievement Quest", nil, "Alliance", "D", function() 
return [[
AAA

KObnrfobpJ^kr^iQf`hp+++yKyArbqlqebrkfnrbk^qroblcqefpbsbkqnrbpqp)qebfk*d^jbdrfabfprk^_ibqlob`ldkfpb@^kav?r`hbqnrbpq`ljmibqflk+Vlrtfiikbbaqlj^kr^iivqf`hqebpqbmqlmol`bbaqlqebkbuqpqbm+y
K?bdfk^qA^ok^pprpyKyQ^hbqebmloq^iqlA^ok^pprpcoljA^i^o^ky

QA^ok^pprp)@o^cqpjbk$pQboo^`byKy34).3&yyNFAy./001yyWyA^ok^pprpy
QQbiao^ppfi)Ali^k^^oyKy%23)3-&yNFAy./00.yyWyQbiao^ppfiy
KQ^hbMloq^iqlOrq$qebo^kSfii^dbyKyOrk_^`hqlA^ok^pprp^kaq^hbqebmloq^i%/5+5)13&qlOrq$qebo^kSfii^dbyyWyA^ok^pprpy
_>r_boafkbyKyQ^hbqeb_l^qql>r_boafkb)%21+5)63&yyWyQbiao^ppfiy
e>r_boafkbyKyPbqvlroEb^oqepqlkbql>r_boafkb)FkkhbbmboPe^rppfv%04)11+.&yyWyA^ohpeloby
QA^ohpelob)>r_boafkbyKyA^ohpelob%04)11&yyWyA^ohpelobyyNFAy./005y
_>wrobjvpqFpibyKyQ^hbqeb?l^qql>wrobjvpqFpib)%0-+4)1.&yyWyA^ohpeloby
Q>wrobjvpqFpib)>wrobT^q`eyKy>wrobjvpqFpib%15)16&yyWy>wrobjvpqFpibyyNFAy./000y
Q?illajvpqFpib)?illaT^q`eyKy?illajvpqFpib%23)3-&yyWy?illajvpqFpibyyNFAy./01.y
E>r_boafkbyKyEb^oqe_^`hql>r_boafkbyyRy3615y

CBsboillhyKyCivqlBsboillh)@^vi^fpJllkcb^qebo%03+1)12+3&yyWyA^ohpeloby
QTfkqbopmofkd)BsboillhyKyTfkqbopmofkd%3.)06&yyWyTfkqbopmofkdyyNFAy./1--y

C>pqo^k^^oyKyCivql>pqo^k^^o)J^bqeov^%3/+0)03+3&yyWyTfkqbopmofkdy
Q>pebks^ib)>pqo^k^^oyKy>pebks^ib%04)16&yyWy>pebks^ibyyNFAy./012y

CPqlkbq^ilkMb^hyKyCivqlBsboillh)@^vi^fpJllkcb^qebo%03+1)12+3&yyWyA^ohpeloby
QPqlkbq^ilkJlrkq^fkp)Pqlkbq^ilkMb^hyKyPqlkbq^ilkJlrkq^fkp%02)4&yyWyPqlkbq^ilkJlrkq^fkpyyNFAy./014y

CKfgbi$pMlfkqyKyCivqlKfgbi$pMlfkq)Qbibolk%03+1)4+/&yyWyPqlkbq^ilkJlrkq^fkpy
QAbpli^`b)Kfgbi$pMlfkqyKyAbpli^`b%32)4&yyWyAbpli^`byyNFAy./015y

CCb^qebojllkPqolkdeliayKyCivqlCb^qebojllkPqolkdelia)?bofq^k^p%31+4).-+2&yyWyAbpli^`by
QCbo^i^p)Cb^qebojllkPqolkdeliayKyCbo^i^p%0.)10&yyNFAy./02-yyWyCbo^i^py

C@bk^oflkEliayKyCivql@bk^oflkElia%0-+/)10+0&yyWyCbo^i^py
QPfifqerp)@bk^oflkEliayKyCbo^i^p%2/)06&yyWyPfifqerpyyNFAy./1-.y

CD^adbqw^kyKyCivqlD^adbqw^k)@ilraPhva^k`bo%2-+3)01+2&yyWyPfifqerpy
QQ^k^ofp)D^adbqw^kyKyQ^k^ofp%2/)/5&yyWyQelrp^kaKbbaibpyyNFAy./066y

CJrapmol`hbqyKyCivqlJrapmol`hbqArpqt^iiltJ^ope)?bo^%2.)/6+0&yyWyQ^k^ofpy
QArpqt^iiltJ^ope)Jrapmol`hbqyKyArpqt^iiltJ^ope%1/)41&yyWyArpqt^iiltJ^opeyyNFAy./065y
CQebo^jlobFpibyKyCivqlQebo^jlobFpib)?bo^%1/+5)4/+1&yyWyArpqt^iiltJ^opey

CO^`ebqyKyCivqlO^q`ebq%34+2)2.+0&yyWyArpqt^iiltJ^opey
Q?^oobkp)O^q`ebqyKyQeb?^oobkp%3/)06&yyWyQeb?^oobkpyyNFAy./063y

_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpy
QPqo^kdibqelokS^ib)?llqv?^vyKy?llqv?^v%/4+.)44+0&yyNFAy./064yyWyPqo^kdibqelokS^iby

CPbkqfkbiEfiiyKyCivqlTbpqc^ii%/4+2)44+5&yyWyPqo^kdibqelokS^iby
QTbpqc^ii)PbkqfkbiEfiiyKyTbpqc^ii%40+6)11+2&yyNFAy./01-yyWyTbpqc^iiy

CA^ohpefobyKyCivqlA^ohpefob%23+2)2/+3&yyWyTbpqc^iiy
QArphtlla)A^ohpefobyKyArphtlla%40+6)11+2&yyNFAy./011yyWyArphtllay

CI^hbpefobyKyCivqlI^hbpefob%44+2)11+0&yyWyArphtllay
QObaofadbJlrkq^fkp)I^hbpefobyKyObadofadbJlrkq^fkp%/4)12&yyWyObaofadbJlrkq^fkpyyNFAy./01/y

CPqlojtfka@fqvyKyCivqlPqlojtfka@fqv%0-+3)26+1&yyWyObaofadbJlrkq^fkpy
QPqlojtfka)QebQo^abAfpqof`qyKyPqlojtfka)%3-+2)42+/&yyWyPqlojtfka@fqvyyNFAy./003y
QBitvkkClobpq)DliapefobyKyBitvkkClobpq)%10+4)33&yyWyBitvkkClobpqyyNFAy.//53y

O@fqvlcFolkclodbyKyQ^hbqebqo^jqlFolkclodb%33+1)01+.&yyWyPqlojtfka@fqvy
QFolkclodb)Qeb@ljjlkpyKyFolkclodb%.5+4)2.+2&yyWyFolkclodbyyNFAy./002y
eFolkclodbyKyPbqvlroeb^oqepqlkbqlFolkclodb%.5+.)2.+2&yyWyFolkclodby
QArkJlolde)He^o^klpyKyHe^o^klp%14+1)2/+1&yyNFAy./00/yyWyArkJloldey
EFolkclodbyKyEb^oqeqlFolkclodbyyRy3615y

CQebip^j^oyKyCivqlQebip^j^o%22+2)14+5&yyWyFolkclodby
QIl`eJla^k)Qebip^j^oyKyIl`eJla^k%02+2)15+2&yyWyIl`eJla^kyyNFAy./006y

CJbkbqefiE^o_loyKyCivqlJbkbqefiE^o_lo%00+6)2.&yyWyIl`eJla^ky
QTbqi^kap)JbkbqefiE^o_loyKyJbkbqefiE^o_lo%.-+5)3-+6&yyWyTbqi^kapyyNFAy./010y

CPlrqepelobyKyCivqlPlrqepelob%6+2)26+4&yyWyTbqi^kapy
QEfiip_o^aCllqefiip)PlrqepelobyKyPlrqepelob%2.+.)25+6&yyWyEfiip_o^aCllqefiipyyNFAy./013y
ePlrqepelobyKyPbqvlroEb^oqeqlPlrqepelob)Fkkhbbmbo>kaboplk%2.+/)25+6&yyWyEfiip_o^aCllqefiipy
>@o^pefkdqebTf`hboj^kCbpqfs^iyKyPbodb^kqE^oqj^k%2-)24+2&yyNFAy.325yyWyEfiip_o^aCllqefiipy
>QebMltbolcMfkbyKyPbodb^kqE^oqj^k%2-)24+2&yyNFAy5040yyWyEfiip_o^aCllqefiipy
@QebMltbolcMfkbyKyCfkaqebobam^q`ebpfkqeb^ob^qeoltk_vEloabmi^vbop%26+4)24+1&^karpbqebXPqfkh?lj_@ib^kboZyyRy/-3-1yyNFAy5040yyWyEfiip_o^aCllqefiipy

C@efiitfka@^jmyKyCivql@efiitfka@^jm%16+0)2/+0&yyWyEfiip_o^aCllqefiipy
OQfofpc^iDi^abpyKyOrkqlQfofpc^iDi^abp%50+6)4-+0&yyWyQfofpc^iDi^abpy
@@o^pefkdqebTf`hboj^kCbpqfs^iyKyP`lrqqebTf`hboj^k%26)36&yyNFAy.325yyWyQfofpc^iDi^abpy
EPlrqepelobyRy3615y
Q@o^pefkdqebTf`hboj^kCbpqfs^iyKyPbodb^kqE^oqj^k%2-)24+2&yyNFAy.325yyWyEfiip_o^aCllqefiipy
QQebMltbolcMfkbyKyPbodb^kqE^oqj^k%2-)24+2&yyNFAy5040yyWyEfiip_o^aCllqefiipy

C>bofbMb^hyKyCivql>bofbMb^h%16+0)2/+0&yyWyEfiip_o^aCllqefiipy
QEfkqboi^kap)>bofbMb^hyKyEfkqboi^kap%.1+.)1.+3&yyWyQebEfkqboi^kapyyNFAy./02.y

CIfdeq$pElmb@e^mbiyKyB^pqbokMi^drbi^kap%..+.)13+.&yyWyQebEfkqboi^kapy
QB^pqbokMi^drbi^kap)Ifdeq$pElmb@e^mbiyKyIfdeq$pElmb@e^mbi%42+6)2/+0&yyWyB^pqbokMi^drbi^kapy

K>wbolqeDrfab@ljmibqb

]]
end)
