DugisGuideViewer:RegisterGuide("The Lunar Festival (80+)", nil, "Alliance", "D", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^obibsbi5-)^ka,lo^obfk^i^odbdolrm+Vlrtfii_bsfpfqfkdpljbk^pqvmi^`bptef`ej^v_be^oaqlplil+Dllair`h)_o^sb^asbkqroboy

eA^i^o^kyKyFcvlr^ob`roobkqivfkA^i^o^k)j^hbprobqlpbqvlroEb^oqepqlkbqebobfcvlre^sbk$q^iob^avalkbpl+Vlr$ii_b`ljfkd_^`hi^qbo+y
O@fqvlcFolkclodbyKyRpbqebmloq^iy

>QebIrk^oCbpqfs^iyKyColjqebIrk^oCbpqfs^iBjfpp^ovfkFolkclodb+Phfmqefp^kaqebcliilt*rmfcvlr^iob^ave^sb^XIrk^oCbpqfs^iFksfq^qflkZyyNFAy554-y
QQebIrk^oCbpqfs^iyKy@eb`h?ifww^oa$pnrbpqqo^`hbocloqebil`^qflkyyNFAy554-y

>Irk^oCfobtlohpyNFAy5534y
@Irk^oCfobtlohpyKy?rvcfobtlohpcoljqebkb^o_vsbkalo)i^rk`eqebjfkqlqebphvyyNFAy5534y
QIrk^oCfobtlohpyKy@eb`h?ifww^oa$pnrbpqqo^`hbocloqebil`^qflkyyNFAy5534y

>S^i^a^oPq^oplkdyNFAy5550y

Q?olkwb_b^oaqebBiaboyKyFkqebJvpqf`T^oa%/5+.).4&yWyFolkclodby

CPb^ofkdDlodb
QFolk_^kaqebBiaboyKyPlrqetbpq`lokbofk?i^`h`e^o@^sb%/.)46&yyWyPb^ofkdDlodby

O?i^`hol`hPmfobyKyWlkbfkqebfkpq^k`b?i^`hol`hPmfoby
QPqlkbcloqqebBiaboyKyEb$pfkqeb$iltbo$b^oivm^oqlcI?OP)^`olpp^_ofadbofdeq_bclobtebobvlrdbqqebOlrdepelaMfhb+Vlrpelria_b^_ibqlpbbefj%lo^qib^pqefpmfii^olcifdeq&coljtebobS^bi^kfp+Ebfpob^`e^_ibtfqelrq^ddol^qibsbi4-y

O?i^`hol`hAbmqepyKyWlkbfkqebfkpq^k`b?i^`hol`hAbmqepy
QJlokabbmqebBiaboyKyFkpfabqebOfkdlcI^ty

O?rokfkdPqbmmbp
QA^tkpqofaboqebBiaboyKyRm^qCi^jb@obpq)qe^q`^sbtfqeqebIf_o^jdrv%31+/)/1&yyWy?rokfkdPqbmmbpy
QOrj_ibol`hqebBiaboyKyLkqlmlcAob^aj^riOl`h)kloqelcJlod^k$pSfdfi%5.+6)13+0&yyWy?rokfkdPqbmmbpy

OPqlojtfka@fqv
QE^jjbopelrqqebBiaboyKyPq^kafkdfkqebJllkTbii)M^ohAfpqof`q%03)33&yyWyPqlojtfka@fqvy

OBitvkkClobpq
QPqloj_oltqebBiaboyKyKb^oqebmlka%06+3)30+2&yyWyBitvkkClobpqy

OTbpqc^ii
QPhv`e^pboqebBiaboyKyLkqlmlcqebqltbo)kloqe*b^pqlcPbkqfkbiEfii%23+3)14&yyWyTbpqc^iiy

C?i^pqbaI^kap
Q?biilto^dbqebBiaboyKyKloqelcqebA^ohMloq^i%24+4)21+4&yyWy?i^pqbaI^kapy

OQebQbjmiblc>q^i$E^hh^o
QPq^oplkdqebBiaboyKyCfopqibcqrmpmfo^ipq^fop)qeolrdeao^dlkhfk^qqlmi^kafkd)pq^vibcqfkqlj^fkolljtfqeao^dlkhfky

CPqo^kdibqelokS^ibyKyOb_bi@^jm)mobcbo^_ivy
QPq^odi^abqebBiaboyKyKb^oWri$Dror_)fkqebofdeq`lroqv^oafkcolkqlcqebpqbmprmqlfkpq^k`bbkqo^k`b%20+.).5+0&yyWyPqo^kdibqelokS^iby
QTfkqboellcqebBiaboyKyKb^oEloabcifdeqj^pqbolkqlmlcqeb_^khfk?llqv?^v%/3+0)43+1&yyWyPqo^kdibqelokS^iby

_Qeb?^oobkp
QTfkaqlqbjqebBiaboyKyFkO^q`ebq)lrqpfablcqebBkdfkbbofkd_rfiafkdkloqelcqeb_^kh%3/+3)03+4&yyWyQeb?^oobkpy

OLodofjj^oyKyVbp)>iif^k`bkbbaqldlqlEloab`fqfbp+Ir`hfivclovlr)Lodofjj^ofpqebi^odbpqEloab`fqv+>kagrpqifhbfkFolkclodb)qebjlpq`oltabami^`bpfpqeb_^kh)qebj^fi_lu^kaqeb^r`qflkelrpb+Lodofjj^oe^pqtlbkqo^k`bp+Lkbfkqebplrqe)^kalkbfkqebtbpq+Vlrtlriaifhbqlbkqboqebtbpqbokbkqo^k`b)pfk`bqefpfpqebbkqo^k`btfqeqebib^pqmi^vbop)eltbsbovlrpqfiie^sbqllrqorkdr^oapy
QA^ohelokqebBiaboyKyLrqpfabQeo^ii$p`e^j_bo)S^iibvlcTfpalj%1-+6)0/+6&yyWyLodofjj^oy

OArolq^o
QOrkbqlqbjqebBiaboyKyPBbadblcO^wloEfii%20+.)10+2&yyWyArolq^oy

OQeb?^oobkp
QJllkt^oabkqebBiaboyKyKbuqqlqebcifdeqj^pqbofkqeb@olppol^ap%2.+1)0-+3&yyWyQeb?^oobkpy
QEfdeJlrkq^fkqebBiaboyKyKBbadblc@^jmQ^ro^gl)kbuqqlqebclodb%12)24+6&yyWyQeb?^oobkpy

OJridlob
Q?illaellcqebBiaboyKyKloqelc?illaellcSfii^db)kbuqqlqeb_ofadb%15+0)20+1&yyWyJridloby

OQerkabo?irccyKyRkifhbLodofjj^o)Qerkabo?irccfpklq^sbov_fd`fqv)qebobclobvlr^objr`ejlobifhbivqljbbqbkbjvmi^vbop+Eltbsbo)Qerkabo?irccfpgrpq^pmlmri^o`fqv^pA^ok^pprpfp)^kaqebobclobvlre^sbdob^q`e^k`bplcklq_bfkdlrqkrj_boba+Bkqbosf^qebKloqeIfcqy
QTeb^qellcqebBiaboyKyBiaboOfpb%4/+/)/0+2&+Fkjbjlof^j)Bwo^@e^qqboqlk%.665*/--5&+yyWyQerkabo?irccy

OQelrp^kaKbbaibp
QPhvpbboqebBiaboyKyJfaaiblcCobbtfkaMlpq%12+0)16+0&yyWyQelrp^kaKbbaibpy
QJlokfkdabtqebBiaboyKyJfo^dbO^`bt^v)kb^oqebpq^oqfkdifkb%46)43+6&yyWyQelrp^kaKbbaibpy

OQ^k^ofp
QAob^jpbboqebBiaboyKyFkD^adbqw^k%2.+0)/4+5&yyWyQ^k^ofpy

OWri$C^oo^h
QTfiaj^kbqebBiaboyKyPB`lokbolcqebolljtfqeD^ew$ofii^$pdlkdy

OQ^k^ofp
QO^dbqlqbjqebBiaboyKyS^iibvlcqebT^q`ebop)tbpqpfab%03+/)5-+1&yyWyQ^k^ofpy

ORk$Dlol@o^qbo
QQerkaboelokqebBiaboyKyKloqelcqebPifqebofkdP`^o%2-+.)43+.&yyWyRk$Dlol@o^qboy

OPfifqerp
Q?i^abpfkdqebBiaboyKyPq^kafkdfkqebJllkTbii)@bk^oflkElia%15+5)04+3&yyWyPfifqerpy
QMofjbpqlkbqebBiaboyKy@bkqbolcqeb@ovpq^iS^ib%//+6)..+3&yyWyPfifqerpy

CAbpli^`b
OJ^o^ralk
QPmifqol`hqebBiaboyKyGrjmfkqlqebt^qbo_vqebMofk`bpp^kaOlqdofm+Ptfjqlqebb^pq^kaeb^armqebo^jm+Qrokofdeq^kaeb^arm^/kao^jm+QebBiabotfii_bfkcolkqlcvlr+y

O@fqvlcFolkclodbyKyEb^oqeqlA^i^o^k)rpbqebmloq^iy
OArkJlolde
QDliatbiiqebBiaboyKyKb^oqebHe^o^klpfkk%13+4)2.+1&yyWyArkJloldey

OIl`eJla^k
QPfisbosbfkqebBiaboyKy%00)13+0&yyWyIl`eJla^ky

CQebEfkqboi^kap
QEfdemb^hqebBiaboyKyKb^oqeb@obbmfkdOrfk%16+6)14+6&yyWyQebEfkqboi^kapy

OTbpqbokMi^drbi^kap
QJllkpqofhbqebBiaboyKyLkqlmlcqebP`elilj^k`bQltbo)lrqpfablcqebfkpq^k`b%36)41&yyWyTbpqbokMi^drbi^kapy
QJb^altorkqebBiaboyKyKloqelcqebol^a)plrqelcQebTbbmfkd@^sb%32+5)14+4&yyWyTbpqbokMi^drbi^kapy

OB^pqbokMi^drbi^kap
QTfkaorkqebBiaboyKy@oltkDr^oaQltbo)kloqelcA^ooltpefob%02+3)35+5&yyWyB^pqbokMi^drbi^kapy
QPklt`oltkqebBiaboyKyIfdeq$pElmb@e^mbi%42+4)21+3&yyWyB^pqbokMi^drbi^kapy

OPqo^qelijb
QC^otefpmboqebBiaboyKyKloqelcqebCbpqfs^iI^kbj^fi_lu%kb^oQebRkclodfsbk&+Bkqboqeolrdeqeb_^`hallo+J^hbvlrocfopqibcqfkqebfkpq^k`b)dlqeolrdeqebd^qb)qrokofdeq)^kaqebBiabotfii_bpq^kafkd^qqeb_^`h+y

OQfofpc^iDi^abp
QDo^sb_lokqebBiaboyKyGrpqplrqelc?ofii%3.+4)20+4&yyWyQfofpc^iDi^abpy

OPfisbomfkbClobpq
QL_pfaf^kqebBiaboyKyKb^oqlQebPbmri`ebo%11+5)1.+.&yyWyPfisbomfkbClobpqy

ORkabo`fqv
QA^oh`lobqebBiaboyKyFkqebjfaaiblcRkabo`fqv)^_lsbdolrka%34+1)06+.&yyWyRkabo`fqvy

OJllkdi^abyKyPq^kafkqeb_fd_b^jlcifdeqfkqebjfaaiblcqebQeolkbOllj^karpbvlroIrk^oFksfq^qflk+LorpbvlroQbibmloqpmbiifcvlr^ob^Aorfa+Bfqebot^vtfiimloqvlrqlJllkdi^ab+yyRy/.4..y
QS^i^a^oPq^oplkdyKy%21)02&yyNFAy5550yyWyJllkdi^aby

CTfkqbopmofkd
QPqlkbpmfobqebBiaboyKyFkqeb`bkqbolcBsboillh%3.+0)04+4&yyWyTfkqbopmofkdy
Q?ofdeqpmb^oqebBiaboyKyPlrqeb^pqbokbadblcI^hbHbi$Qebofi%22+0)10+5&yyWyTfkqbopmofkdy

CCbitlla
QKfdeqtfkaqebBiaboyKyKloqelcG^babk^o%04+4)2/+6&yyWyCbitllay

C>wpe^o^
QPhvdib^jqebBiaboyKyO^sbk`obpqJlkrjbkq)plrqe*b^pq%4/+1)51+6&yyWy>wpe^o^y

OA^ok^pprpyKyEb^oqeqlA^i^o^k)rpbqebmloq^iy
Q?i^abptfcqqebBiaboyKy@bkqbolcqeb@bk^oflkBk`i^sb%00+3).2+.&yyWyA^ok^pprpy
Q?i^abib^cqebBiaboyKyPlrqebokbadblcAli^k^^o%24+/)3-+4&yyWyQbiao^ppfiy

CA^ohpelob
QPq^otb^sbqebBiaboyKyKb^oqebEfmmldovmeJ^pqbofk>r_boafkb%03+4)13+3&yyWyA^ohpeloby

O>pebks^ib
QOfsboplkdqebBiaboyKyFkqebd^wb_lkb^oqebEfmmldovmeJ^pqbo%02+1)15+6&yyWy>pebks^iby

CCbo^i^p
QJfpqt^ihboqebBiaboyKyFkpfabqebAfobJ^ri^obk^)lrqpfabqebfkpq^k`b%3/)0.&yyWyCbo^i^py
QDofjqlqbjqebBiaboyKyI^ofppM^sfiflk)kloqeb^pqlc@^jmJlg^`eb%43+4)04+4&yyWyCbo^i^py

KKloqeobkayKyQeba^q^cloqebBiaboplcKloqeobkafpfk`ljmibqb+Vlrtfiie^sbqlcfkapljblcqebj)bpmb`f^iivfkarkdblkp)lkvlroltk+y

EA^i^o^k
OQebPqlojMb^hp
QC^od^iqebBiaboyKyFkColpqelia%/5+6)40+4&yyWyQebPqlojMb^hpy
QDo^vj^kbqebBiaboyKyFkH0%1.+/)51+4&yyWyQebPqlojMb^hpy
QPqlkb_b^oaqebBiaboyKyFk?lriabo`o^d$pObcrdb%0.+0)04+3&yyWyQebPqlojMb^hpy
QJro^`lqebBiaboyKyfk@^jmQrkh^$il%31+3)2.+0&yyWyQebPqlojMb^hpy

OWri$Ao^h
QQ^rolpqebBiaboyKyFkWfj$Qlod^%25+6)23&yyWyWri$Ao^hy

ODofwwivEfiip
QIrk^olqebBiaboyKyFkqebOrfkplcQbqevp%5-+2)04+3&yyWyDofwwivEfiipy
Q?bia^hqebBiaboyKyTbpqc^ii?ofd^abBk`^jmjbkq%3-+3)/4+4&yyWyDofwwivEfiipy
QTero^fkqebBiaboyKy@^jmLkbnt^e%31+/)14&yyWyDofwwivEfiipy

OAo^dlk_ifdeq
QQelfjqebBiaboyKyfkJl^$hfE^o_lo%15+5)45+/&yyWyAo^dlk_ifdeqy
QPhvt^oabkqebBiaboyKyfk>dj^o$pE^jjbo%02+.)15+0&yyWyAo^dlk_ifdeqy
QJloqefbqebBiaboyKyfkPq^o$pObpq%/6+4)22+6&yyWyAo^dlk_ifdeqy

O?lob^kQrkao^
Q>omqebBiaboyKyfkqebA+B+E+Q+>+`^jm%24+0)10+4&yyWy?lob^kQrkao^y
QP^oafpqebBiaboyKyfkS^if^k`bHbbm%26+.)32+3&yyWy?lob^kQrkao^y
QM^jrv^qebBiaboyKyfkT^oplkdElia%1/+6)16+3&yyWy?lob^kQrkao^y
QKloqe^iqebBiaboyKyfkQo^kpfpqrpPefbia%00+5)01+1&yyWy?lob^kQrkao^y

OPeli^w^o?^pfk
QP^kaobkbqebBiaboyKyfkI^hbpfabI^kafkd%16+5)30&yyWyPeli^w^o?^pfky
QT^kfh^v^qebBiaboyKyfkO^fkpmb^hboO^mfap%30+5)16&yyWyPeli^w^o?^pfky

OTfkqbodo^pm
Q?irbtlicqebBiaboyKyVlroc^`qflkkbbapql`lkqoliI^hbTfkqbodo^pmfkloaboqlsfpfqBiabo?irbtlic+%16).1&yyWyTfkqbodo^pmy

OQebKburp
QFd^pelqebBiabo

OE^iiplcPqlkb
QVro^rhqebBiaboyKyLkqebofdeq^pvlrdlfky

ORqd^oabHbbm
QG^oqbkqebBiabo

O>wgli*Kbor_
QKrodbkqebBiabo

OAo^h$Qe^olkHbbm
QHfif^pqebBiabo

ORqd^oabMfkk^`ib
Q@eld^k$d^a^qebBiabo

ODrkao^hyKyQebbiabotfiilkiv^mmb^ofkEbolf`Jlab)^kaobnrfobpvlrqlabcb^qJllo^_f^ilkdqebt^vy
QLe^kwbbqebBiaboyKyQebbiabotfiilkiv^mmb^ofkEbolf`Jlab)^kaobnrfobpvlrqlabcb^qJllo^_f^ilkdqebt^vy

]]
end)
