DugisGuideViewer:RegisterGuide("Midsummer Festival - Lord Ahune (70+)", nil, "Alliance", "D", function() 
return [[
AAA

>Rkrpr^i>`qfsfqvyKyVlr`^kmf`hrmqefpnrbpqcoljB^oqebkOfkdBiaboclrkafk^kvj^glo`fqvS^iibvlcTfpaljfkLodofjj^oloE^iilcBumilobofkFolkclodbyyNFAy..553y
O>pqo^k^^oyKyQo^sbiql>pqo^k^^ofk>pebks^iby
@Rkrpr^i>`qfsfqvyKyHfiiqebQtfifdeqpKM@%.2).4&qldbqXQtfifdeq@loobpmlkabk`bZyyNFAy..553yyWy>pebks^iby
QRkrpr^i>`qfsfqvyKyRpbqebXQlqbjf`?b^`lkZqlprjjlkqebKM@qlqrokfkqebnrbpqyyNFAy..553yyRy025/5y
>>kFkkl`bkqAfpdrfpbyNFAy..56.y
@>kFkkl`bkqAfpdrfpbyKyCliiltqeb_irbqlo`ebpql%6+2)60+/&^karpbqebXLo_lcqeb@o^tiboZyyNFAy..56.yyRy02/04yyWy>pebks^iby
Q>kFkkl`bkqAfpdrfpbyKyRpbqebXQlqbjf`?b^`lkZqlprjjlkqebKM@qlqrokfkqebnrbpqyyNFAy..56.yyRy025/5y
>FkclojqebBiaboyNFAy./-./y
QFkclojqebBiaboyKyDl_^`hqlqebbiabofk^kv`^mfq^i`fqvyyNFAy./-./y
OQebColpqIloa>erkbyKyRpbqebArkdblkCfkaboqlnrbrbcloIloa>erkbyyFy
HIloa>erkbyKyGrpqhfiiqeb^aaprkqfiIloa>erkb_b`ljbpsrkbo^_ib)qebkbsbovlkb`^ka^j^dbIloa>erkbyyIy024/0y
>Pe^oaplc>erkbyRy024/0yyLyyNFAy..64/y
QPe^oaplc>erkbyKyIrj^Phvjlqebofkpfabqebpi^sbmbkpyyLyyNFAy..64/y
KDrfab@ljmibqb

]]
end)
