DugisGuideViewer:RegisterGuide("Midsummer Festival Azeroth (50+)", nil, "Alliance", "D", function() 
return [[
AAA

KJ^kr^iQf`hObnrfobayKyArbqlqebrkfnrbk^qroblcqebJfaprjjbobsbkq)ArdfpDrfabSfbtboWfp`roobkqivrk^_ibql^rqlj^qf`^iivabqb`qqebnrbpq^kavlrtfiikbbaqlqf`hqeb`ljmibqbanrbpqj^kr^iiv+Tb^obtlohfkdlk^plirqflky
OA^ok^pprpyKy?bdfk^qA^ok^pprpy

>ElkloqebCi^jb%Ali^k^^o&yKy%22)3-&yyNFAy..5/1yyWyQbiao^ppfiyyBy
OQbiao^ppfiyKyOrk_^`hqlA^ok^pprp^kaq^hbqebmloq^i%/5+5)13&qlOrq$qebo^kSfii^dbyyWyA^ok^pprpy
C>r_boafkbyKyCivql>r_boafkb)%21+5)61&yyWyQbiao^ppfiy
e>r_boafkbyKyPbqvlroEb^oqepqlkbql>r_boafkb)FkkhbbmboPe^rppfv%04)11+.&yyWyA^ohpeloby
_>wrobjvpqFpibyKyQ^hbqeb?l^qql>wrobjvpqFpib)%0-+4)1.&yyWyA^ohpeloby
>ElkloqebCi^jb%>wrobT^q`e&yKy>wrobjvpqFpib%11)20&yyWy>wrobjvpqFpibyyNFAy..5-3yyBy
>ElkloqebCi^jb%?illaT^q`e&yKy?illajvpqFpib%22)36&yyWy?illajvpqFpibyyNFAy..5-6yyBy
E>r_boafkbyKyEb^oqe_^`hql>r_boafkbyyRy3615y
>ElkloqebCi^jb%>r_boafkb&yKyA^ohpelob%04)13&yyWyA^ohpelobyyNFAy..5..yyBy

CBsboillhyKyCivqlBsboillh)@^vi^fpJllkcb^qebo%03+1)12+3&yyWyA^ohpeloby
>Abpb`o^qbqefpCfob%Bsboillh&yKyTfkqbopmofkd%26)02&yyWyTfkqbopmofkdyyNFAy..5-0yyBy
>ElkloqebCi^jb%Bsboillh&yKyTfkqbopmofkd%3/)02&yyWyTfkqbopmofkdyyNFAy..501yyBy

C>pqo^k^^oyKyCivql>pqo^k^^o)J^bqeov^%3/+0)03+3&yyWyTfkqbopmofkdy
>ElkloqebCi^jb%>pqo^k^^o&yKy>pebks^ib%05)21&yyWy>pebks^ibyyNFAy..5-2yyBy
>Abpb`o^qbqefpCfob%PmifkqboqobbMlpq&yKy>pebks^ib%4-)36&yyWy>pebks^ibyyNFAy..432yyBy

OQeb?^oobkpyKyOrkPlrqeqlQeb?^oobkp%15+0)..+0&yyWyQeb?^oobkpy
>Abpb`o^qbqefpCfob%@olppol^ap&yKyQeb?^oobkp%2/)/5&yyWyQeb?^oobkpyyNFAy..450yyBy

OArolq^oyKyOrkqlArolq^o%02+/)1/+1&yyWyArolq^oy
>Abpb`o^qbqefpCfob%O^wloEfii&yKyArolq^o%2/)14&yyWyArolq^oyyNFAy..44-yyBy
KPqb^iXCi^jblcLodofjj^oZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%13)05&yyIy/0.46yyWyLodofjj^oy
>Pqb^ifkdLodofjj^o$pCi^jbyRy/0.46yyLyyNFAy60/1yyBy
E>r_boafkbyKyEb^oqe_^`hql>r_boafkbyyRy3615y

CPqlkbq^ilkMb^hyKyCivqlBsboillh)@^vi^fpJllkcb^qebo%03+1)12+3&yyWyA^ohpeloby
>Abpb`o^qbqefpCfob%PrkOl`hObqob^q&yKyPqlkbq^ilkJlrkq^fkp%2-)3-&yyWyPqlkbq^ilkJlrkq^fkpyyNFAy..45-yyBy
OAbpli^`byKyOrkqlAbpli^`b%/4)52&yyWyPqlkbq^ilkJlrkq^fkpy
>ElkloqebCi^jb%Kfgbi$pMlfkq&yKyAbpli^`b%32).4&yyWyAbpli^`byyNFAy..5./yyBy
>Abpb`o^qbqefpCfob%Pe^altmobvSfii^db&yKyAbpli^`b%/3)43&yyWyAbpli^`byyNFAy..436yyBy

OCbo^i^pyKyOrkqlCbo^i^p%12)5+2&yyWyCbo^i^py
_Cb^qebojllkyKyRpbqeb_l^q^q%10+1)1/+4&yyWyCbo^i^py
>ElkloqebCi^jb%Cb^qebojllkPqolkdelia&yKyCbo^i^p%/5)11&yyWyCbo^i^pyyNFAy..5.4yyBy
CQe^i^k^^oyKyCivqlQe^i^k^^o%0-+/)10+0&yyWyCbo^i^py
>Abpb`o^qbqefpCfob%@^jmJlg^`eb&yKyCbo^i^p%4/)14&yyWyCbo^i^pyyNFAy..440yyBy
C@bk^oflkEliayKyCivql@bk^oflkElia)%56+2)12+6&yyWyCbo^i^py

>Abpb`o^qbqefpCfob%@bk^oflkElia&yKyPfifqerp%13)11&yyWyPfifqerpyyNFAy..5--yyBy
>ElkloqebCi^jb%@bk^oflkElia&yKyPfifqerp%24)01&yyWyPfifqerpyyNFAy..50.yyBy

CQe^i^k^^oyKyCiv_^`hqlQe^i^k^^o)@ilraPhva^k`bo%2-+3)01+2&yyWyPfifqerpy
>Abpb`o^qbqefpCfob%CobbtfkaMlpq&yKyQelrp^kaKbbaibp%1.)2/&yyWyQelrp^kaKbbaibpyyNFAy..452yyBy

OQ^k^ofpyKyOrkqlQ^k^ofp%40+5)63+.&yyWyQelrp^kaKbbaibpy
>Abpb`o^qbqefpCfob%D^adbqw^k&yKyQ^k^ofp%16)/4&yyWyQ^k^ofpyyNFAy..5-/yyBy
>ElkloqebCi^jb%D^adbqw^k&yKyQ^k^ofp%2/)/6&yyWyQ^k^ofpyyNFAy..500yyBy

CQebo^jlobFpibyKyCivqlQebo^jlobFpib)?bo^%2.)/6+0&yyWyQ^k^ofpy
>ElkloqebCi^jb%Qebo^jlobFpib&yKyArpqt^iiltJ^ope%3/)1-&yyWyArpqt^iiltJ^opeyyNFAy..5.2yyBy
>Abpb`o^qbqefpCfob%?o^`hbkt^iiSfii^db&yKyArpqt^iiltJ^ope%00)0-&yyWyArpqt^iiltJ^opeyyNFAy..44.yyBy

OQeb?^oobkpyKyOrkqlQeb?^oobkp%16+2)45+0&yyWyQeb?^oobkpy
OJridlobyKyOrkqlJridlob%35+0)3-+1&yyWyJridloby

>Abpb`o^qbqefpCfob%?illaellcSfii^db&yKyJridlob%2.)3-&yyWyJridlobyyNFAy..444yyBy
KPqb^iXCi^jblcQerkabo?irccZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%/.)/2&yyWyQerkabo?irccyyIy/0.5-y
>Pqb^ifkdQerkabo?ircc$pCi^jbyRy/0.5-yyLyyNFAy60/2yyBy
E>r_boafkbyKyEb^oqe_^`hql>r_boafkbyyRy3615y

_Pqlojtfka@fqvyKyQ^hbqebplrqe_l^qqlPqlojtfka@fqv%0/+1)10+5&yyWyA^ohpeloby
OBitvkkClobpqyKyOrkqlBitvkkClobpq%0/+3)16+6&yyWyBitvkkClobpqy
>ElkloqebCi^jb%Dliapefob&yKyBitvkkClobpq%10)32&yyWyBitvkkClobpqyyNFAy..5.3yyBy
OTbpqc^iiyKyOrkqlTbpqc^ii%26+3)/-+/&yyWyTbpqc^iiy
>ElkloqebCi^jb%PbkqfkbiEfii&yKyTbpqc^ii%23)21&yyWyTbpqc^iiyyNFAy..250yyBy

C?llqv?^vyKyCivql?llqv?^v)Qelo%23+2)2/+3&yyWyTbpqc^iiy
>Abpb`o^qbqefpCfob%?llqv?^v&yKyPqo^kdibqelokS^ib%0/)42&yyWyPqo^kdibqelokS^ibyyNFAy..5-.yyBy
>ElkloqebCi^jb%?llqv?^v&yKyPqo^kdibqelokS^ib%00)40&yyWyPqo^kdibqelokS^ibyyNFAy..50/yyBy

CA^ohpefobyKyCivqlA^ohpefob%/4+2)44+5&yyWyPqo^kdibqelokS^iby
eA^ohpefobyKyPbqvlroEb^oqefkA^ohpefob)%40+6)11+1&yWyArphtllay
>ElkloqebCi^jb%A^ohpefob&yKyArphtlla%41)2.&yyWyArphtllayyNFAy..5.1yyBy

CKbqebod^oabHbbmyKyCivqlKbqebod^oabHbbm%44+2)11+0&yyWyArphtllay
>ElkloqebCi^jb%Kbqebod^oabHbbm&yKy?i^pqbaI^kap%25).4&yyWy?i^pqbaI^kapyyNFAy..5-5yyBy
OPt^jmlcPlooltpyKyOrkqlPt^jmPlooltp%00+0)32+/&yyWyPt^jmlcPlooltpy
>Abpb`o^qbqefpCfob%Pqlk^oa&yKyPt^jmlcPlooltp%14)14&yyWyPt^jmlcPlooltpyyNFAy..45.yyBy
EA^ohpefobyRy3615y

CI^hbpefobyKyCivqlI^hbpefob%44+2)11+0&yyWyArphtllay
>ElkloqebCi^jb%I^hbpefob&yKyObaofadbJlrkq^fkp%/1)26&yyWyObaofadbJlrkq^fkpyyNFAy..5//yyBy

CJlod^k$pSfdfiyKyCivqlJlod^k$pSfdfi%0-+3)26+1&yyWyObaofadbJlrkq^fkpy
>ElkloqebCi^jb%Jlod^k$pSfdfi&yKy?rokfkdPqbmmbp%5-)3/&yyWy?rokfkdPqbmmbpyyNFAy..5.-yyBy
>Abpb`o^qbqefpCfob%Ci^jb@obpq&yKy?rokfkdPqbmmbp%3/)/6&yyWy?rokfkdPqbmmbpyyNFAy..435yyBy

CQelofrjMlfkqyKyCivqlQelofrjMlfkq%51+0)35+0&yyWy?rokfkdPqbmmbpy
O?^ai^kapyKyOrkql?^ai^kap%43+4)23+4&yyWyPb^ofkdDlodby
>Abpb`o^qbqefpCfob%H^od^qe&yKy?^ai^kap%1)16&yyWy?^ai^kapyyNFAy..433yyBy

OIl`eJla^kyKyOrkqlIl`eJla^k%14)5-&yyWyIl`eJla^ky
>ElkloqebCi^jb%Qebip^j^o&yKyIl`eJla^k%0/)1-&yyWyIl`eJla^kyyNFAy..5/-yyBy

C@fqvlcFolkclodbyKyCivqlFolkclodb%00+6)2.&yyWyIl`eJla^ky
>ElkloqebCi^jb%He^o^klp&yKyArkJlolde%13)13&yyWyArkJloldeyyNFAy..5.0yyBy

O@fqvlcFolkclodbyKyOrk_^`hqlFolkclodb%20+0)02+/yyWyArkJloldey
CTbqi^kapyKyCivqlqebTbqi^kap%22+2)14+5&yyWyFolkclodby
>ElkloqebCi^jb%JbkbqefiE^o_lo&yKy%.0)14&yyWyTbqi^kapyyNFAy..5/5yyBy

CObcrdbMlfkqbyKyCiv%6+2)26+4&yyWyTbqi^kapy
>ElkloqebCi^jb%ObcrdbMlfkq&yKy>o^qefEfdei^kap%2-)11&yyWy>o^qefEfdei^kapyyNFAy..5-1yyBy
>Abpb`o^qbqefpCfob%E^jjboc^ii&yKy>o^qefEfdei^kap%41)1.&yyWy>o^qefEfdei^kapyyNFAy..431yyBy

CPlrqepelobyKyCivqlPlrqepelob%12+5)23+.&yyWy>o^qefEfdei^kapy
ePlrqepelobyKyPbqvlroEb^oqeqlPlrqepelob)Fkkhbbmbo>kaboplk%2.+/)25+6&yWyEfiip_o^aCllqefiipy
>ElkloqebCi^jb%Plrqepelob&yKyEfiip_o^aCllqefiip%2-)13&yyWyEfiip_o^aCllqefiipyyNFAy..5.6yyBy
>Abpb`o^qbqefpCfob%Q^oobkJfii&yKyEfiip_o^aCllqefiip%25)/2&yyWyEfiip_o^aCllqefiipyyNFAy..443yyBy

O>iqbo^`Jlrkq^fkpyKyOrkql>iqbo^`Jlrkq^fkp%34+4)41+0&yWy>iqbo^`Jlrkq^fkpy
OTbpqbokMi^drbi^kapyKyOrkqlTbpqbokMi^drbi^kap%10+5)55+6&yyWyTbpqbokMi^drbi^kapy
>ElkloqebCi^jb%@efiitfka@^jm&yKyTbpqbokMi^drbi^kap%10)5/&yyWyTbpqbokMi^drbi^kapyyNFAy..5/4yyBy

C>bofbMb^hyKyCivql>bofbMb^h%1/+6)52+.&yyWyTbpqbokMi^drbi^kapy
>ElkloqebCi^jb%>bofbMb^h&yKyQebEfkqboi^kap%.1)2-&yyWyQebEfkqboi^kapyyNFAy..5/3yyBy
>Abpb`o^qbqefpCfob%Obs^kqrphSfii^db&yKyQebEfkqboi^kap%43)41&yyWyQebEfkqboi^kapyyNFAy..451yyBy
EPlrqepelobyRy3615y

OPfisbomfkbClobpqyKyOrkqlPfisbomfkbClobpq%33+.)46+4&yWyPfisbomfkbClobpqy
>Abpb`o^qbqefpCfob%QebPbmri`ebo&yKy%16)05&yyWyPfisbomfkbClobpqyyNFAy..25-yyBy

OQfofpc^iDi^abpyKyOrkqlQfofpc^iDi^abp%20+5)42+0&yyWyQfofpc^iDi^abpy
>Abpb`o^qbqefpCfob%?ofii&yKy%24)2/&yyWyQfofpc^iDi^abpyyNFAy..453yyBy
KPqb^iXCi^jblcRkabo`fqvZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%35)4&yyWyRkabo`fqvyyIy/0.5.y
>Pqb^ifkdRkab`fqv$pCi^jbyRy/0.5.yyLyyNFAy60/3y
OTbpqbokMi^drbi^kapyKyOfabqlTbpqbokMi^drbi^kap%/5+2)24+/&yyWyTbpqbokMi^drbi^kapy
CB^pqbokMi^drbi^kapyKyRpbqebcifdeqmlfkq^q@efiitfka@^jm%1/+6)52+.&yyWyTbpqbokMi^drbi^kapy
ODelpqi^kapyKyRpbqebmloq^i^q%15)52&yyWyDelpqi^kapy
>Abpb`o^qbqefpCfob%Qo^knrfifbk&yKyDelpqi^kap%13)/3&yyWyDelpqi^kapyyNFAy..441yyBy
OBsboplkdTllapyKyOrkqlBsboplkdTllap%15+6)55+/&yyWyBsboplkdTllapy
>Abpb`o^qbqefpCfob%KloqeP^k`qrj&yKyBsboplkdTllap%13)2-&yyWyBsboplkdTllapyyNFAy..44/yyBy
KPqb^iXCi^jblcPfisbojllkZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%35)1.&yyWyPfisbojllk@fqvyyIy02235y
>Pqb^ifkdPfisbojllk$pCi^jbyRy02235yyLyyNFAy..602y

K>wbolqeDrfab@ljmibqb

]]
end)
