DugisGuideViewer:RegisterGuide("Midsummer Festival Outland (60+)", nil, "Alliance", "D", function() 
return [[
AAA

KJ^kr^iQf`hObnrfobayKyArbqlqebrkfnrbk^qroblcqebJfaprjjbobsbkq)ArdfpDrfabSfbtboWfp`roobkqivrk^_ibql^rqlj^qf`^iivabqb`qqebnrbpq^kavlrtfiikbbaqlqf`hqeb`ljmibqbanrbpqj^kr^iiv+Tb^obtlohfkdlk^plirqflky
KQ^hb^Mloq^iqlPe^qqo^qe@fqv
>ElkloqebCi^jb%Qbolhh^oClobpq&yKy>iibof^kPqolkdelia%22)22&yyWyQbolhh^oClobpqyyNFAy..5/2yyBy
>Abpb`o^qbqefpCfob%Qbolhh^oClobpq&yKyPqlkb_ob^hboElia%2/)10&yyWyQbolhh^oClobpqyyNFAy..45/yyBy
>ElkloqebCi^jb%Pe^altjllkS^iibv&yKyTfiae^jjboPqolkdelia%1-)22&yyWyPe^altjllkS^iibvyyNFAy..5/0yyBy
>Abpb`o^qbqefpCfob%Pe^altjllkS^iibv&yKyPe^altjllkSfii^db%00)0-&yyWyPe^altjllkS^iibvyyNFAy..446yyBy
>ElkloqebCi^jb%K^do^ka&yKyQbi^^o%2-)4-&yyWyK^do^kayyNFAy..5/.yyBy
>Abpb`o^qbqefpCfob%K^do^ka&yKyD^o^a^o%2.)01&yyWyK^do^kayyNFAy..442yyBy
>ElkloqebCi^jb%W^kd^oj^ope&yKyQbiobalo%36)2/&yyWyW^kd^oj^opeyyNFAy..5/6yyBy
>Abpb`o^qbqefpCfob%W^kd^oj^ope&yKyW^_o^$Gfk%03)2/&yyWyW^kd^oj^opeyyNFAy..454yyBy
>ElkloqebCi^jb%EbiicfobMbkfkpri^&yKyElkloElia%3/)25&yyWyEbiicfobMbkfkpri^yyNFAy..5.5yyBy
>Abpb`o^qbqefpCfob%EbiicfobMbkfkpri^&yKyQeo^iij^o%24)1/&yyWyEbiicfobMbkfkpri^yyNFAy..442yyBy
>ElkloqebCi^jb%?i^ab$pBadbJlrkq^fkp&yKyPvis^k^^o%1/)33&yyWy?i^ab$pBadbJlrkq^fkpyyNFAy..5-4yyBy
>Abpb`o^qbqefpCfob%?i^ab$pBadbJlrkq^fkp&yKyQerkaboiloaPqolkdelia%2-)26&yyWy?i^ab$pBadbJlrkq^fkpyyNFAy..434yyBy
>ElkloqebCi^jb%Kbqebopqloj&yKy>ob^2/%0.)30&yyWyKbqebopqlojyyNFAy..50-yyBy
>Abpb`o^qbqefpCfob%Kbqebopqloj&yKy>ob^2/%0/)35&yyWyKbqebopqlojyyNFAy..466yyBy
KDrfab@ljmibqb

]]
end)
