DugisGuideViewer:RegisterGuide("Midsummer Festival Northrend (70+)", nil, "Alliance", "D", function() 
return [[
AAA

KJ^kr^iQf`hObnrfobayKyArbqlqebrkfnrbk^qroblcqebJfaprjjbobsbkq)ArdfpDrfabSfbtboWfp`roobkqivrk^_ibql^rqlj^qf`^iivabqb`qqebnrbpq^kavlrtfiikbbaqlqf`hqeb`ljmibqbanrbpqj^kr^iiv+Tb^obtlohfkdlk^plirqflky
K?bdfkColjA^i^o^k
>Abpb`o^qbqefpCfob%Peli^w^o?^pfk&yKyOfsbo$pEb^oq%14)3/&yyWyPeli^w^o?^pfkyyBy
>ElkloqebCi^jb%Peli^w^o?^pfk&yKyOfsbo$pEb^oq%14)33&yyWyPeli^w^o?^pfkyyBy
>Abpb`o^qbqefpCfob%?lob^kQrkao^&yKy?lo$dlolhLrqmlpq%2.)./&yyWy?lob^kQrkao^yyBy
>ElkloqebCi^jb%?lob^kQrkao^&yKyCfww`o^kh>fopqofm%22)/-&yyWy?lob^kQrkao^yyBy
>Abpb`o^qbqefpCfob%Ao^dlk_ifdeq&yKy>dj^o$pE^jjbo%06)15&yyWyAo^dlk_ifdeqyyBy
>ElkloqebCi^jb%Ao^dlk_ifdeq&yKyTfkqbod^oabHbbm%42)11&yyWyAo^dlk_ifdeqyyBy
>ElkloqebCi^jb%@ovpq^iplkdClobpq&yKyTfkaorkkbo$pLsboillh%45)42&yyWy@ovpq^iplkdClobpqyyBy
>Abpb`o^qbqefpCfob%@ovpq^iplkdClobpq&yKyPrkob^sbo$p@ljj^ka%5-)20&yyWy@ovpq^iplkdClobpqyyBy
>Abpb`o^qbqefpCfob%PqlojMb^hp&yKyH0%1-)53&yyWyQebPqlojMb^hpyyBy
>ElkloqebCi^jb%PqlojMb^hp&yKyH0%1/)54&yyWyQebPqlojMb^hpyyBy
>ElkloqebCi^jb%Wri$Ao^h&yKyQeb>odbkqPq^ka%1.)3.&yyWyWri$Ao^hyyBy
>Abpb`o^qbqefpCfob%Wri$Ao^h&yKyQeb>odbkqPq^ka%10)4.&yyWyWri$Ao^hyyBy
>Abpb`o^qbqefpCfob%DofwwivEfiip&yKy@lknrbpqElia%.6)3.&yyWyDofwwivEfiipyyBy
>ElkloqebCi^jb%DofwwivEfiip&yKy>j_bomfkbIladb%01)3.&yyWyDofwwivEfiipyyBy
>Abpb`o^qbqefpCfob%EltifkdCgloa&yKy@^jmTfkqboellc%15).0&yyWyEltifkdCgloayyBy
>ElkloqebCi^jb%EltifkdCgloa&yKyCloqTfiabos^o%25).3&yyWyEltifkdCgloayyBy
KDrfab@ljmibqb

]]
end)
