DugisGuideViewer:RegisterGuide("Winter Veil: Quest Chain", nil, "Alliance", "D", function() 
return [[
AAA

C@fqvlcFolkclodbyKyDlqlFolkclodby
>PqlibkTfkqboSbfiQob^qpyKyJ^`bvGfkdibml`hbq%00)34+3&yyNFAy4-1/yyWyFolkclodby

>Dob^q*c^qeboTfkqbofpEbobyKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy4-//yyWyFolkclodby
>JbqwbkqebObfkabboyKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy543/yyWyFolkclodby
RXPjlhvtllaP^q`ebiZyKyLmbkXPjlhvtllaP^q`ebiZyyRy/.0.2y
>QebOb^plkcloqebPb^plkyKyDlifHorjk%0-)3-&yNFAy4-3/yyWyFolkclodby

QDob^q*c^qeboTfkqbofpEbobyKyDob^qc^qeboTfkqbo%00)33&yyNFAy4-//yyWyFolkclodby
>Qob^qpcloDob^q*c^qeboTfkqboyKyDob^qc^qeboTfkqbo%00)33&yyNFAy4-/2yyWyFolkclodby

QQebOb^plkcloqebPb^plkyKyEfpqlof^kH^okfh%44)..&yyNFAy4-3/yyWyFolkclodby
>QebCb^pqlcTfkqboSbfiyKyEfpqlof^kH^okfh%44)..&yyNFAy4-30yyWyFolkclodby

QQebCb^pqlcTfkqboSbfiyKyHfkdJ^dkf?olkwb_b^oa%3-)2.+4&yyNFAy4-30yyWyFolkclodby
RQeoltXPklt_^iiZ^q@^fokb++yKyQeoltXPklt_^iiZ^qHfkdJ^dkf?olkwb_b^oa%06+0)22+6&clo^`efbsbjbkqyyRy.4/-/y

CPlrqePelobyKyCivqlPlrqePelobfkEfiip_o^aCllqefiipy

QPqlibkTfkqboSbfiQob^qpyKyPqo^kdbPkltj^k%02+/)4/+.&yyNFAy4-1/yyWy>iqbo^`Jlrkq^fkpy
>Vlr$ob^Jb^kLkb+++yKyPqo^kdbPkltj^k%02+/)4/+.&yyNFAy4-10yyWy>iqbo^`Jlrkq^fkpy
@Vlr$ob^Jb^kLkb+++yKyHfiiQeb>_ljfk^_ibDobbk`e^ka`liib`qqebXPqlibkQob^qpZ%0-)21&)%06+4)30+3&)%00)36&)%0-)31&)%1-)40&yyNFAy4-10yyWy>iqbo^`Jlrkq^fkpy
QVlr$ob^Jb^kLkb+++yKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy4-10yyWyFolkclodby
>>PjlhvtllaM^pqrobp$Qe^khVlryKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy4-12yyWyFolkclodby

CQelofrjMlfkqyKyCivqlQelofrjMlfkqy
KHfiiPqlkbDlibjplkvlrot^v+++yKyHfii^kvPqlkbDlibjpvlrpbbfkPb^ofkdDlodb^ka`liib`q2uXAbbmol`hP^iqZ%34+6)00+4&yyIy5.2-yyWyPb^ofkdDlodby
@JbqwbkqebObfkabboyKyCfkaJbqwbkqebObfkabbo%34+6)00+4&^kaq^ihqlefjyyNFAy543/yyWyPb^ofkdDlodby
KDbqXAbbmol`hP^iqZyKyHfii^kvPqlkbDlibjpvlrpbbfkPb^ofkdDlodb^ka`liib`qXAbbmol`hP^iqZyyIy5.2-y

C@fqvlcFolkclodbyKyDlqlFolkclodby

Q>PjlhvtllaM^pqrobp$Qe^khVlryKyDob^qc^qeboTfkqbo%00)33&yyNFAy4-12yyWyFolkclodby
QJbqwbkqebObfkabboyKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy543/yyWyFolkclodby
KQebEbollcqebA^vyKyQefpnrbpqobnrfobpvlrqle^sbibsbi0--`llhfkdphfiiqlmf`hrmy
>QebEbollcqebA^vyKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy5430yyWyFolkclodby
QQebEbollcqebA^vyKyTrijloqGfkdibml`hbq%00)34+3&yyNFAy5430yyWyFolkclodby

?.uXF`b@liaJfihZyKy?rv.uXF`b@liaJfihZcoljDtbkk^Cfob_obt%.5+4)2.+3&yyIy..46yyWyFolkclodby
KDfkdbo_ob^a@llhfbyKyBfqebo_rv2uXDfkdbo_ob^a@llhfbZcoljqeb>Elo`llhfqvlropbicvlrlkivkbbaibsbi.`llhfkdphfii)qebob`fmb^kaXElifa^vpmf`bpZfpplia_vTrijloqGfkdibml`hbq%00)34+3&^kaqebbddp`^k_bclrka_vhfiifkdqebCibpeofmmbopfkTbpqc^iiyyIy.4.642yyWyFolkclodby
QQob^qpcloDob^q*c^qeboTfkqboyKyDob^qc^qeboTfkqbo%00)33&yyNFAy4-/2yyWyFolkclodby

KTfkqboSbfiNrbpq@e^fk@ljmibqb

]]
end)
