DugisGuideViewer:RegisterGuide("Scholomance / Stratholme (55-58)", "", "Alliance", "I", function()
return [[
AAA


KIbsbi22ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi22qlmf`hrmqebcliiltfkdnrbpqpyyNFAy2010yyMIy22y

O@efiitfka@^jmyNFAy2010yyKyQo^sbiql@efiitfka@^jm%1/+6)52+.&yyWy.1//y
>?^olsC^jfivCloqrkbyNFAy2010yyKy%km`7..-/0&fkx@efiitfka@^jmz%10+2)50+5&yyWy.1//y

OIfdeq$pElmb@e^mbiyNFAy22/6yyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWy.1/0y
>Mi^drbaE^q`eifkdpyNFAy22/6yyKy%km`7..-02&fkxIfdeq$pElmb@e^mbiz%42+4)20+4&yyWy.1/0yyKM@y..-02y
>QebCibpeAlbpKlqIfbyNFAy2/./yyKy%km`7..-02&fkxIfdeq$pElmb@e^mbiz%42+4)20+4&yyWy.1/0yyKM@y..-02y
>QebDob^qCo^pPf^_fyNFAy2/.1yyKy%km`7..-00&fkxIfdeq$pElmb@e^mbiz%41+6)2/+/&yyWy.1/0yyKM@y..-00y
>ElrpbplcqebElivyNFAy2/10yyKy%km`7..-03&fkxIfdeq$pElmb@e^mbiz%42+6)2/+.&yyWy.1/0yyKM@y..-03y
>QebObpqibppPlrip%.&yNFAy2/5.yyKy%km`7..-05&fkxIfdeq$pElmb@e^mbiz%41)24+1&yyWy.1/0yyKM@y..-05y
>Qeb>o`efsfpqyNFAy2/2.yyKy%km`7..-06&fkxIfdeq$pElmb@e^mbiz%42+3)20+5&yyWy.1/0yyKM@y..-06y

OTbpqbokMi^drbi^kapyNFAy205/yyKyQo^sbiqlx@^boA^ooltzfkxTbpqbokMi^drbi^kapz%4-+/)40+5&yyWy.1//yyOB>@Ey
>Al`qloQeblibkHo^pqfkls)qeb?rq`eboyNFAy205/yyKy%km`7../.3&fkx@^boA^ooltz%4-+/)40+5&yyWy.1//yyKM@y../.3y

OP`elilj^k`byNFAy22/6yyKyWlkbfkqlcloP`elilj^k`b%4-+-0)41+.0&yyWy.1//yyFy
K%fqbj7.012-&yNFAy201.+0yyKy@liib`q%fqbj7.012-&)fqfpfkqebcfopqi^odbollj%ibcqpfab^pvlrt^ihfkqlqebollj&fk^pj^ii`lokbokbuqql^_llhpebiclkqlmlc^abphyyIy.012-yyAJ>MyP`elilj^k`b\>y
K%fqbj7.012.&yNFAy201.+1yyKy@liib`q%fqbj7.012.&)Fq$plk^abphqlqebofdeq`lokbolcqebollj_bclobAo^dlktebimpyyIy.012.yyAJ>MyP`elilj^k`b\>y
@Mi^drbaE^q`eifkdpyNFAy22/6yyKyHfii/-%km`7.-345&)fqfpqebollj_bclobO^qqibdlobyyAJ>MyP`elilj^k`b\>yyKM@y.-345y
H%km`7..3//7&yNFAy205/yyKyHfiiO^qqibdlobqldbqqeb%fqbj7.0540&cloqebkbuqpb`qflkyyIy.0540yyAJ>MyP`elilj^k`b\>yyKM@y..3//y
K%fqbj7.014.&yNFAy201.yyKyDlqlqebsfbtfkdollj^ka`liib`q%fqbj7.014.&fkpfab%km`7.-2-5&olljyyIy.014.yyAJ>MyP`elilj^k`b\>yyKM@y.-2-5y
@Al`qloQeblibkHo^pqfkls)qeb?rq`eboyNFAy205/yyKyQeb%km`7../3.&fplkqebqlmcillo)B^pqpfablk`bvlrhfiibaefjvlrkbbaql_rokqeb/_lafbpfkqebollj_v`if`hfkdlkfqyyWy.1//yyAJ>MyP`elilj^k`b\>yyKM@y../3.y
K%fqbj7.0115&yNFAy201.yyKy@liib`q%fqbj7.0115&tef`efpfkqeb)B^pqpfabollj_lqqljcillotebobIloa>ibubf?^olsyyIy.0115yyAJ>MyP`elilj^k`b\>yyKM@y.-2-1y

OTbpqbokMi^drbi^kapyQFAy205/yyKyBufqlrqqlx@^boA^ooltz%4-+/)40+5&yyWy.1//yyFy
QAl`qloQeblibkHo^pqfkls)qeb?rq`eboyNFAy205/yyKy%km`7../.3&fkx@^boA^ooltz%4-+/)40+5&yyWy.1//y

O@efiitfka@^jmyQFAy2010yyKyQo^sbiql@efiitfka@^jm%1/+6)52+.&yyWy.1//y
Q?^olsC^jfivCloqrkbyNFAy2010yyKy%km`7..-/0&fkx@efiitfka@^jmz%10+2)50+5&yyWy.1/-y

OIfdeq$pElmb@e^mbiyQFAy22/6yyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWy.1/0y
QMi^drbaE^q`eifkdpyNFAy22/6yyKy%km`7..-02&fkxIfdeq$pElmb@e^mbiz%42+4)20+4&yyWy.1/0yyKM@y..-02y

QQebObpqibppPlrip%.&yNFAy2/5.yyKy%km`7...1-&fkxB^pqbokMi^drbi^kapz%..+2)/5+5&yyWy.1/0yyKM@y...1-y
>QebObpqibppPlrip%/&yNFAy2/5/yyKy%km`7...1-&fkxB^pqbokMi^drbi^kapz%..+2)/5+5&yyWy.1/0yyKM@y...1-y

OPqo^qelijbyNFAy2/5/yyKyWlkbfkqlPqo^qelijbarkdblk%0-+55)/-+21&yyWy.1/0yyFy
@QebObpqibppPlrip%/&yNFAy2/5/yyKyQ^odbqqeb%km`7.-051&^ka%km`7.-052&fkPqo^qelijb)^karpbqeb%fqbj7.0/56&)fqtfii_b`ljb^ObpqibppPlri)_i^pqfq^d^fkqldbq`obafqcloqebnrbpqyyRy.0/56yyAJ>MyPqo^qelijb\>yyKM@y.-052).-051y
@QebDob^qCo^pPf^_fyNFAy2/.1yyKyColjqebbkqo^k`b)cliiltqebol^a^kaj^hb^e^fomfkqrokqlvlroIBCQ^kaqebobfp^_lulkqebcillokbuqqlqebj^fi_lu)lmbkfq^ka%km`7..-25&tfiipm^tk)Hfiiefj^ka`liib`q%fqbj7.0.4/&yyIy.0.4/yyAJ>MyPqo^qelijb\>yyKM@y..-25y
@ElrpbplcqebElivyNFAy2/10yyKyLmbkqeb`o^qbpp`^qqboba^olrkaPqo^qelijbp^ka`liib`q2%fqbj7.0.5-&^kaobjbj_boqlp^sbqebjcloqebnrbpqyyAJ>MyPqo^qelijb\>yyL?Gy002y
@QebCibpeAlbpKlqIfbyNFAy2/./yyKy@liib`q.-%fqbj7.0.41&qebpblkivaolmlccWlj_fbbkbjfbpfkpqo^qelijb%klqPhbibqlkp)Pmb`qo^iploDelpqp&yyAJ>MyPqo^qelijb\>yyKM@y.-1./).-05.).-1-2).-05/y
H%km`7.-5..&yNFAy2/2.yyKyHfii%km`7.-5..&ebfpfkqebP`^oibq_rfiafkd`ilpbqlqebi^pq_lpp)vlrtfii^iplkbbaql_rokqeb>o`efsb_v`if`hfkdlkfqyyWy.1/0yyAJ>MyPqo^qelijb\>yyKM@y.-5..y

OB^pqbokMi^drbi^kapyQFAy2/3/yyKyQo^sbiqlxB^pqbokMi^drbi^kapz%..+2)/5+5&yyWy.1/0y
QQebObpqibppPlrip%/&yNFAy2/5/yyKy%km`7...1-&fkxB^pqbokMi^drbi^kapz%..+2)/5+5&%..+2)/5+5&yyWy.1/0yyKM@y...1-y

OIfdeq$pElmb@e^mbiyQFAy2/2.yyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWy.1/0y
QQeb>o`efsfpqyNFAy2/2.yyKy%km`7..-06&fkxIfdeq$pElmb@e^mbiz%42+3)20+5&yyWy.1/0yyKM@y..-06y
QQebCibpeAlbpKlqIfbyNFAy2/./yyKy%km`7..-02&fkxIfdeq$pElmb@e^mbiz%42+4)20+4&yyWy.1/0yyKM@y..-02y
QQebDob^qCo^pPf^_fyNFAy2/.1yyKy%km`7..-00&fkxIfdeq$pElmb@e^mbiz%41+6)2/+/&yyWy.1/0yyKM@y..-00y
QElrpbplcqebElivyNFAy2/10yyKy%km`7..-03&fkxIfdeq$pElmb@e^mbiz%42+6)2/+.&yyWy.1/0yyKM@y..-03y

OPqo^qelijbyNFAy2/3/yyKyWlkbfkqlPqo^qelijbarkdblk%0-+55)/-+21&yyWy.1/0yyFy
H%km`7.-5.0&yNFAy2/3/yyKyHfii%km`7.-5.0&qebcfk^i_lppfkErj^kpfablcPqo^qelijb^kaillq%fqbj7.0/2-&yyIy.0/2-yyAJ>MyPqo^qelijb\>yyKM@y.-5.0y
>QebQorqe@ljbp@o^pefkdAltkyNFAy2/3/yyKyRpb%fqbj7.0/2-&ql^``bmqnrbpqyyRy.0/2-y

OIfdeq$pElmb@e^mbiyQFAy2/10yyKyQbibmloqqlxIfdeq$pElmb@e^mbiz%43+0)2/+2&yyWy.1/0y
QQebQorqe@ljbp@o^pefkdAltkyNFAy2/3/yyKy%km`7..-06&fkxIfdeq$pElmb@e^mbiz%42+3)20+5&yyWy.1/0yyKM@y..-06y

KDrfab@ljmibqb


]]
end)
